### ISSUE TITLE
Change altitude data by a companion computer？

### ISSUE THREAD

**Issue by hujunhan** [mavlink/mavros#1011]
Hi，I‘m using pixhawk and mavros to make a indoor autonomous drone.
    Here is my situation：Since the altitude measured by pixhawk's internal air pressure sensor is inaccurate. And I have a sonar sensor that  can be read distance data from it using my raspberrypi. Now what should I do to set the altitude(/mavros/local_position/pose pose.z)?
    Any advice will be helpful! thanks!

**Comment by TSC21** [comment]
This depends on the autopilot system and not from MAVROS directly. You should connect the range sensor on the Pixhawk directly and then, depending on the estimator and the autopilot firmware, the range data will be threaten differently. So this is a question that you need to push to the autopliots firmware forums.
