### ISSUE TITLE
[mavros_extras] mocap_estimate.cpp plugin

### ISSUE THREAD

**Issue by TSC21** [mavlink/mavros#102]
A plugin to connect to:
`vicon_bridge`: http://wiki.ros.org/vicon_bridge
or `vicon_mocap`: http://wiki.ros.org/vicon_mocap
Must have a tf_lookup to `vicon/<subject_name>/<segment_name>` or `~output` depending on the pkg being used.

Msg to send: `VICON_POSITION_ESTIMATE`
https://pixhawk.ethz.ch/mavlink/#VICON_POSITION_ESTIMATE

Note: Possible OptiTrack support can be added and message sent through `VICON_POSITION_ESTIMATE`. It can be connected to http://wiki.ros.org/mocap_optitrack.

**Comment by mhkabir** [comment]
Plugin works fine, can see data in PX4 side. No support for it in INAV though.

For users, please use vision_position plugin for now. It will give you the same functionality.
