### ISSUE TITLE
GPS horizontal accuracy

### ISSUE THREAD

**Issue by pavloblindnology** [mavlink/mavros#1020]
What is the reason of using HDOP value for computing horizontal accuracy of `GPS_RAW_INT` message instead of using `h_acc` values contained in the message? HDOP value is a scale factor, so, at least it should be multiplied by some metric accuracy estimation. Otherwise, it gives unrealistically small values.
https://github.com/mavlink/mavros/blob/38c6fff5aebf8d474e2fc6cad429ec99382bc0dc/mavros/src/plugins/global_position.cpp#L175

**Comment by vooon** [comment]
Just because that code done for a very long time before GPS_RAW_INT have extended with that fields.
And note, extension do not works with mavlink v1.0.

**Comment by pavloblindnology** [comment]
Understood.
Can we use extension values if on mavlink v2.0 and HDOP otherwise?
Also, I'd add some metric accuracy estimation parameter to config file to be scaled by HDOP, VDOP.
Is it feasible?

**Comment by TSC21** [comment]
> Understood.
Can we use extension values if on mavlink v2.0 and HDOP otherwise?
Also, I'd add some metric accuracy estimation parameter to config file to be scaled by HDOP, VDOP.
Is it feasible?

@pavloblindnology that seems reasonable to me. Can you please do a PR with it? Thank you!
