### ISSUE TITLE
Add /mavros/rc/override for PX4

### ISSUE THREAD

**Issue by TrishantRoy** [mavlink/mavros#1030]
**Feature Request**

*For Quadcopter Firmware*
Can the /mavros/rc/override topic be added in the PX4 firmware for sending channel values to Pixhawk? It is present in the APM firmware but it would be helpful if it is present in the PX4. 

PX4 has setpoint topics but it is helpful if you have the coordinates of the quadcopter.

Thanks.

**Comment by vooon** [comment]
That is already done.
