### ISSUE TITLE
Do anyone use the intel RTF drone for visual-inertial odometey/slam research?

### ISSUE THREAD

**Issue by zxp771** [mavlink/mavros#1031]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

Do anyone use the drone for visual-inertial odometey/slam research?
I have some question.
1.Could I change the imu operating frequency by myself.I record the imu/data it seems like its operating frequency is 50hz. I'm wondering if the imu can reach 100 or 200hz. because for most visual-inertial algorithms the data should be collect in this frequency.
2.how can I do the extrinsic parameter calibration(camera between imu)?
3.Does the imu and camera data I get from ros should in synchronization condition?I use rosbag fuction to record these data.

### MAVROS version and platform

Mavros: ?0.18.4?
ROS: ?Kinetic?
Ubuntu: ?16.04?

### Autopilot type and version

PX4

Version: ?3.7.1?

**Comment by zxp771** [comment]
@vooon @szebedy @zehortigoza

**Comment by zehortigoza** [comment]
Maybe you will get answers if you open a issue in PX4 or in some ROS related github/mail list/forum.

**Comment by indigomega** [comment]
hey there, i've seen this problem before. Here are the steps to solve all your problems:

1.  To change the publish rate, modify the ATTITUDE (for data_raw) and ATTITUDE_QUATERNION (for data with quaternion) in https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_main.cpp#L1789
this corresponds to your operation mode.
2. use the ROS package Kalibr
3. Unfortunately no. Follow this https://dev.px4.io/en/tutorials/camera_trigger.html#camera-imu-sync-example-vio

Hope this helps

**Comment by zxp771** [comment]
Hi @indigomega 

Thanks for your advise！

**Comment by zxp771** [comment]
@yc718764666 
I think you can get some idea from @indigomega 's answers.
I also figure out those problems before, so if you still have problem you can ask me.

**Comment by yc718764666** [comment]
hi  @zxp771 Thank you very much you are willing to give me help, my purpose is to use the px4 and VIO simulation under the gazebo, the current obstacles is not synchronized, cameras and innovative marketing information or deviation is bigger (I use is called VINS - MONO), I want to know how do you solve this problem, I use libgazebo_imu_plugin. so and libgazebo_camera_plugin. so to release two informations. Thank you again for your reply

**Comment by zxp771** [comment]
Hi@yc718764666 
I think you can check this first:https://dev.px4.io/en/tutorials/camera_trigger.html
And actually as I know the performance of VIO algorithms on the drone is really not good enough.(FOR SVO2.0 which add the imu data)

**Comment by yc718764666** [comment]
Hello @zxp771 
I'm sorry repling so late(Forgive me for seeing it now), your suggestion was useful, Thank your advice,
