### ISSUE TITLE
error with mavcmd takeoff and takeoffcur

### ISSUE THREAD

**Issue by xup682u03** [mavlink/mavros#1038]
I was using mavros on rpi3 and testing mavros .

connect to px4

```
 source ~/catkin_ws/devel/setup.bash
 roscore
 rosrun mavros mavros_node _fcu_url:=/dev/ttyAMA0:921600
```
----

### MAVROS version and platform

Mavros: 0.18.5
ROS: Kinetic
Ubuntu: 16.04 mate

### Autopilot type and version

[  ] ArduPilot
[O] PX4

### Issue details

I can run `rosrun mavros mavsafety arm` with motor rotating and `rosrun mavros mavcmd set home 0 0 0`  without error.
But i encountered some errors when running  **takeoff** and **takeoffcur** in mavcmd.

PS. I test in room in stead of outside.

----

error when running `rosrun mavros mavcmd takeoffcur 0 0 50`:
Request failed. Check mavros logs. ACK: 4 
error when running `rosrun mavros mavcmd takeoff 0 0 0 0 50`:
NavSatFix topic not exist 
![529_180529_0001](https://user-images.githubusercontent.com/39234690/40648308-b7d8dbfe-6360-11e8-95a7-8dc49244d2b2.jpg)

the mavros logs:
![529_180529_0002](https://user-images.githubusercontent.com/39234690/40648909-2aa6f19c-6362-11e8-874f-7ff18a44b7aa.jpg)

The above line with error appear when running `rosrun mavros mavsafety arm` **successfully**.

**Comment by TSC21** [comment]
> PS. I test in room in stead of outside.

You cannot takeoff with a position lock, meaning you need to have GPS signal available.

**Comment by xup682u03** [comment]
@TSC21 
Thanks for replying.

 This time I test on the roof  and face the same situation:
`rosrun mavros mavsafety arm` with motor rotating 
`rosrun mavros mavcmd set home 0 0 0` without error.
error when running `rosrun mavros mavcmd takeoffcur 0 0 50`:
NavSatFix topic not exist
error when running `rosrun mavros mavcmd takeoff 0 0 0 0 50`:
Request failed. Check mavros logs. ACK: 4

PS. Absolute height around 45m.
![61_180601_0004](https://user-images.githubusercontent.com/39234690/40836452-64020918-65c9-11e8-8c88-5dd6243d3cad.jpg)


RPI3 and UAV with  GPS signal available.
![61_180601_0002](https://user-images.githubusercontent.com/39234690/40836462-6a280e00-65c9-11e8-8474-27c397ffe289.jpg)


When I run `rosrun mavros mavcmd set home 0 0 0` without GPS signal available, I will get the error:
Request failed. Check mavros logs. ACK: 4  

Hope this can help.

**Comment by jamaruiz** [comment]
I'm having similar problems. Moving outdoors and getting a GPS signal does not change anything. Were you able to figure this out?

**Comment by vooon** [comment]
@xup682u03 you have APM firmware, not PX4.

Try to set GUIDED mode first.

**Comment by TSC21** [comment]
Solved in https://github.com/mavlink/mavros/pull/1128.
