### ISSUE TITLE
/tf empty

### ISSUE THREAD

**Issue by Mrrrbel** [mavlink/mavros#1044]
I am very new to ROS, and might be overlooking something very simple. I cannot get any data from /tf when I subscribe to it. I am able to see data from other rostopics though (such as /mavros/imu/data, /mavros/global_position/global, /tf_static). Any sort of guidance will be appreciated.  

### MAVROS version and platform

Mavros: 0.25.0 
ROS: Kinetic
Ubuntu: 16.04

pixhawk PX4 + radio connection

### Node logs
errors I am getting that is probably irrelevant 

```
[ WARN] [1527866466.260520026]: IMU: linear acceleration on RAW_IMU known on APM only.
[ WARN] [1527866466.260631040]: IMU: ~imu/data_raw stores unscaled raw acceleration report.
```

**Comment by vooon** [comment]
Very few plugins may publish transforms, and perhaps they not setup for that.
Usually tf tree should be defined in URDF file.
