### ISSUE TITLE
FCU external velocity estimation on px4

### ISSUE THREAD

**Issue by sehomi** [mavlink/mavros#1054]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

Hello guys! 
I am using mavros to connect my odroid xu4 to the pixhawk with apm firmware. my project is some kind of optical flow written as a ROS node and publishes /mavros/vision_speed/speed_vector topic. also vision_speed_estimate plugin is loaded but the problem is that I think the published velocities are not implemented in apm filters. the /mavros/local_position/* topics are always empty. In addition I have tried to publish /mavros/vision_pose/pose and the local positions are still empty.
how can I deliver my own optical flow velocities to apm kalman filters? or can this problem be solved with px4?

### MAVROS version and platform

ROS: Kinetic
Ubuntu Mate: 16.04

### Autopilot type and version

[  ] ArduPilot

Version: 3.5.5

### Node logs

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 0.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 0.0
 * /mavros/distance_sensor/rangefinder_pub/field_of_view: 0.0
 * /mavros/distance_sensor/rangefinder_pub/frame_id: lidar
 * /mavros/distance_sensor/rangefinder_pub/id: 0
 * /mavros/distance_sensor/rangefinder_pub/send_tf: False
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/rangefinder_sub/id: 1
 * /mavros/distance_sensor/rangefinder_sub/orientation: PITCH_270
 * /mavros/distance_sensor/rangefinder_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: /dev/ttySAC2:57600
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: True
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/estimator_type: 3
 * /mavros/odometry/frame_tf/desired_frame: ned
 * /mavros/plugin_blacklist: ['actuator_contro...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682389136
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: False
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: NONE
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /mavros/vision_speed/twist_cov: True
 * /rosdistro: kinetic
 * /rosversion: 1.12.12

NODES
  /
    mavros (mavros/mavros_node)

auto-starting new master
process[master]: started with pid [2899]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to bc4d0404-82d6-11e8-b29f-7cdd909f94e8
WARNING: Package name "Cam_Handler" does not follow the naming conventions. It should start witha lower case letter and only contain lower case letters, digits, underscores, and dashes.
process[rosout-1]: started with pid [2940]
started core service [/rosout]
process[mavros-2]: started with pid [2970]
[ INFO] [1531071944.869638076]: FCU URL: /dev/ttySAC2:57600
[ INFO] [1531071944.878464820]: serial0: device: /dev/ttySAC2 @ 57600 bps
[ INFO] [1531071944.879866737]: GCS bridge disabled
[ INFO] [1531071944.919590625]: Plugin 3dr_radio loaded
[ INFO] [1531071944.927909050]: Plugin 3dr_radio initialized
[ INFO] [1531071944.928050963]: Plugin actuator_control blacklisted
[ INFO] [1531071944.935849861]: Plugin adsb loaded
[ INFO] [1531071944.955213882]: Plugin adsb initialized
[ INFO] [1531071944.955361420]: Plugin altitude blacklisted
[ INFO] [1531071944.955835448]: Plugin cam_imu_sync loaded
[ INFO] [1531071944.959323596]: Plugin cam_imu_sync initialized
[ INFO] [1531071944.959883455]: Plugin command loaded
[ INFO] [1531071944.984026629]: Plugin command initialized
[ INFO] [1531071944.984172500]: Plugin debug_value blacklisted
[ INFO] [1531071944.984608529]: Plugin distance_sensor loaded
[ INFO] [1531071945.033258741]: Plugin distance_sensor initialized
[ INFO] [1531071945.033405820]: Plugin fake_gps blacklisted
[ INFO] [1531071945.033489192]: Plugin ftp blacklisted
[ INFO] [1531071945.034076259]: Plugin global_position loaded
[ INFO] [1531071945.122806557]: Plugin global_position initialized
[ INFO] [1531071945.122961052]: Plugin hil blacklisted
[ INFO] [1531071945.123057591]: Plugin home_position blacklisted
[ INFO] [1531071945.123658282]: Plugin imu loaded
[ INFO] [1531071945.169681362]: Plugin imu initialized
[ INFO] [1531071945.170244846]: Plugin local_position loaded
[ INFO] [1531071945.201732764]: Plugin local_position initialized
[ INFO] [1531071945.201913801]: Plugin manual_control blacklisted
[ INFO] [1531071945.202058797]: Plugin mocap_pose_estimate blacklisted
[ INFO] [1531071945.202173460]: Plugin obstacle_distance blacklisted
[ INFO] [1531071945.202277915]: Plugin odom blacklisted
[ INFO] [1531071945.202962229]: Plugin param loaded
[ INFO] [1531071945.214904673]: Plugin param initialized
[ INFO] [1531071945.215040711]: Plugin px4flow blacklisted
[ INFO] [1531071945.215515822]: Plugin rangefinder loaded
[ INFO] [1531071945.218805769]: Plugin rangefinder initialized
[ INFO] [1531071945.218959931]: Plugin rc_io blacklisted
[ INFO] [1531071945.219101927]: Plugin safety_area blacklisted
[ INFO] [1531071945.219222173]: Plugin setpoint_accel blacklisted
[ INFO] [1531071945.219815906]: Plugin setpoint_attitude loaded
[ INFO] [1531071945.276938497]: Plugin setpoint_attitude initialized
[ INFO] [1531071945.277083284]: Plugin setpoint_position blacklisted
[ INFO] [1531071945.277177990]: Plugin setpoint_raw blacklisted
[ INFO] [1531071945.277933635]: Plugin setpoint_velocity loaded
[ INFO] [1531071945.311206252]: Plugin setpoint_velocity initialized
[ INFO] [1531071945.311867857]: Plugin sys_status loaded
[ INFO] [1531071945.358776995]: Plugin sys_status initialized
[ INFO] [1531071945.359346520]: Plugin sys_time loaded
[ INFO] [1531071945.393580401]: TM: Timesync mode: NONE
[ INFO] [1531071945.399385982]: Plugin sys_time initialized
[ INFO] [1531071945.399867718]: Plugin trajectory loaded
[ INFO] [1531071945.429868889]: Plugin trajectory initialized
[ INFO] [1531071945.430524620]: Plugin vfr_hud loaded
[ INFO] [1531071945.433669237]: Plugin vfr_hud initialized
[ INFO] [1531071945.433826649]: Plugin vibration blacklisted
[ INFO] [1531071945.434253261]: Plugin vision_pose_estimate loaded
[ INFO] [1531071945.479597319]: Plugin vision_pose_estimate initialized
[ INFO] [1531071945.480169261]: Plugin vision_speed_estimate loaded
[ INFO] [1531071945.502991348]: Plugin vision_speed_estimate initialized
[ INFO] [1531071945.503554999]: Plugin waypoint loaded
[ INFO] [1531071945.525126414]: Plugin waypoint initialized
[ INFO] [1531071945.525744896]: Plugin wind_estimation loaded
[ INFO] [1531071945.528872597]: Plugin wind_estimation initialized
[ INFO] [1531071945.529043342]: Built-in SIMD instructions: None
[ INFO] [1531071945.529175130]: Built-in MAVLink package version: 2018.6.6
[ INFO] [1531071945.529363707]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1531071945.529495120]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ WARN] [1531071945.563003855]: TM: Wrong FCU time.
[ INFO] [1531071945.610214234]: IMU: Raw IMU message used.
[ WARN] [1531071945.610647638]: IMU: linear acceleration on RAW_IMU known on APM only.
[ WARN] [1531071945.610956629]: IMU: ~imu/data_raw stores unscaled raw acceleration report.
[ WARN] [1531071945.823418501]: GP: No GPS fix
[ INFO] [1531071945.923348807]: CON: Got HEARTBEAT, connected. FCU: ArduPilotMega / ArduCopter
[ INFO] [1531071947.168740304]: VER: 1.1: Capabilities         0x0000000000001bcf
[ INFO] [1531071947.169179916]: VER: 1.1: Flight software:     030505ff (27229c830384802e1bcae90b)
[ INFO] [1531071947.169524364]: VER: 1.1: Middleware software: 00000000 (0384802e1bcae90b)
[ INFO] [1531071947.169877229]: VER: 1.1: OS software:         00000000 (1bcae90b)
[ INFO] [1531071947.170203803]: VER: 1.1: Board hardware:      00000000
[ INFO] [1531071947.170530168]: VER: 1.1: VID/PID:             0000:0000
[ INFO] [1531071947.170792328]: VER: 1.1: UID:                 0000000000000000
[ WARN] [1531071947.171326895]: CMD: Unexpected command 520, result 0
[ INFO] [1531071956.146810265]: FCU: PX4: 0384802e NuttX: 1bcae90b
[ INFO] [1531071956.156262073]: FCU: Frame: QUAD
[ INFO] [1531071961.137866686]: WP: mission received
[ WARN] [1531071976.837330439]: GP: No GPS fix
[ INFO] [1531071998.149001532]: FCU: PX4v2 002C0033 3133470F 36393133
[ INFO] [1531071999.603424458]: PR: parameters list received
[ INFO] [1531071999.710286188]: FCU: APM:Copter V3.5.5 (27229c83)
^[[B[ WARN] [1531072005.588597966]: TM:

### Diagnostics

header: 
  seq: 105
  stamp: 
    secs: 1531072078
    nsecs:  30910961
  frame_id: ''
status: 
  - 
    level: 0
    name: "mavros: FCU connection"
    message: "connected"
    hardware_id: "/dev/ttySAC2:57600"
    values: 
      - 
        key: "Received packets:"
        value: "26652"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "229"
      - 
        key: "Tx sequence number:"
        value: "136"
      - 
        key: "Rx total bytes:"
        value: "766806"
      - 
        key: "Tx total bytes:"
        value: "2856"
      - 
        key: "Rx speed:"
        value: "8636.000000"
      - 
        key: "Tx speed:"
        value: "21.000000"
  - 
    level: 2
    name: "mavros: GPS"
    message: "No satellites"
    hardware_id: "/dev/ttySAC2:57600"
    values: 
      - 
        key: "Satellites visible"
        value: "0"
      - 
        key: "Fix type"
        value: "0"
      - 
        key: "EPH (m)"
        value: "99.99"
      - 
        key: "EPV (m)"
        value: "0.00"
  - 
    level: 0
    name: "mavros: Heartbeat"
    message: "Normal"
    hardware_id: "/dev/ttySAC2:57600"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "133"
      - 
        key: "Frequency (Hz)"
        value: "1.037008"
      - 
        key: "Vehicle type"
        value: "Quadrotor"
      - 
        key: "Autopilot type"
        value: "ArduPilotMega / ArduCopter"
      - 
        key: "Mode"
        value: "STABILIZE"
      - 
        key: "System status"
        value: "Standby"
  - 
    level: 2
    name: "mavros: System"
    message: "Sensor helth"
    hardware_id: "/dev/ttySAC2:57600"
    values: 
      - 
        key: "Sensor present"
        value: "0x0360FD4F"
      - 
        key: "Sensor enabled"
        value: "0x02601D4F"
      - 
        key: "Sensor helth"
        value: "0x0360FD0F"
      - 
        key: "3D gyro"
        value: "Ok"
      - 
        key: "3D accelerometer"
        value: "Ok"
      - 
        key: "3D magnetometer"
        value: "Ok"
      - 
        key: "absolute pressure"
        value: "Ok"
      - 
        key: "optical flow"
        value: "Fail"
      - 
        key: "laser based position"
        value: "Ok"
      - 
        key: "3D angular rate control"
        value: "Ok"
      - 
        key: "attitude stabilization"
        value: "Ok"
      - 
        key: "yaw position"
        value: "Ok"
      - 
        key: "AHRS subsystem health"
        value: "Ok"
      - 
        key: "Terrain subsystem health"
        value: "Ok"
      - 
        key: "Battery"
        value: "Ok"
      - 
        key: "CPU Load (%)"
        value: "39.7"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 1
    name: "mavros: Battery"
    message: "Low voltage"
    hardware_id: "/dev/ttySAC2:57600"
    values: 
      - 
        key: "Voltage"
        value: "0.00"
      - 
        key: "Current"
        value: "0.0"
      - 
        key: "Remaining"
        value: "100.0"
---

### Check ID

OK. I got messages from 1:1.

---
Received 3019 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 1, 2, 65, 24, 147, 150, 152, 27, 29, 30, 33, 163, 36, 165, 42, 173, 178, 182, 62, 193, 74, 35, 241, 116, 125

**Comment by mhkabir** [comment]
This is firmware specific, nothing to do with mavros. Please seek help at APM forums.
