### ISSUE TITLE
Late motor response

### ISSUE THREAD

**Issue by trishantroy** [mavlink/mavros#1056]
Hello,
I am using /mavros/rc/override topic to give channel values to the Pixhawk for controlling the quad. 
I am facing issue that the motors respond later (~1-2 secs) after giving channel value.

Has anyone else also faced the same issue or has any suggestions to solve the issue.

TIA

### MAVROS version and platform

Mavros: 0.26.0
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[  ] ArduPilot 3.5.5

**Comment by TSC21** [comment]
That's certainly a latency issue. What's the baudrate of your link? Please do follow the issue template.
