### ISSUE TITLE
Land at current GPS position - with ~cmd/land service

### ISSUE THREAD

**Issue by szebedy** [mavlink/mavros#1073]
Hi guys just a quick question:

Is it possible to land a PX4 drone at current GPS position with the ~cmd/land service?

If not, do you know a way to call the mavcmd landcur from a C++ ROS node?

Thanks in advance!

**Comment by vooon** [comment]
As i remember PX4 allow to use lat/lon=NAN, that meaning "use current".

**Comment by szebedy** [comment]
That works, thanks!
