### ISSUE TITLE
How to send SLAM position to APM

### ISSUE THREAD

**Issue by TomatoAndScallion** [mavlink/mavros#1085]
This is a problem that I face now

----

### Issue details

I want to send the SLAM position to APM，but I do not know which topic I should send to. I try to send message to /mavros/vision_pose/pose  and /mavros/local_pose/pose show nothing in rqt. No matter GUIDED flight mode and other mode I'm in, there still no messeage in local_pose topic. I refer to the following URL to set the parameters of the ardupliot。
http://ardupilot.org/dev/docs/ros-slam.html
By the why there is no problem with the hardware connection. There's no problem with the other topics.
Does anybody know how to solve this problem？
Thanks！
### MAVROS version and platform

Mavros: ?0.18.4?
ROS: ?Kinetic?
Ubuntu: ?16.04?

### Autopilot type and version
 ArduPilot

Version:3.5.7

**Comment by TSC21** [comment]
@TomatoAndScallion I suggest you bring that to the ArduPilot/VisionProjects Gitter channel. The issue tracker is usually used for solving bugs or punctual problems. For a more generic discussion I advise you to open the discussion on the forums.
Also, you didn't follow the issue template as asked, so it turns to be difficult to help you without further details.

**Comment by TomatoAndScallion** [comment]
> @TomatoAndScallion I suggest you bring that to the ArduPilot/VisionProjects Gitter channel. The issue tracker is usually used for solving bugs or punctual problems. For a more generic discussion I advise you to open the discussion on the forums.
> Also, you didn't follow the issue template as asked, so it turns to be difficult to help you without further details.

Thanks for your suggest. I have found the error of my program. It is because that I did not send right time stamp to mavros. Thanks for your reply again.

**Comment by YCH188** [comment]
@TomatoAndScallion Hello, I want to know how do you control the uav to fly to the position you set in slam situation. Do you use /mavros/setpoint_position/local or other topic in mavros? Does /mavros/setpoint_position/local setpoint according to vision_pose? Thanks a lot!

**Comment by TSC21** [comment]
@YCH188 again I gently ask you to stop posting on closed issues and open one to handle your case.
