### ISSUE TITLE
Setpoint Position in MAVLink

### ISSUE THREAD

**Issue by RR2-IP2** [mavlink/mavros#1086]
Hi,

I have achieved offboard control with MAVROS using a transform between the "map" and "setpoint" frames.  I enabled `setpoint_position tf listen` in `px4_config.yaml`, and the drone successfully listens to the commands being sent.

My question:
Does the setpoint get published to MAVLink and can I see it?  My understanding is that MAVROS takes the aforementioned transform and publishes it to MAVLink, but I cannot find this information using QGroundControl's Inspector / Analyze widgets.

I am new to drone development so I am sorry if this is a very fundamental question. Any help would be greatly appreciated!

Thanks in advance,
Justin

**Comment by TSC21** [comment]
Not MAVROS related. Please, check your autopilot SW docs and forums.
