### ISSUE TITLE
mavros and ArduCopter do not have the same origin of global frame?

### ISSUE THREAD

**Issue by aet2230** [mavlink/mavros#1097]
Hi
I use ArduCopter 3.5.5 with Pixhawk on Quadcopter.

I use MavROS to track quadrotor’s position online and give navigaton targets. Seems that the mavros/odometry is reported in ENU frame which origin is
arming position but the controller uses EKF origin (another position where quadcopter has been turned on and initialized). So if quadrotor has been moved to another location before arming, EKF and the odometry do not have the same origin.
 What is the way to track and command using the same frame? Only to reset EKF origin before takeoff,  or there is another ROS-topic which origin is EKF?

Thanks

**Comment by TSC21** [comment]
This topic was already addressed before (https://github.com/PX4/Firmware/issues/7632), and from what I know is still a TODO, but currently there's no command available in Mavlink `common.xml` that allows resetting the FCU estimator, so MAVROS doesn't also support it. If you want that to be possible, you would need to add support on both Mavlink and APM. The support on MAVROS, from there, would be as simple as a service call.
