### ISSUE TITLE
How to check if client is connected?

### ISSUE THREAD

**Issue by kossumov** [mavlink/mavros#1108]
Hey guys
How can I check if clinet (gcs on over tcp) is connected? I have to do certain things if client has been disconnected
**I'm not using gcs_bridge**

Thanks

**Comment by vooon** [comment]
For gcs connection status not checked. Only possible way to achieve that - modify gcs_link "message received callback" to add timeout timer.
Then you can detect disconnects.

**Comment by kossumov** [comment]
Thanks. Where in the code can I do it?

**Comment by kossumov** [comment]
Basically, What I was trying to accomplish is to disarm pixhawk if gcs disconnects.
Seems like mavros node turns off every time GCS unexpectedly disconnects. (By "unexpectedly" I mean if user does not click "disconnect" and closes Mission Planner, or internet turns off")
Is there a way to disarm pixhawk when GCS disconnects. (or when mavros turns off)?

**Comment by vooon** [comment]
But you don't even need to change anything. FCU already can react (or toggle failsafe) on that. Only what needed to be clarified - does they differentiate OBC and GCS heartbeats.
