### ISSUE TITLE
Can't arm via mavros UDP

### ISSUE THREAD

**Issue by tuloski** [mavlink/mavros#1129]
Hi,
I have a pixracer with both a serial telem and the wifi telem with ESP.
On the serial telem I'm able to ard/disarm from qGroundControl.
While with mavros via UDP (which overall works correctly) I'm unable to arm using the service. I get "success: false, result: 4".
What is the result 4?
I also tried "rosrun mavros mavsafety arm" without success.
I noticed that mavros writes a ROS_WARN "WP: timeout, retries N" and finally a ROS_ERR "WP: timed out". Why waipoint when I'm trying to arm?

**Comment by vooon** [comment]
Plugins mostly works independent, so problem with waypoint plugin likely have different reason than arming.

Result enumeration: [MAV_RESULT][1]

Usually firmware sends some log lines on arming requests. Please paste here mavros logs.
And better if you follow issue template.

[1]: https://mavlink.io/en/messages/common.html#MAV_RESULT

**Comment by amilcarlucas** [comment]
No answer for three months....

**Comment by tuloski** [comment]
@amilcarlucas I forgot about this because:

- I wasn't able to find mavros log.
- I switched to serial because it was a better connection and I didn't have any issue.

Now I don't have anymore the hardware to test it, but I remember clearly that the WP thing was coming out when trying to arm.
