### ISSUE TITLE
what does distance_sensor measure?

### ISSUE THREAD

**Issue by gladys0313** [mavlink/mavros#1169]
Hello,

This might be a stupid question (please forgive me if it indeed is...) I'm just wondering which distance does the distance_sensor measure. I read through the code but still don't have a clear idea. 

Thank you!

**Comment by vooon** [comment]
Plugin itself - measures nothing.
But FCU may use some rangefinders to measure height.
Or something else, read your ap docs.

**Comment by gladys0313** [comment]
@vooon thanks a lot!
