### ISSUE TITLE
mavros compilation error on arm64

### ISSUE THREAD

**Issue by acwatkins** [mavlink/mavros#1174]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

On amd64 platforms mavros builds fine, but on an arm64, specifically the NVidia TX2, there is a timing error between mavros_msgs and mavros, causing a compile error with a missing include. This is remedied by building twice.

**compile error:**
```
In file included from /ros_catkin_ws/src/mavros/mavros/include/mavros/utils.h:22:0,
                 from /ros_catkin_ws/src/mavros/mavros/include/mavros/mavros_uas.h:29,
                 from /ros_catkin_ws/src/mavros/mavros/src/lib/uas_data.cpp:17:
/ros_catkin_ws/src/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:17:33: fatal error: mavros_msgs/Mavlink.h: No such file or directory
compilation terminated.
mavros/mavros/CMakeFiles/mavros.dir/build.make:62: recipe for target 'mavros/mavros/CMakeFiles/mavros.dir/src/lib/uas_data.cpp.o' failed
```

### MAVROS version and platform

Mavros: 0.29 (master)
ROS: Kinetic
Ubuntu: 16.04

**Comment by KiloNovemberDelta** [comment]
Hello, 
I have succeed to install Mavros on the Jetson TX2 through the apt-get command : 
``install ros-kinetic-mavros ros-kinetic-mavros-extras``

Or you really want to build it from source and catkin_ws ?
