### ISSUE TITLE
How do I get the offset information of imu?

### ISSUE THREAD

**Issue by EdXian** [mavlink/mavros#1177]
### Issue details

Hi all,
I found my px4 has different imu offset during flying. How do I get the offset information of imu through mavros topics ?   I have to get the imu data without offset during the flight due to research purpose.
Thanks!

### MAVROS version and platform

Mavros: latest
ROS:Kinetic
Ubuntu: 16.04

### Autopilot type and version

 PX4

Version:1.7.3

**Comment by mhkabir** [comment]
HIGHRES_IMU is already bias compensated for PX4.
