### ISSUE TITLE
MAV_DISTANCE_SENSOR, more than one sensors...

### ISSUE THREAD

**Issue by logindiamant** [mavlink/mavros#1187]
Dear collegues,
I need to use more than one distance sensors, eg SF11/C, to check height (top and buttom)
How to do this? Thanks

**Comment by vooon** [comment]
You can config any amount of sensors, read config file.

**Comment by logindiamant** [comment]
Please, may be you wright some little examples?

**Comment by TSC21** [comment]
@logindiamant check [`px4_config.yaml`](https://github.com/mavlink/mavros/blob/master/mavros/launch/px4_config.yaml).
