### ISSUE TITLE
slow imu rate

### ISSUE THREAD

**Issue by rossj13** [mavlink/mavros#1189]
I have a pixracer connected to my PC through UDP via an esp8266. It uses the PX4 firmware. I am trying to use the IMU data_raw however I cannot get it to publish faster than 1.5hz (its pretty consistent 1.5)  I have tried set_stream service and using a extras.txt (I believe i did it right) however I cannot get the rate to increase. I can see that on the FCU the rate of the accelerator is 250 Hz. 

imu_data publishes at 20Hz, however the linear accelerations within the message only update at the 1.5Hz. I feel like I am missing something small. Any help would be appreciated.

**Comment by TSC21** [comment]
Related: https://github.com/mavlink/mavros/issues/1182
