### ISSUE TITLE
Cannot connect to APM using roslaunch 

### ISSUE THREAD

**Issue by nobody1114** [mavlink/mavros#1192]
roslaunch mavros apm2.launch fcu_url:=/dev/ttyACM0:115200
... logging to /home/user/.ros/log/125c1192-3f05-11e9-85df-2c27d725b00e/roslaunch-ubuntu-27557.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:46311/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_mav_type: ONBOARD_CONTROLLER
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/rangefinder_pub/field_of_view: 0.0
 * /mavros/distance_sensor/rangefinder_pub/frame_id: lidar
 * /mavros/distance_sensor/rangefinder_pub/id: 0
 * /mavros/distance_sensor/rangefinder_pub/send_tf: False
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/rangefinder_sub/id: 1
 * /mavros/distance_sensor/rangefinder_sub/orientation: PITCH_270
 * /mavros/distance_sensor/rangefinder_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: /dev/ttyACM0:115200
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/estimator_type: 3
 * /mavros/odometry/frame_tf/desired_frame: ned
 * /mavros/plugin_blacklist: ['actuator_contro...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682389136
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: False
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /mavros/wheel_odometry/child_frame_id: base_link
 * /mavros/wheel_odometry/count: 2
 * /mavros/wheel_odometry/frame_id: map
 * /mavros/wheel_odometry/send_raw: True
 * /mavros/wheel_odometry/send_twist: False
 * /mavros/wheel_odometry/tf/child_frame_id: base_link
 * /mavros/wheel_odometry/tf/frame_id: map
 * /mavros/wheel_odometry/tf/send: True
 * /mavros/wheel_odometry/use_rpm: False
 * /mavros/wheel_odometry/vel_error: 0.1
 * /mavros/wheel_odometry/wheel0/radius: 0.05
 * /mavros/wheel_odometry/wheel0/x: 0.0
 * /mavros/wheel_odometry/wheel0/y: -0.15
 * /mavros/wheel_odometry/wheel1/radius: 0.05
 * /mavros/wheel_odometry/wheel1/x: 0.0
 * /mavros/wheel_odometry/wheel1/y: 0.15
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    mavros (mavros/mavros_node)

ROS_MASTER_URI=http://localhost:11311

process[mavros-1]: started with pid [27575]
[ INFO] [1551764900.352190367]: FCU URL: /dev/ttyACM0:115200
[ INFO] [1551764900.354471970]: serial0: device: /dev/ttyACM0 @ 115200 bps
[ INFO] [1551764900.354858999]: GCS bridge disabled
[ INFO] [1551764900.370009088]: Plugin 3dr_radio loaded
[ INFO] [1551764900.373375058]: Plugin 3dr_radio initialized
[ INFO] [1551764900.373411480]: Plugin actuator_control blacklisted
[ INFO] [1551764900.376614185]: Plugin adsb loaded
[ INFO] [1551764900.382193236]: Plugin adsb initialized
[ INFO] [1551764900.382233215]: Plugin altitude blacklisted
[ INFO] [1551764900.382339378]: Plugin cam_imu_sync loaded
[ INFO] [1551764900.383144244]: Plugin cam_imu_sync initialized
[ INFO] [1551764900.383285187]: Plugin command loaded
[ INFO] [1551764900.391103142]: Plugin command initialized
[ INFO] [1551764900.391252144]: Plugin companion_process_status loaded
[ INFO] [1551764900.396264654]: Plugin companion_process_status initialized
[ INFO] [1551764900.396304360]: Plugin debug_value blacklisted
[ INFO] [1551764900.396429557]: Plugin distance_sensor loaded
[ INFO] [1551764900.414545730]: Plugin distance_sensor initialized
[ INFO] [1551764900.414758913]: Plugin fake_gps loaded
[ INFO] [1551764900.440417968]: Plugin fake_gps initialized
[ INFO] [1551764900.440475401]: Plugin ftp blacklisted
[ INFO] [1551764900.440705273]: Plugin global_position loaded
[ INFO] [1551764900.472141605]: Plugin global_position initialized
[ INFO] [1551764900.472338689]: Plugin gps_rtk loaded
[ INFO] [1551764900.478061313]: Plugin gps_rtk initialized
[ INFO] [1551764900.478112781]: Plugin hil blacklisted
[ INFO] [1551764900.478310003]: Plugin home_position loaded
[ INFO] [1551764900.484908162]: Plugin home_position initialized
[ INFO] [1551764900.485068929]: Plugin imu loaded
[ INFO] [1551764900.498757521]: Plugin imu initialized
[ INFO] [1551764900.498994190]: Plugin local_position loaded
[ INFO] [1551764900.513865394]: Plugin local_position initialized
[ INFO] [1551764900.514049117]: Plugin log_transfer loaded
[ INFO] [1551764900.518908572]: Plugin log_transfer initialized
[ INFO] [1551764900.519066775]: Plugin manual_control loaded
[ INFO] [1551764900.524467991]: Plugin manual_control initialized
[ INFO] [1551764900.524649077]: Plugin mocap_pose_estimate loaded
[ INFO] [1551764900.532945746]: Plugin mocap_pose_estimate initialized
[ INFO] [1551764900.533136330]: Plugin obstacle_distance loaded
[ INFO] [1551764900.538152727]: Plugin obstacle_distance initialized
[ INFO] [1551764900.538332130]: Plugin odom loaded
[ INFO] [1551764900.551263493]: Plugin odom initialized
[ INFO] [1551764900.551420235]: Plugin param loaded
[ INFO] [1551764900.555580124]: Plugin param initialized
[ INFO] [1551764900.555638909]: Plugin px4flow blacklisted
[ INFO] [1551764900.555805809]: Plugin rangefinder loaded
[ INFO] [1551764900.556994674]: Plugin rangefinder initialized
[ INFO] [1551764900.557178803]: Plugin rc_io loaded
[ INFO] [1551764900.564784801]: Plugin rc_io initialized
[ INFO] [1551764900.564835698]: Plugin safety_area blacklisted
[ INFO] [1551764900.565030629]: Plugin setpoint_accel loaded
[ INFO] [1551764900.571817408]: Plugin setpoint_accel initialized
[ INFO] [1551764900.572027821]: Plugin setpoint_attitude loaded
[ INFO] [1551764900.593162444]: Plugin setpoint_attitude initialized
[ INFO] [1551764900.593381603]: Plugin setpoint_position loaded
[ INFO] [1551764900.622004189]: Plugin setpoint_position initialized
[ INFO] [1551764900.622176811]: Plugin setpoint_raw loaded
[ INFO] [1551764900.638516111]: Plugin setpoint_raw initialized
[ INFO] [1551764900.638760008]: Plugin setpoint_velocity loaded
[ INFO] [1551764900.651461723]: Plugin setpoint_velocity initialized
[ INFO] [1551764900.651718238]: Plugin sys_status loaded
[ INFO] [1551764900.668896719]: Plugin sys_status initialized
[ INFO] [1551764900.669111732]: Plugin sys_time loaded
[ INFO] [1551764900.682488850]: TM: Timesync mode: MAVLINK
[ INFO] [1551764900.685192964]: Plugin sys_time initialized
[ INFO] [1551764900.685395621]: Plugin trajectory loaded
[ INFO] [1551764900.694626517]: Plugin trajectory initialized
[ INFO] [1551764900.694830245]: Plugin vfr_hud loaded
[ INFO] [1551764900.695891004]: Plugin vfr_hud initialized
[ INFO] [1551764900.695929378]: Plugin vibration blacklisted
[ INFO] [1551764900.696045782]: Plugin vision_pose_estimate loaded
[ INFO] [1551764900.712828163]: Plugin vision_pose_estimate initialized
[ INFO] [1551764900.712889187]: Plugin vision_speed_estimate blacklisted
[ INFO] [1551764900.713089851]: Plugin waypoint loaded
[ INFO] [1551764900.722272359]: Plugin waypoint initialized
[ INFO] [1551764900.722349150]: Plugin wheel_odometry blacklisted
[ INFO] [1551764900.722500988]: Plugin wind_estimation loaded
[ INFO] [1551764900.723246088]: Plugin wind_estimation initialized
[ INFO] [1551764900.723312631]: Built-in SIMD instructions: None
[ INFO] [1551764900.723338498]: Built-in MAVLink package version: 2019.2.2
[ INFO] [1551764900.723365691]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1551764900.723388682]: MAVROS started. MY ID 1.240, TARGET ID 1.1

rostopic echo -n1 /diagnostics | tee /tmp/diag.yml
header: 
  seq: 45
  stamp: 
    secs: 1551764952
    nsecs: 224074569
  frame_id: ''
status: 
  - 
    level: 1
    name: "mavros: FCU connection"
    message: "not connected"
    hardware_id: "/dev/ttyACM0:115200"
    values: 
      - 
        key: "Received packets:"
        value: "6"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "224"
      - 
        key: "Tx sequence number:"
        value: "105"
      - 
        key: "Rx total bytes:"
        value: "192"
      - 
        key: "Tx total bytes:"
        value: "16460"
      - 
        key: "Rx speed:"
        value: "0.000000"
      - 
        key: "Tx speed:"
        value: "460.000000"
  - 
    level: 2
    name: "mavros: GPS"
    message: "No satellites"
    hardware_id: "/dev/ttyACM0:115200"
    values: 
      - 
        key: "Satellites visible"
        value: "0"
      - 
        key: "Fix type"
        value: "0"
      - 
        key: "EPH (m)"
        value: "Unknown"
      - 
        key: "EPV (m)"
        value: "Unknown"
  - 
    level: 2
    name: "mavros: Heartbeat"
    message: "No events recorded."
    hardware_id: "/dev/ttyACM0:115200"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "0"
      - 
        key: "Frequency (Hz)"
        value: "0.000000"
      - 
        key: "Vehicle type"
        value: "Generic micro air vehicle"
      - 
        key: "Autopilot type"
        value: "Generic autopilot"
      - 
        key: "Mode"
        value: ''
      - 
        key: "System status"
        value: "Uninit"
  - 
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "/dev/ttyACM0:115200"
    values: 
      - 
        key: "Sensor present"
        value: "0x00000000"
      - 
        key: "Sensor enabled"
        value: "0x00000000"
      - 
        key: "Sensor helth"
        value: "0x00000000"
      - 
        key: "CPU Load (%)"
        value: "0.0"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 2
    name: "mavros: Battery"
    message: "No data"
    hardware_id: "/dev/ttyACM0:115200"
    values: 
      - 
        key: "Voltage"
        value: "-1.00"
      - 
        key: "Current"
        value: "0.0"
      - 
        key: "Remaining"
        value: "0.0"
  - 
    level: 2
    name: "mavros: Time Sync"
    message: "No events recorded."
    hardware_id: "/dev/ttyACM0:115200"
    values: 
      - 
        key: "Timesyncs since startup"
        value: "0"
      - 
        key: "Frequency (Hz)"
        value: "0.000000"
      - 
        key: "Last RTT (ms)"
        value: "0.000000"
      - 
        key: "Mean RTT (ms)"
        value: "0.000000"
      - 
        key: "Last remote time (s)"
        value: "0.000000000"
      - 
        key: "Estimated time offset (s)"
        value: "0.000000000"
---
I am new.
I connect my APM to my PC via USB and i had launch ROSCORE

**Comment by KiloNovemberDelta** [comment]
Which device are you using for running this ? Your computer or a controller like the Raspberry Pi ? 
Are you sure that you output is /dev/ttyACM0, and not for example /dev/ttyUSB0 (as you are using USB) ?

**Comment by nobody1114** [comment]
I use pc.i tried both

**Comment by KiloNovemberDelta** [comment]
Which port are you using in the Pixhawk ? TELEM1/2 or microUSB ? 
Can you provide here your Pixhawk parameters ?

**Comment by nobody1114** [comment]
I use apm and micro usb

**Comment by KiloNovemberDelta** [comment]
Can you check that SERIAL0_BAUD = 115 (115200) and SERIAL0_PROTOCOL = 1 ?
