### ISSUE TITLE
mavros build issue from source installation

### ISSUE THREAD

**Issue by AnnaMiG** [mavlink/mavros#1200]
Hello,
I'm following the instructions described in the [source installation](https://github.com/mavlink/mavros/tree/master/mavros#source-installation) and I get the following error when I do catkin build:

Errors     << mavros_extras:make /home/user/catkin_ws/logs/mavros_extras/build.make.000.log                                                                      
/home/user/catkin_ws/src/mavros/mavros_extras/src/plugins/odom.cpp: In member function ‘void mavros::extra_plugins::OdometryPlugin::handle_odom(const mavlink_message_t*, mavlink::common::msg::ODOMETRY&)’:
/home/user/catkin_ws/src/mavros/mavros_extras/src/plugins/odom.cpp:235:50: error: ‘struct mavlink::common::msg::ODOMETRY’ has no member named ‘twist_covariance’
   ftf::mavlink_urt_to_covariance_matrix(odom_msg.twist_covariance, cov_vel);
                                                  ^
/home/user/catkin_ws/src/mavros/mavros_extras/src/plugins/odom.cpp: In member function ‘void mavros::extra_plugins::OdometryPlugin::odom_cb(const ConstPtr&)’:
/home/user/catkin_ws/src/mavros/mavros_extras/src/plugins/odom.cpp:411:51: error: ‘struct mavlink::common::msg::ODOMETRY’ has no member named ‘twist_covariance’
   ftf::covariance_urt_to_mavlink(cov_vel_map, msg.twist_covariance);
                                                   ^
make[2]: *** [CMakeFiles/mavros_extras.dir/src/plugins/odom.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/mavros_extras.dir/all] Error 2
make: *** [all] Error 2
cd /home/user/catkin_ws/build/mavros_extras; catkin build --get-env mavros_extras | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
.................................................................................................................................................................
Failed     << mavros_extras:make                   [ Exited with code 2 ]                                                                                        
Failed    <<< mavros_extras                        [ 1 minute and 10.4 seconds ]                                                                                 
Abandoned <<< test_mavros                          [ Unrelated job failed ]                                                                                      
[build] Summary: 5 of 7 packages succeeded.                                                                                                                      
[build]   Ignored:   None.                                                                                                                                       
[build]   Warnings:  None.                                                                                                                                       
[build]   Abandoned: 1 packages were abandoned.                                                                                                                  
[build]   Failed:    1 packages failed.                                                                                                                          
[build] Runtime: 6 minutes and 28.4 seconds total.                                                                                                               
[build] Note: Workspace packages have changed, please re-source setup files to use them.

I'm using:
ROS: Kinetic
Ubuntu: 16.04

**Comment by TSC21** [comment]
This has been reported multiple times. Check the issues list. Current mavros master requires a release of ROS Mavlink package, which should happen soon. Closing
