### ISSUE TITLE
Navio2 with Px4

### ISSUE THREAD

**Issue by alexisutc** [mavlink/mavros#1202]
Hello world 

I'm trying to install the px4 on the navio2.

I proceeded to following :
[https://docs.px4.io/en/flight_controller/raspberry_pi_navio2.html](url)
[https://dev.px4.io/en/setup/dev_env_linux.html](url)
[https://dev.px4.io/en/setup/dev_env_linux_ubuntu.html#raspberry-pi-hardware](url)

i proceed to following :

> the command below builds the target for Raspberry Pi 2/3 Navio2.
>Cross-compiler Build
>
>cd Firmware
>make emlid_navio2_cross # for cross-compiler build
>
>The "px4" executable file is in the directory build/emlid_navio2_cross/. Make sure you can connect to >your RPi over ssh, see instructions how to access your RPi.
>
>Then set the IP (or hostname) of your RPi using:
>
>export AUTOPILOT_HOST=192.168.X.X
>
>And upload it with:
>
>cd Firmware
>make emlid_navio2_cross upload # for cross-compiler build
>
>Then, connect over ssh and run it with (as root):
>
>sudo ./bin/px4 -s px4.config

but when i do 

>make emlid_navio2_cross upload

i have following problem :

[0/1] uploading px4
ssh: Could not resolve hostname : No address associated with hostname
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.2]
FAILED: boards/emlid/navio2/CMakeFiles/upload
cd /home/pi/Firmware/build/emlid_navio2_cross/boards/emlid/navio2 && rsync -arh --progress /home/pi/Firmware/build/emlid_navio2_cross /home/pi/Firmware/posix-configs/rpi/*.config /home/pi/Firmware/ROMFS pi@"":/home/pi
ninja: build stopped: subcommand failed.
Makefile:190: recipe for target 'emlid_navio2_cross' failed
make: *** [emlid_navio2_cross] Error 1

Anyway, i was looking to connect via QGroundControl without sucess.

Has anybody an idear ? thx

### MAVROS version and platform

Mavros: ?0.18.4?
ROS: ?Kinetic?
RPI + navio2

### Autopilot type and version

[  ] ArduPilot
[ x ] PX4

### Diagnostics

header:
  seq: 1206
  stamp:
    secs: 1551971027
    nsecs: 698169291
  frame_id: ''
status:
  -
    level: 1
    name: "mavros: FCU connection"
    message: "not connected"
    hardware_id: "udp://:14650@"
    values:
      -
        key: "Received packets:"
        value: "0"
      -
        key: "Dropped packets:"
        value: "0"
      -
        key: "Buffer overruns:"
        value: "0"
      -
        key: "Parse errors:"
        value: "0"
      -
        key: "Rx sequence number:"
        value: "0"
      -
        key: "Tx sequence number:"
        value: "0"
      -
        key: "Rx total bytes:"
        value: "0"
      -
        key: "Tx total bytes:"
        value: "0"
      -
        key: "Rx speed:"
        value: "0.000000"
      -
        key: "Tx speed:"
        value: "0.000000"
  -
    level: 2
    name: "mavros: GPS"
    message: "No satellites"
    hardware_id: "udp://:14650@"
    values:
      -
        key: "Satellites visible"
        value: "0"
      -
        key: "Fix type"
        value: "0"
      -
        key: "EPH (m)"
        value: "Unknown"
      -
        key: "EPV (m)"
        value: "Unknown"
  -
    level: 2
    name: "mavros: Heartbeat"
    message: "No events recorded."
    hardware_id: "udp://:14650@"
    values:
      -
        key: "Heartbeats since startup"
        value: "0"
      -
        key: "Frequency (Hz)"
        value: "0.000000"
      -
        key: "Vehicle type"
        value: "Generic micro air vehicle"
      -
        key: "Autopilot type"
        value: "Generic autopilot"
      -
        key: "Mode"
        value: ''
      -
        key: "System status"
        value: "Uninit"
  -
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "udp://:14650@"
    values:
      -
        key: "Sensor present"
        value: "0x00000000"
      -
        key: "Sensor enabled"
        value: "0x00000000"
      -
        key: "Sensor helth"
        value: "0x00000000"
      -
        key: "CPU Load (%)"
        value: "0.0"
      -
        key: "Drop rate (%)"
        value: "0.0"
      -
        key: "Errors comm"
        value: "0"
      -
        key: "Errors count #1"
        value: "0"
      -
        key: "Errors count #2"
        value: "0"
      -
        key: "Errors count #3"
        value: "0"
      -
        key: "Errors count #4"
        value: "0"
  -
    level: 2
    name: "mavros: Battery"
    message: "No data"
    hardware_id: "udp://:14650@"
    values:
      -
        key: "Voltage"
        value: "-1.00"
      -
        key: "Current"
        value: "0.0"
      -
        key: "Remaining"
        value: "0.0"
  -
    level: 2
    name: "mavros: Time Sync"
    message: "No events recorded."
    hardware_id: "udp://:14650@"
    values:
      -
        key: "Timesyncs since startup"
        value: "0"
      -
        key: "Frequency (Hz)"
        value: "0.000000"
      -
        key: "Last RTT (ms)"
        value: "0.000000"
      -
        key: "Mean RTT (ms)"
        value: "0.000000"
      -
        key: "Last remote time (s)"
        value: "0.000000000"
      -
        key: "Estimated time offset (s)"
        value: "0.000000000"

### Check ID

ERROR. I got 0 addresses, but not your target 1:1

---
Received 0 messages, from 0 addresses
sys:comp   list of messages

**Comment by TSC21** [comment]
This has nothing to do with MAVROS. Please move this to the appropriate PX4 channels.
