### ISSUE TITLE
error: 'struct mavlink::common::msg::ODOMETRY' has no member named 'velocity_covariance'

### ISSUE THREAD

**Issue by Kumaron** [mavlink/mavros#1215]
### Issue detail
Error occurs while building PX4/avoidance
`error: 'struct mavlink::common::msg::ODOMETRY' has no member named 'velocity_covariance'`

### MAVROS version and platform

Mavros: today's master
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

PX4

Version: master

**Comment by TSC21** [comment]
Update your Mavlink headers. This is a duplicated and solved issue.
