### ISSUE TITLE
Arm state unstable

### ISSUE THREAD

**Issue by nicovanduijn** [mavlink/mavros#1227]
### Issue details

In our system we sometimes encounter a situation where the drone is armed, but the mavros on our companion computer is publishing alternating 'True' and 'False' on the `/mavros/state/armed` topic.

I'm not sure how easy this is to reproduce. It comes and goes quite randomly on our system.

Any ideas what could be causing this?

### MAVROS version and platform

Mavros: 0.29.0
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[  ] ArduPilot
[ X] PX4

Version: Upstream

### Node logs
![image](https://user-images.githubusercontent.com/14265408/56966083-c0f6ac00-6b5e-11e9-9e7c-7f4a42a4306f.png)

[Rosbag](https://drive.google.com/file/d/1Op0GOlDSmBwJJSSiT0m_suO52EQdfQJQ/view?usp=sharing)

**Comment by vooon** [comment]
Probably you have several sources. Please catch some more full `/mavros/state`.
Also need to have diagnostics and node logs.

**Comment by nicovanduijn** [comment]
It's difficult to reproduce, but I'll make sure to log `/diagnostics` and all mavros topics next time I see it.

What else do you need? I did log `mavros/state`, right? (In the bag linked above)

**Comment by nicovanduijn** [comment]
Here's a bag with all mavros topics and the `/diagnostics`
[rosbag](https://drive.google.com/file/d/1OJiujZpt9mhwJPHtChD1UHHRwUrDucmD/view?usp=sharing)

**Comment by nicovanduijn** [comment]
Turns out we ran into this: #1107

**Comment by TSC21** [comment]
@nicovanduijn this gets fixed with #1228 right?

**Comment by nicovanduijn** [comment]
Yes!
