### ISSUE TITLE
how can I use the plugin of fake_gps.cpp on px4 firmware?

### ISSUE THREAD

**Issue by XiaoJake** [mavlink/mavros#1243]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

I originally wanted to follow indoor/fake gps tutorial on the px4 development guide at http://dev.px4.io/advanced-fake-gps.html, but the website is 404.

And then I find a similar article,but I can't find the parameters described in article in my QGC,like "ATT_EXT_HDG_M","INAV_DISAB_MOCAP ",and I don't know where to find "default Group".

![image](https://user-images.githubusercontent.com/30372147/58689733-65684a00-83ba-11e9-96e9-b4ae1e01727c.png)

Is my  px4 firmware version too new?
Has anyone successfully used fake_gps plugin with vision ? Can you tell me the configure steps?Please!

### MAVROS version and platform

Mavros: master
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version
PX4
Version: 1.8.2(px4_fmu-v2_lpe.px4)

**Comment by TSC21** [comment]
@XiaoJake two notes:
1. I don't know exactly where are you checking that documentation, but the link you shared doesn't work and the instructions I am seeing in the image you sent are clearly outdated;
2. Before opening an issue here, and considering that you are trying to follow a PX4 guide, first try to ask your questions on the appropriate PX4 forum and Slack, before asking your questions here - the issue tracking is ideally to solve problems, propose features.
