### ISSUE TITLE
What is the initial GPS coordinate (/mavros/global_position/global) on px4 in sitl

### ISSUE THREAD

**Issue by elgarbe** [mavlink/mavros#1246]
https://github.com/mavlink/mavros/issues/1245

this is not what I ask, I would like to know what is the default value, not how to set a new one. I want to leave px4 firmware build from default values.

**Comment by TSC21** [comment]
Please do no reopen issues related to the same topic. Thank you.

**Comment by loicgirard** [comment]
That's a super response thanks evryone
