### ISSUE TITLE
Frame of reference for /mavros/setpoint_raw/attitude and /mavros/local_position/odom topics

### ISSUE THREAD

**Issue by rishab26201** [mavlink/mavros#1251]
Hi,
So I want to move my drone from my current position to a given position and land it. For this I am using the mavros/setpoint_raw/attitude topic and getting my data from /mavros/local_position/odom. I have some queries. 

1) The twist.linear and twist.angular data are in correspondence to which frame of reference, the global or body fixed frame?
2) Am I right in assuming the pose.orientation in odom topic is with respect to the global frame.
3) In the setpoint_raw/attitude topic is the thrust with respect to the body fixed frame? What is the frame of reference for the orientation and body rate.

For example if I give an input orientation of pitch 15 degrees and body_rate 0.1 in z direction, the mavros controller shows a pitch of 15, but the odom topic shows changing orientations. The drone however contiues to move in the x direction of the body fixed frame

Thanks

**Comment by chenhanpolyu** [comment]
1. body fixed frame
2. yes
3. thrust is with respect to body frame. the orientation and body rate in this setpoint_raw/attitude message are for the body frame, but in NED convention. For most mavros messages, they use ENU , the same as ROS. But for messages with "raw", they use NED (https://mavlink.io/en/messages/common.html#SET_ATTITUDE_TARGET). so if you want to publish the orientation setpoint with this raw message, please be careful to convert the commant between different coordinate convention.
