### ISSUE TITLE
alternative for MAVLINK FTP on ardupilot

### ISSUE THREAD

**Issue by kornee-mainblades** [mavlink/mavros#1253]
----

### Issue details
MAVLINK FTP for use on ardupilot.

Hello everybody,

For a project I like to send data from a GCS (such as: MissionPlanner/ROS computer/APMPlanner2 etc.) via the FCU to my payload, a computer. A good solution would be something like MAVLINK-FTP unfortunately this is not available for Ardupilot. Is there another solution for this? Or is the feature MAVLINK-FTP comming soon available for use on Ardupilot?
I like to send various kinds of data but mainly an alternative safety box/fencing, which I like to use for navigation in the payload. However, this should not interfere with the normal fencing of the drone.

Thanks in advance, Kornee

### MAVROS version and platform

ROS: melodic
Ubuntu: 18.04

### Autopilot type and version

[ x ] ArduPilot
[  ] PX4

**Comment by mhkabir** [comment]
Please ask on the Ardupilot forums. discuss.ardupilot.org
