### ISSUE TITLE
Mavros don't stop after SIGINT (^C)

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#130]
Termination are broken in 0.7: mavros_node ignore SIGINT, but stops after SIGTERM.
Also now it ignore `rosnode kill mavros`.

Also termination at port closed event also broken (mavconn related).
```
[ERROR] [1408358771.110588398]: serial0:receive: End of file
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
```

**Comment by vooon** [comment]
Please check now.
After https://github.com/mavlink/mavros/commit/298b66869ca21f9983041d116665730eab718b2a it closes on `tcp://`.

**Comment by vooon** [comment]
Reports + my tests:

1. Ubuntu 14.04.1 LTS + Indigo => bug present
2. Ubuntu 14.10 + Indigo (don't do it yourself :) ) => bug is gone.

I think that main difference is gcc and stdc++ version (4.8 or 4.9).

**Comment by TSC21** [comment]
@vooon is this bug still present? For my experience it works on 14.04.2, even though it takes some time to shut.

**Comment by vooon** [comment]
Bug still present. I think you used launch scripts, and roslaunch does SIGTERM if node not responding to termination request in time.

**Comment by vooon** [comment]
Still there :(. Perhaps bug in libmavconn locking, but i do not know which tool may help with bug finding.
