### ISSUE TITLE
Installing mavros on Ros melodic for Nvidia Nano

### ISSUE THREAD

**Issue by fishworx** [mavlink/mavros#1310]
Please see below, mavros for melodic did not install....

sudo apt-get install ros-melodic-mavros ros-melodic-mavros-extras

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-melodic-mavros : Depends: ros-melodic-diagnostic-updater but it is not going to be installed
                      Depends: ros-melodic-pluginlib but it is not going to be installed
                      Depends: ros-melodic-rosconsole-bridge but it is not going to be installed
                      Depends: ros-melodic-roscpp but it is not going to be installed
                      Depends: ros-melodic-rospy but it is not going to be installed
                      Depends: ros-melodic-tf2-ros but it is not going to be installed
 ros-melodic-mavros-extras : Depends: ros-melodic-roscpp but it is not going to be installed
                             Depends: ros-melodic-tf but it is not going to be installed
                             Depends: ros-melodic-urdf but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

![Screenshot from 2019-09-07 21-08-43](https://user-images.githubusercontent.com/29113771/64474166-4a288a00-d1b4-11e9-9959-815760782096.png)
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

_Please describe the problem, or desired feature_

### MAVROS version and platform

Mavros: ?0.18.4?
ROS: ?Kinetic?
Ubuntu: ?16.04?

### Autopilot type and version

[  ] ArduPilot
[  ] PX4

Version: ?3.7.1?

### Node logs

```
copy output of mavros_node. Usually console where you run roslaunch
```

### Diagnostics

```
place here result of:
rostopic echo -n1 /diagnostics
```

### Check ID

```
rosrun mavros checkid
```

**Comment by Jaeyoung-Lim** [comment]
Try 'source /opt/ros/melodic/setup.bash'

**Comment by fishworx** [comment]
not sure if (Try 'source /opt/ros/melodic/setup.bash') worked....

![Screenshot from 2019-09-08 00-05-20](https://user-images.githubusercontent.com/29113771/64476043-9cc27000-d1cd-11e9-8007-fbce1a993d0d.png)

![Screenshot from 2019-09-08 00-14-38](https://user-images.githubusercontent.com/29113771/64476052-af3ca980-d1cd-11e9-894b-9d7159cdbfb3.png)

**Comment by TSC21** [comment]
@fishworx do you even have ROS Melodic installed in your system? From the output above, it seems like you don't.

**Comment by TSC21** [comment]
http://wiki.ros.org/melodic/Installation/Ubuntu

**Comment by fishworx** [comment]
@TSC21 , reflashing sd card now and restarting melodic install from scratch....

**Comment by fishworx** [comment]
It looks like it worked.... How do i test it works? Also, it is necessary to install thee GeographicLib datasets?

https://github.com/mavlink/mavros/blob/master/mavros/README.md#installation


![Screenshot from 2019-09-09 16-24-12](https://user-images.githubusercontent.com/29113771/64507559-6fd1a280-d31e-11e9-90aa-d0a655f580df.png)

**Comment by canberkgurel** [comment]
yes, GeographicLib is required.

**Comment by ashirsat** [comment]
@fishworx If that solved your issue please close the ticket. Thanks
