### ISSUE TITLE
Controlling Servo with Mavros commands on PX4's aux pins

### ISSUE THREAD

**Issue by Ken-Thorburn** [mavlink/mavros#1316]
### Issue details
I'm trying to control a servo with the Aux pins on a Pixhawk. The ability to do so seems deprecated and for Arducopter seems to be an option only for waypoint mission planning but not python commands. 

If anyone has had success doing this, please let me know as there isn't a guide on the wiki. If I can't figure it out I will most likely get a standalone Arduino board to connect to ROS on the onboard Nuc. 

### MAVROS version and platform

Mavros: 0.18.4
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

PX4 1.90

**Comment by TSC21** [comment]
The issue tracker serves the purpose of reporting issues/bugs or request for features. Please use the respecrive forums to request autopilot related help.
