### ISSUE TITLE
Alternate way for providing GPS

### ISSUE THREAD

**Issue by utkarsh447** [mavlink/mavros#1324]
Hi, sorry it is meant for bug and feature issue only, But i require some information which i can't find in different links.

----

### Scenario

I want to control my drone by using mavros and a device which is providing global coordinates and other parameters which are required for GPS. It is connected to my raspberry PI and I want to re-route this data to Pixhawk, So that pixhawk will treat that as it's GPS data.

I came over `fake-gps` plugin, but it generates local coordinates with given reference point. But in my scenario i have global coordinates and i don't want to transform it to local coordinates.

Can you suggest method or `mavros topic` which will take GPS data and re-route it to send that data to pixhawk and pixhawk will treat that as it's own GPS data and work as usual with different mavros topics?

### MAVROS version and platform

Mavros: 0.18.4
ROS: Kinetic
Ubuntu: Mate 16.04

### Autopilot type and version

[ X ] ArduPilot
[  ] PX4

**Comment by TSC21** [comment]
Publish to https://github.com/mavlink/mavros/blob/master/mavros/src/plugins/hil.cpp#L53 topic to publish `HIL_GPS` messages and make the required config on Ardupilot, if any.
