### ISSUE TITLE
Cannot specify frame for output of obstacle_distance plugin

### ISSUE THREAD

**Issue by mortenfyhn** [mavlink/mavros#1330]
### Issue details

The `obstacle_distance` plugin sends a mavlink [OBSTACLE_DISTANCE](https://mavlink.io/en/messages/common.html#OBSTACLE_DISTANCE) message, but the plugin does not specify the `frame` field of the message, so it defaults to `MAV_FRAME_GLOBAL`. I reckon the user should be able to specify this through a ROS parameter for the plugin. Do you agree? I can make the PR.

The upcoming v1.10.0 PX4 release has some changes to the collision prevention code where it now supports frames GLOBAL, LOCAL_NED, and BODY_FRD for obstacle distances, so it would be convenient to update the plugin accordingly.

### MAVROS version and platform

Mavros: 0.33.0
ROS: Melodic
Ubuntu: 18.04

### Autopilot type and version

[ ] ArduPilot
[x] PX4

Version: v1.10.0-beta2

### Node logs

N/A.

### Diagnostics

N/A.
### Check ID

N/A.

**Comment by TSC21** [comment]
@mortenfyhn a PR is welcomed. Though, take into consideration that it should take some time before a new MAVROS release is done, considering 0.33.0 was released yesterday.

**Comment by mortenfyhn** [comment]
Cool, I'll make the PR. And thanks for notifying me about the release, shouldn't be a problem though.
