### ISSUE TITLE
No plugin publishing for px4 estimator status.

### ISSUE THREAD

**Issue by saifullah3396** [mavlink/mavros#1348]
### Issue details

Hi, my work involves using the px4-mavros integration for uavs in simulations. For that I require to  repeatedly switch on/off the estimator after every simulation iteration for which I use the px4-ekf2/local_position_estimator binaries. However I found no reliable way to get the current status of the estimator and to check whether the estimator has stabilized and started giving outputs with valid states in mavros. I saw that mavlink already provides a message for that but its not being published by any mavros plugin.

To solve the problem I've made a estimator_status plugin that publishes it with the following message:

```std_msgs/Header header
bool stable_attitude
bool stable_hor_velocity_est
bool stable_ver_velocity_est
bool stable_hor_position_est_rel
bool stable_hor_position_est_abs
bool stable_ver_position_est_abs
bool stable_ver_position_est_agl
bool const_position_mode
bool pred_hor_position_rel
bool pred_hor_position_abs
bool gps_glitch
bool accel_error```

Each bool represents the corresponding ESTIMATOR_STATUS_FLAGS defined in mavlink message definitions.h. Is this the right way to solve the problem or is there any other way? If yes then can I PR this addition?

### MAVROS version and platform

Mavros: ?0.18.4?
ROS: ?Melodic?
Ubuntu: ?18.04?


### Autopilot type and version

[  ] ArduPilot
[x] PX4

Version: ?3.7.1?

**Comment by Jaeyoung-Lim** [comment]
@saifullah3396 Did you make a pull request?

**Comment by saifullah3396** [comment]
@Jaeyoung-Lim Not yet.

**Comment by TSC21** [comment]
Everything status related pleasr put it under the sys_status plugin. No need for another plugin.
