### ISSUE TITLE
Is/Clock being published??

### ISSUE THREAD

**Issue by woongjoonchoi** [mavlink/mavros#1353]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

i check
 rostopic echo /clock
but clock is not published . 
I don't know how to solve them
### MAVROS version and platform

Mavros: ?0.18.4?
ROS: ?Kinetic?
Ubuntu: ?16.04?

### Autopilot type and version

[  ] ArduPilot
[  ] PX4

Version: ?3.7.1?

### Node logs

```
copy output of mavros_node. Usually console where you run roslaunch
```

### Diagnostics

```
place here result of:
rostopic echo -n1 /diagnostics
```

### Check ID

```
rosrun mavros checkid
```

**Comment by TSC21** [comment]
This issue is not related with MAVROS. Please bring this to the ROS forum: answers.ros.org, or do a proper search on the matter, as you have a lot of content about it in the forum.
