### ISSUE TITLE
Log reading for terminal and for topic (with custom msg)

### ISSUE THREAD

**Issue by TSC21** [mavlink/mavros#138]
Related to last comment in #41. The idea is use `roscpp` features to read a `.bin`/`.log` file and print the data into the terminal when calling the sevice. Also, add the possibility of writing into a topic as a custom msg (with the different log fields), which data can be read by `rqt_plot` for example.

The other way could be transform the `.log`/`.bin`/`.tlog` into a `.bag` file, that can be played using `rosbag` functionalities. But that will require the understanding how `.bag` files are created and their structure.

**Comment by mhkabir** [comment]
@vooon Do we still need this?

**Comment by vooon** [comment]
I think no, on PX4 we could use FTP, and APM has it's own log download not in mavlink (MissionPlanner).
