### ISSUE TITLE
Coordinate conversion question

### ISSUE THREAD

**Issue by machenxiang** [mavlink/mavros#1408]
![image](https://user-images.githubusercontent.com/18185943/78645451-1f3d1a80-78ea-11ea-9936-4d3bab04f28c.png)
As shown in the picture, we can get the object's XYZ coordinate about the drone.But my question is how conversion this coordinate to mavros's ENU coordinate?

**Comment by TSC21** [comment]
This is a generic question, rather than a question or an issue related with this repo. Please use the [ROS Q&A forum](https://answers.ros.org/questions/) or the [ROS discussion forum](https://discourse.ros.org/) to the same purpose. Closing.
