### ISSUE TITLE
GCU_URL Remote/Public IP Address?

### ISSUE THREAD

**Issue by ed-muthiah** [mavlink/mavros#1410]
### Issue details
Hi All,

Given the current lockdown my partner and I are not able to be co-located in that same house on the same wifi network to work on our Navio2 drone project (note: hardware is at my house). I have setup port forwarding such that my friend is able to SSH into the Navio2 using Putty. While he is able to SSH into to play around with ROS/Ardupilot/MAVROS he is not able to stream data to his Mission Planner becase we are not on the same network.

I am able to get data streaming easily to Mission Planner using a local IP address for gcs like `gcs_url:=udp://:14551@10.0.041:14550`

This is the code I run:
```
rosrun mavros mavros_node \
_fcu_url:=udp://:14650@ \
_gcs_url:=udp://:14551@10.0.041:14550
```
My friend however, is trying to use his global IP address like the kind you get when you google "What is my IP address?" and replacing his code to read
 ```
rosrun mavros mavros_node \
_fcu_url:=udp://:14650@ \
_gcs_url:=udp://:14551@194.xxxxxxxx:14550
```
Could someone please give me a hand as to how to specificy a remote GCS URL? Does this have to do with UDP bind/remote? Thanks!

### MAVROS version and platform
Mavros: v2.0
ROS: Kinetic

### Autopilot type and version
ArduPilot Version: 3.7.1
Navio2

**Comment by vooon** [comment]
You and your friend uses routers to make a WiFi network, that routers uses NAT between your LAN and WAN.
It is possible to direct traffic to any IP, but then you need a way to open a port on friend's WAN side and direct to your friend's laptop IP. But traffic would be unencrypted.

Personally I prefer to setup VPN between networks to make them directly routable from LAN to LAN.
Modern routers + OpenWRT tough enough to run OpenVPN on both sides.
