### ISSUE TITLE
How to install mavros for ros melodic & ubuntu 18.04

### ISSUE THREAD

**Issue by staycoolish** [mavlink/mavros#1418]
Hello,

I cannot install mavros, in Ubuntu 18.04, using the command

**sudo apt-get install ros-melodic-mavros ros-melodic-mavros-extras**

It says

**E: Unable to locate package ros-melodic-mavros
E: Unable to locate package ros-melodic-mavros-extras**

What should I do? 

Thanks,

**Comment by TSC21** [comment]
@staycoolish how did you install ROS Melodic?

**Comment by Jaeyoung-Lim** [comment]
@staycoolish Did you install ROS?

**Comment by staycoolish** [comment]
Actually I followed the steps from http://wiki.ros.org/melodic/Installation/Ubuntu , but I might have removed something by accident, every time I start Ubuntu, a system error (with Report it / Cancel options) is given to me. Do you think uninstalling & reinstalling ROS might work?

**Comment by Jaeyoung-Lim** [comment]
@staycoolish It is not about reinstalling - you are missing the ros repository from the sources list. If you were able to install ROS, you should be able to install mavros

**Comment by staycoolish** [comment]
Thank you, @TSC21 and @Jaeyoung-Lim ! I have applied the installation processes again (which took a very short time), from http://wiki.ros.org/melodic/Installation/Ubuntu , then I was able to apply apt-get install commands, for mavros and some other packages.
