### ISSUE TITLE
Error installing MAVROS

### ISSUE THREAD

**Issue by toma-hawk** [mavlink/mavros#1420]
----

### Issue details

unable to install geographiclib datasets 
Error showing OS not supported ! check GeographicLib page for supported OS and lib versions
im unable to install mavros due to this issue.

### MAVROS version and platform

ROS: Melodic
Ubuntu: 18.04

### Autopilot type and version

[  ] PX4

**Comment by vooon** [comment]
Follow your distro's installation instructions for GeographicLib.
