### ISSUE TITLE
Missing ros-kinetic-mavros-extras on ROS repositories for ARM64

### ISSUE THREAD

**Issue by Davidnet** [mavlink/mavros#1431]
Hi I have a CI that builds a container that is based on kinetic and is on a ARM64 devices and since yesterday is failing due to `ros-kinetic-mavros-extras` is gone from the repos. Any help?

**Comment by Davidnet** [comment]
This is the manfiest:
http://repositories.ros.org/ubuntu/main/dists/xenial/main/binary-arm64/Packages

no mention of kinetic only lunar

**Comment by vooon** [comment]
That is related to #1424.

**Comment by vooon** [comment]
Should be fixed now.
