### ISSUE TITLE
Release to ROS Noetic

### ISSUE THREAD

**Issue by TSC21** [mavlink/mavros#1433]
@vooon we need a release to ROS Noetic. Are there any concerns regarding the Python support? Or is this easy to address?

**Comment by vooon** [comment]
That is blocked by: https://github.com/ros/rosdistro/pull/25016
And probably that is not last absent dependency.

**Comment by TSC21** [comment]
@vooon ros/rosdistro#25016 is solved. What's next?

**Comment by TSC21** [comment]
Ah I saw you did the release already! Never mind, thanks!
