### ISSUE TITLE
How can i move my drone by some inch?

### ISSUE THREAD

**Issue by sagardalai** [mavlink/mavros#1436]
Is there any topic to publish to move the drone by some distance ?
Or any other way to do so.

### MAVROS version and platform
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version
PX4

**Comment by Jaeyoung-Lim** [comment]
@sagardalai You can follow the documentation as in http://dev.px4.io/master/en/ros/mavros_offboard.html

**Comment by amilcarlucas** [comment]
This is a support question, not a bug
