### ISSUE TITLE
Conversion for covariances

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#148]
New mavlink messages have covariance information, but i don't know how convert frames for that.

Related #49, #94.

**Comment by TSC21** [comment]
@tonybaltovski do you have some bandwidth to apply https://github.com/mavlink/mavros/pull/208 also here?

**Comment by mhkabir** [comment]
http://robotics.stackexchange.com/questions/2556/how-to-rotate-covariance

**Comment by TSC21** [comment]
#317 adds the solution to this.
