### ISSUE TITLE
How the data in topic /mavros/local_position/pose(odom) estimated?

### ISSUE THREAD

**Issue by DRAEYE** [mavlink/mavros#1487]
Hello, I am using the mavros to read the data of imu, but I was confused about how the data from /mavros/local_position/pose(odom) is estimated, it seems that it doesn't use the GPS data, is it estimated based on the IMU or something else?

**Comment by Jaeyoung-Lim** [comment]
@DRAEYE Usually it is estimated by the estimator on the autopilot. mavros is a bridge to speak mavlink in ROS and can connect to any autopilot that speaks mavlink. Therefore the answer to your question can differ depending on what autopilot you are talking about

**Comment by DRAEYE** [comment]
OK, thank you very much for your relpy. Maybe I should look into the px4 firmware.
