### ISSUE TITLE
How to subscribe the /mavros/imu/data topic?

### ISSUE THREAD

**Issue by sotomotocross** [mavlink/mavros#1513]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

I want to use the values of the /mavros/imu in order to make some features transformations.

I created a subscriber: imu_sub = rospy.Subscriber("/mavros/imu/data", Imu)
But i can't understand how to use the values i want to subscribe. If i type imu_sub.orientation the editor doesn't recognize these kind of attributes of the imu.
How do i correctly subscribe and constantly update the /mavros/imu/data topic in order to use it for calculations?
Excuse me for this kind of question. I am entry level developer both in ROS and Python.
Maybe for some of you it's very easy but it would help very much if you give me at least one lead.
Thank you very much in advance.
Best,
Sotiris.

### MAVROS version and platform

Mavros: latest
ROS: Melodic
Ubuntu: 18.04

### Autopilot type and version

[X] ArduPilot
[  ] PX4

Version: ArduCopter V4.1.0-dev

**Comment by wrmichaelmak** [comment]
Here have a look at this (definitely recommend going through the ROS tutorials): http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28python%29

This will tell you how to write a subscriber node. The thing you need to do is manipulate the data obtained from the topic via the callback function but in your code you are not doing that
