### ISSUE TITLE
Odometry plugin odom_cb missing estimator_type

### ISSUE THREAD

**Issue by ashwinvk94** [mavlink/mavros#1524]
### Issue details
The Odometry plugin [does not set](https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/odom.cpp#L228) the [estimator_type](https://mavlink.io/en/messages/common.html#MAV_ESTIMATOR_TYPE) in the [Odometry message](https://mavlink.io/en/messages/common.html#ODOMETRY). This prevents the mavlink Odometry message from being published at the PX4 firmware since they [have a check](https://github.com/PX4/PX4-Autopilot/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L1392-L1400) for this field.

### Fix

`msg.estimator_type = utils::enum_value(MAV_ESTIMATOR_TYPE::VISION);` can be added [here](https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/odom.cpp#L229)
`using mavlink::common::MAV_ESTIMATOR_TYPE;` can be added [here](https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/odom.cpp#L29)

Before this fix, there was no messages received in the uOrb topic `vehicle_visual_odometry`.
After this fix, the messages could be echoed through the [mavlink console](https://docs.qgroundcontrol.com/master/en/analyze_view/mavlink_console.html) on qgrouncontrol on this topic. 

### MAVROS version and platform
Mavros: master
ROS: Melodic
Ubuntu: 18.04
### Autopilot type and version
[  ] ArduPilot
[ x] PX4

**Comment by TSC21** [comment]
Please issue a PR. Thank you!

**Comment by ashwinvk94** [comment]
PR issued #1525
