### ISSUE TITLE
ROS2: port mavros scripts

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#1563]
Need to port scripts to python3 and ros2.
Also would use single entry point.

**Comment by akvavit01** [comment]
Hi, is there any progress in this task? I would like to contribute on porting MAVROS to ROS2

**Comment by vooon** [comment]
Hi. I;m currently working on new python client library. Perhaps would get first scripts soon.

See: https://github.com/mavlink/mavros/tree/ros2/mavros/mavros

Also i found out that current param plugin doesn't work well - i have to redo service interface by myself and not rely on rclcpp provided one.

**Comment by akvavit01** [comment]
Can I trouble you to explain about the param plugin? Is the one that's not working the parser?

**Comment by akvavit01** [comment]
By the way, will there be any plan to port the code into c++?
As far as I know, c++ is better in terms of performance

**Comment by vooon** [comment]
No, param is working, just having some bugs which i need to fix...

Mavros node is written in C++, for helper cli's like mavparam/mavwp performance is not an issue, so i do not see any reason to rewrite.

**Comment by akvavit01** [comment]
Okay
Is there anything that can be done in parallel?

**Comment by vooon** [comment]
Actually you could start porting of mavros_extras, that's entirely untouched ground.

**Comment by akvavit01** [comment]
Okay, will do it after my laptop has beem repaired
Best of luck to you, sir

**Comment by vooon** [comment]
Done.
