### ISSUE TITLE
Question: accessing EKF status message/flags

### ISSUE THREAD

**Issue by NicoNorena** [mavlink/mavros#1573]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

Question : is there a way to check the EKF status in PX4? I need to check whenever it resets. 

### MAVROS version and platform

Mavros: 1.7.1
ROS: Melodic
Ubuntu: 18.04

### Autopilot type and version

[  ] ArduPilot
[ x ] PX4

Version: 1.11.3

**Comment by shazib2t** [comment]
@NicoNorena If you are looking to check the status from QgroundControl then you can simply do it by using the Mavlink Console and type ```ekf2 status```. You can also restart the EKF by ```ekf2 stop``` and ```ekf2 start```. 
But now if you are looking to check the status from Mavros then I do not know. I am also looking for the same answer
