### ISSUE TITLE
Is it possible to log raw mavlink packets sent from mavros?

### ISSUE THREAD

**Issue by icefoxen** [mavlink/mavros#1578]
### Issue details

I would like to be able to log the raw mavlink messages received by mavros and sent from mavros, so I can try replaying them into a FCU offline and test changes to it.  Logging the `mavlink/from` topic into a bag gets everything that the FCU sends to mavros, but logging `mavlink/to` produces nothing since mavros doesn't echo messages to it.  There doesn't seem any way to tell mavros to log the actual mavlink messages it outputs, and it would be far easier to do it on the companion computer than in the flight controller.

### MAVROS version and platform

Mavros: ros-melodic-mavros 1.8.0
ROS: Melodic
Ubuntu: 18.04

### Autopilot type and version

[  ] ArduPilot
[  ] PX4
[X] Custom

### Node logs

N/A

### Diagnostics

N/A

### Check ID

```
rosrun mavros checkid
```

No output

**Comment by vooon** [comment]
For Mavros v1 it's not possible to bag messages sent by mavros plugins. So as to log any messages you need to place something in between fcu and mavros node. For example mavlink-router.

For ros2 you would be able to rosbag uas link...

**Comment by icefoxen** [comment]
Welp, I ended up writing my own mavlink<->ROS bridge tools since mavros was too high level for what I needed.
