### ISSUE TITLE
Which topic gives angular rates in body-fixed coordinates (pqr)?

### ISSUE THREAD

**Issue by kadhirumasankar** [mavlink/mavros#1580]
Hi, I just have a quick question: which topic would I subscribe to to get p, q, r, i.e. angular rates in body-fixed coordinates?

**Comment by Jaeyoung-Lim** [comment]
@kadhirumasankar Have you checked the documentation? http://wiki.ros.org/mavros

**Comment by vooon** [comment]
That should provide it:

https://github.com/mavlink/mavros/blob/c13ceed94ce42f6c4ed961885d2b61466b5d1459/mavros/src/plugins/imu.cpp#L112

**Comment by kadhirumasankar** [comment]
This is what I was looking for. Thank you!
