### ISSUE TITLE
/mavros/local_position/pose does not update drone's position

### ISSUE THREAD

**Issue by daothanh2011** [mavlink/mavros#1599]
![image](https://user-images.githubusercontent.com/12525793/127309395-6f6619b2-c7a2-4e2a-af56-a4191a721106.png)
 
When I public the topic /mavros/vision_pose/pose to the PX4, it works successfully, but the topic /mavros/local_position/pose is not acting like vision_pose. And the drone is not moving in QGC (it is only rotating as shown in the figure, the topic /mavros/local_position/pose is not moving as /mavros/vision_pose/pose topic).
Could you pls help me with this problem? Thank you in advance!
here is my configurations:
#px4_config.yaml
fake_gps:

use_mocap: false
mocap_transform: false
use_vision: true

#px4 setup
EKF2_AID_MASK : 24
EKF2_HGT_MODE: vision
MAV_USE_HILGPS: 1

**Comment by Smark2019** [comment]
Hi,

I have been facing this kind of problem. Can I ask how you overcome the problem?

Btw, in my problem; during a 1 meter takeoff mission, my drone is arming but not taking off because local pose data especially z data is not accurate and although my drone is armed, z data is growing.

**Comment by daothanh2011** [comment]
The depth camera makes it a little difficult to get accurate z data , so it is recommended to calibrate the camera and fly under good lighting conditions .
