### ISSUE TITLE
Split out mavconn libaray to use in non ros projects.

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#161]
MAVConn library may be useful in standalone projects where needed mavlink.

**Comment by rxdu** [comment]
Hi, 

I know this is a closed issue but I'm having trouble in compiling libmavconn separately. I just treat the libmavconn folder as a standalone cmake project package and tried to cmake and make. I got no error during the cmake process. But during "make", the compiler complains that:

```
<full-path-on-my-computer>/libmavconn/include/mavconn/mavlink_dialect.h:23:42: fatal error: mavlink/v2.0/common/common.hpp: No such file or directory
 #include <mavlink/v2.0/common/common.hpp>
```

It seems the mavlink header auto generation was not triggered properly. I was wondering how I could fix this error and get this package compiled so that I can use it in a non-ROS project. @vooon 

Thanks,
rxdu

**Comment by vooon** [comment]
@rxdu you also need mavlink headers library in your include path. Generating it is not libmavconn task.
c_library_v2 unfortunately not have C++11 lib, so you should generate headers yourself.

Perhaps you may use https://github.com/mavlink/mavlink-gbp-release (branch `release/kinetic/mavlink`), because it is almost pure cmake file (look master patch dir).

Also recent version of libmavconn use my C++11 generator, which can be found at https://github.com/ArduPilot/pymavlink/pull/27

**Comment by rxdu** [comment]
Thanks for your reply @vooon. Now I can compile libmavconn as a standalone package.

Here is a summary of how I got all missing headers (for anyone else who may find helpful in the future):

1. Copy out libmavconn out from the mavros repository.
2. Try to build the project:
```
$ cd libmavconn
$ mkdir build
$ cd build
$ make
```
You will get the error telling you some header files are missing for mavlink.
3. Then use the C++11 generator from vooon to build the .hpp files from .xml files (you need to get those mavlink msg definitions from the mavlink repository). Copy the entire v2.0 folder generated by mavgen.py to libmavconn/include/mavlink/v2.0.
Try to compile again, you will get errors saying some .h files for mavlink are still missing.
4. Now use branch release/kinetic/mavlink from repo "mavlink-gdb-release" to build the missing .h files. Still regular cmake & make steps. Now you can copy the generated .h files under mavlink-gdb-release/build/include/v2.0 into the C++11 header folder. (I tried to got those .h files with same names from repo c_library_v2, but they seem not fully match the ones required here.)
5. Try to build libmavconn again. Now you should get no error.

I'm not sure if it is the best way to do this. But it at least compiles now. I will do further tests and see if everything works as expected.

**Comment by vooon** [comment]
3-4 may be done much easier:
```
git clone https://github.com/mavlink/mavlink-gbp-release -b release/kinetic/mavlink
mkdir mavlink-gbp-release/build
cd mavlink-gbp-release/build
cmake ..
make

tree include/v2.0
```

Mixing c_library_v2 with gbp is bad. All what you need already done by gpb.
Except you may need fresh message definitions xml (gpb has monthly release).

**Comment by clichtz** [comment]
Not 100% on topic, but definitely related. Is there a way of removing the dependency of libmavconn on the default dialects if I don't want to use them?

**Comment by vooon** [comment]
@clichtz libmavconn depends on all dialects, they all must be compilled beforehand.
You could provide alternative dialect set, just add your definition to message_definitions/v1.0.

**Comment by clichtz** [comment]
My thing is that I don't want to use them and since I am not using libmavconn with ros I have to have all of the dialects in my repo, which is a lot of files. But as far as I could figure, some generated files depend on the dialects, and just wanted to know if there was an alternative.

**Comment by vooon** [comment]
There are no direct dependency on dialect, except generated include and helpers files, empy context and unit tests.
You can ignore test and fix context script.

**Comment by rishabsingh3003** [comment]
Hi @vooon,
I am trying to use mavconn outside ROS, and I have been successful in building it using your comments above.
However when I try to include the library in my cmake file `(find_package(libmavconn REQUIRED))` , I get the following error:
![image](https://user-images.githubusercontent.com/36970042/117540199-95e7a280-b02b-11eb-8697-d170aa3aae11.png)

I must be doing something wrong but I can't figure it out.. do you have any clues?

**Comment by clichtz** [comment]
Did you try doing find_package(mavconn) instead?
