### ISSUE TITLE
New custom mavlink message: how could i subscribe to this new message??

### ISSUE THREAD

**Issue by dottantgal** [mavlink/mavros#166]
Hi all,
I'm using the mavros stack to read and send data to an UAV with a pixhawk at the low level and an INTEL NUC with ros hydro at the high level. 
I've already implemented two new mavlink messages in the common file that will work with a new app installed on the pixhawk firmware.
Is there a way to implement a ros topic that will be subscribed by mavros that will understand the data included and send them to the new app on the pixhawk????
I've tried to understand it reading setpoint_position.cpp that subscribes to /mavros/setpoin/local_position, but it's really hard.
Thank you so much!!!

**Comment by mhkabir** [comment]
I think this is done. Closing. Feel free to reopen if required.

**Comment by pietrop88** [comment]
Hi,
I am having the error:
```
In member function ‘virtual const message_map mavplugin::CaTrajectoryPlugin::get_rx_handlers()’:  error: ‘MAVLINK_MSG_ID_CA_TRAJECTORY’ was not declared in this scope
```
I installed the `deb` package and I can see the folder `ca_trajectory` in `/opt/ros/indigo/include/mavlink/v1.0`.
(My dialect contains `common.xml` message set)

I also think there's no link between my new .cpp files and the mavlink new message definition.

I hope the solution is inside the previous message:
> I answered via email. Note that your dialect don't include common.xml message set (required for most plugins).

Can you share the email content?

**Comment by pietrop88** [comment]
I forgot to add my mavlink dialect to `libmavconn/include/mavconn/mavlink_dialect.h`.
Now it works.

**Comment by alquimist** [comment]
Hi All, 

In advance thanks by any support provided in my doubt. I've been working adding a new custom message to mavlink to get the value of this message on ROS. I already changed the mavlink_dialech.h, the custom_message.xml with the common.xml included and the headers generated with mavgenerate.py. I made the plugin and it is initialized and running on ROS, the result is like the Figure above with the plugin started, however, when I send the message from the GCS it looks ignored by the mavlink protocol. Something is not linked, somebody know what's wrong or any direction to solve the problem ? 

Thanks again...

**Comment by vooon** [comment]
@alquimist try to clean all `catkin clean`, then build again. Did you placed xml into mavlink package?

**Comment by alquimist** [comment]
My apologies by the slow reply. I've run _catkin clean_ and build the packages again with same results. regarding te xml,I've created the _custom_message.xml_ and I've run the mavgenerate.py. The headers were copied to mavlink package.

**Comment by vooon** [comment]
Try to use fresh release (use "source install" manual), then place custom.xml to mavlink then run `catkin build`. cmake from mavlink should find your xml and generate headers.

**Comment by alquimist** [comment]
Thank you very much, let me try ASAP.
