### ISSUE TITLE
ROS MAV msgs format

### ISSUE THREAD

**Issue by vmayoral** [mavlink/mavros#168]
@vooon just wanted to ping you about https://docs.google.com/document/d/1pyEz3p3AQ-6icFiyxe6u6vLAdqU33FQuduWSFT3VHHA/edit#heading=h.6tgmrbkss21h.

**Comment by TSC21** [comment]
Are we to get to any useful point on this topic? @vmayoral @vooon @LorenzMeier LCM or DDS?

**Comment by TSC21** [comment]
Closing this as outdated topic
