### ISSUE TITLE
How to get local position and orientation through IMU by MAVROS

### ISSUE THREAD

**Issue by weiweikong** [mavlink/mavros#169]
Hi there,
     I am currently working on project where we are implementing a Pixhawk Autopilot and ROS for SLAM with Hokuyo UTM-30LX laser and monocular/stereo camera. Now we did not use external IMU. So the setup of our system are

- Ubutnu 14.04 64bit
- ROS indigo
- Pixhawk Autopilot

I have already use MAVROS receive the data from IMU. After running ```rosrun mavros mavros_node```, there are ```/mavros/imu/data``` and ```/mavros/imu/data_raw``` on the topic list. But I am not so familiar with Pixhawk and this research filed, so here are some questions:

- **1.The difference between ```/mavros/imu/data``` and ```/mavros/imu/data_raw```**
Regard to  ```mavros/mavros/src/plugins/imu_pub.cpp``` files,
    - What is the difference between ``` void handle_attitude``` and ```void handle_attitude_quaternion``` ? Which kind of IMU is needed and how could we connected it with Pixhawk?
    - What is the difference between ```void handle_raw_imu``` and ```void handle_scaled_imu```? 

- **2.From Quaternion to Euler Angle ?**
I tried to get the Euler Angle (Roll, Pitch , Yaw) using  ```getRPY ``` through Quaternion data from IMU, but the result seems wrong as I rotated Pixhawk. Is that caused by Gamble Lock when the rotation more than 90 degree? And which function should be adpated to access the Euler Angle.

- **3.Electromagnetic Disturbances?**
Also, I tried to test Pixhawk with PTU as shown below for calbrating Laser and Camera System. The Quaternion data were drifting during the rotation of PTU. Is that the electromagnetic disturbances? How could I access the data directly from IMU without the fusion of compass?
![ptu with pixhawk](https://cloud.githubusercontent.com/assets/2463397/5359174/48e73d54-7ff6-11e4-94ec-592b251280d9.jpg)

- **4.Access the local position and orientation**
As mentioned in the paper *PIXHAWK: A Micro Aerial Vehicle Design for Autonomous Flight using Onboard Computer Vision*, both IMU and vision could calculate the attitude, but how could the system get the local position?   Is that possible to get the local position and orientation directly from Pixhawk only with the provided IMU by calculating the accleration and rotation ? Or the only way to get the local position during the flying is depond on Vision System?

Does anyone have any ideas or suggestions? 

Thanks.

Best,
Weiwei

**Comment by mhkabir** [comment]
@weiweikong Any updates on this?

**Comment by mhkabir** [comment]
Please use the PX4users mailing list or Gitter if you have further questions : https://gitter.im/mavlink/mavros
https://gitter.im/PX4/Firmware

**Comment by zer1988** [comment]
Hi vooon can you guide me how I can convert data of orientation of mavros/imu/data from quaternion to  spatial rotaion?

**Comment by vooon** [comment]
Use tf python lib. Or use Eigen.
