### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by PeymanAmirii** [mavlink/mavros#1691]
Hi,
Does MAVROS officially support and is it able to work with Python 3 correctly or we have to use just Python 2 to work safely with MAVROS?
Thanks

**Comment by vooon** [comment]
That depends on what version do you use. Version 1.12 on Noetic should be mostly fine, but there are some fixes in current master.
Anyway if you're going to use ROS API, then it is enough to use ROS Noetic. Main node is written in C++, so py3 mostly comes to rospy support.

**Comment by PeymanAmirii** [comment]
Thanks for your quick reply. We want to use MAVROS APIs for PX4. We know that ROS Noetic is ROS1, but it is recommended to use ROS2 for PX4. If we use ROS2, will MAVROS work with Python 3 (3.7 or 3.8) correctly?
Many Thanks

**Comment by vooon** [comment]
ROS1 vs ROS2 is completely different story. ROS2 has huge overhaul of all things. MAVROS v2 (version for ROS2) is on it's alpha stage and still having some critical bugs. I cannot recommend to use it now.

PX4 has their own bridge node to ROS2, which gives access to uORB, an internal pubsub system of the firmware.
That's counterpart to mavros, which talks to mavlink app, which then interacts with uORB.

**Comment by PeymanAmirii** [comment]
Thanks a bunch. So we can use ROS2 for PX4 without using MAVROS?

**Comment by vooon** [comment]
Yes, you can.
