### ISSUE TITLE
ROS2: FTP segfault on list call

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#1695]
### Issue details

Node segfaults after any call to `/mavros/ftp/list`.

### MAVROS version and platform

Mavros: 2.0.5 (master)
ROS: Galactic
Ubuntu: 20.04

### Autopilot type and version

[x] ArduPilot
[ ] PX4

Version: 4.0.7

**Comment by lopsided98** [comment]
This was caused by https://github.com/mavlink/mavros/pull/1603, which converted `PayloadHeader::data` from a (non-standard in C++) flexible array to a pointer.
