### ISSUE TITLE
getting AUTOPILOT_VERSION via  topic/service

### ISSUE THREAD

**Issue by DoneMan** [mavlink/mavros#1698]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

i would like to retrive the AUTOPILOT_SYSTEM via  mavros service or topic.
 i know i can use /mavros/cmd/command cmd 520 to get capabilities and mavros will print out the AUTOPILOT_VERSION. but how can i capture this?

### MAVROS version and platform

Mavros: 1.12.2
ROS: melodic
Ubuntu: 18.04

### Autopilot type and version

[x ] ArduPilot
[  ] PX4

Version: 4.1.3

**Comment by vooon** [comment]
Use `~vehicle_info_get` service.

**Comment by DoneMan** [comment]
Thank you very much!

בתאריך יום ב׳, 31 בינו׳ 2022, 13:57, מאת Vladimir Ermakov ‏<
***@***.***>:
