### ISSUE TITLE
[ROS2][Question] Which service to use to set params from C++ code

### ISSUE THREAD

**Issue by Vicidel** [mavlink/mavros#1737]
### Issue details

Hello all

I need to set parameters using MAVROS2. I see that there are two services:
- `/mavros/param/set` of type `mavros_msgs::srv::ParamSetV2`
- `/mavros/param/set_parameters` of type `rcl_interfaces::srv::SetParameters`

In the param plugin there is a line [here](https://github.com/mavlink/mavros/blob/ros2/mavros/src/plugins/param.cpp#L44) saying that the service `set_parameters` is not exposed to user code. And in the `mavros_msgs` definition of `ParamSetV2` there is a note that it's only if the ROS2 param API is not sufficient [here](https://github.com/mavlink/mavros/blob/ros2/mavros_msgs/srv/ParamSetV2.srv#L6).

From my interpretation I should not use any of those two. Which of these two should I believe?

### MAVROS version and platform

Mavros: 2.1.1
ROS: ROS2 Galactic
Ubuntu: 20.04

### Autopilot type and version

[  ] ArduPilot
[x] PX4

**Comment by vooon** [comment]
You should use standard parameter interface. `~/set` have quite specific use cases: to bypass parameter exclude check (bu name) or to send unknown (yet) parameter.

**Comment by Vicidel** [comment]
Okay that makes sense, thanks for the quick answer!

**Comment by esharet** [comment]
> You should use standard parameter interface. `~/set` have quite specific use cases: to bypass parameter exclude check (bu name) or to send unknown (yet) parameter.

Can you please explain? I'm interested in setting and getting parameters from pixhawk.
The service /mavros/param/set work fine for setting, is it the right way? and how can I get a specific parameter?
Thanks

**Comment by vooon** [comment]
ROS2 has standard interface to parameters. Use them.
https://github.com/mavlink/mavros/blob/686bd833e7d6ea5542977178872762dfbec5ed89/mavros/src/plugins/param.cpp#L43-L55
