### ISSUE TITLE
typo in function name, subscribe_raw_salellites

### ISSUE THREAD

**Issue by antonyramsy** [mavlink/mavros#1740]
### Issue details

in [mavros.global_position.py](https://github.com/mavlink/mavros/blob/ros2/mavros/mavros/global_position.py)
there's a typo. subscribe_raw_salellites should be subscribe_raw_satellites

### MAVROS version and platform

Mavros: 2.1
ROS: foxy
Ubuntu: 20.04

### Autopilot type and version

[ x ] ArduPilot
[  ] PX4

Version: 4.2.1

**Comment by vooon** [comment]
Please make a PR with a fix.
