### ISSUE TITLE
no data on /mavros/local_position/odom topic

### ISSUE THREAD

**Issue by Captain299792458** [mavlink/mavros#1764]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

hello y'all., I am running ROS with sitl and launching apm.launch script with sitl fcu_url as udp id, its working fine and I am getting the results and data on `mavros/local_position/odom` topic. But as soon as I change the fcu_url as `/dev/ttyACM0` for hardware testing, I am getting no data over that topic ? what might issue here? I appreciate the help or suggestion. thanks!

### MAVROS version and platform

Mavros: ?0.18.4?
ROS: Melodic
Ubuntu: 18

### Autopilot type and version

[  ] ArduPilot: 4.1.5
[  ] PX4

Version: ?3.7.1?

### Node logs

```
copy output of mavros_node. Usually console where you run roslaunch
```

### Diagnostics

```
place here result of:
rostopic echo -n1 /diagnostics
```

### Check ID

```
rosrun mavros checkid
```

**Comment by vooon** [comment]
Maybe you need  to setup the port? What `checkid` shows?

**Comment by Captain299792458** [comment]
> Maybe you need to setup the port? What `checkid` shows?

I have run it. target system id is not set used default id value 1

Also, 
I have performed set_stream_rate and /mavros/imu/data is streaming but /mavros/local_position/pose is not streaming any data. I have autopilot indoors and GPS fix is 0. Should i wait for GPS fix to be 3D to get data from topic mavros/local_position/pose

**Comment by vooon** [comment]
Yes, i suppose fw will send position only when it'll get fix. That could be changed by fw setup + vision pose source.

**Comment by Captain299792458** [comment]
setting stream rate solves the problem. thanks for your replies.
