### ISSUE TITLE
Increase reading data rate

### ISSUE THREAD

**Issue by fabiorubino** [mavlink/mavros#178]
Hi!
I need to increase the rate of the reading data. I tried to use this command "rosservice call /mavros/set_stream_rate 0 100 1" but no change. I used a Pixhawk connected through USB cable. The pixhawk firmware was uploaded through QGroundControl. I didn't connect the device to QGC during the reading. 
What can I do?

**Comment by tonybaltovski** [comment]
Can this be done to increase the value of the raw IMU?

**Comment by mhkabir** [comment]
Closing this. 
The summary : You can increase reading rate by modifying your mavlink stream command (in rc.usb, rcS or extras.txt ) like this, to stream attitude on USB port at 200Hz 
```
mavlink stream -d /dev/ttyACM0 -s ATTITUDE -r 200
```
You should ideally connect to mavros like this : https://pixhawk.org/dev/companion_link
It will automatically start-up typical onboard streams.

**Comment by dani-carbonell** [comment]
"rosservice call /mavros/set_stream_rate 0 100 1" 

This command works whit the APM firmware, shouldn't work with the PX4 also?

**Comment by LorenzMeier** [comment]
We have deprecated the streams API since it's not flexible enough. I will put up docs and an example using QGC how to configure message rates.

**Comment by dani-carbonell** [comment]
Should we document this in the ROS wiki also to avoid confusion?

Thanks Lorenz

2015-02-13 10:38 GMT+01:00 Lorenz Meier <notifications@github.com>:

**Comment by y22ma** [comment]
@LorenzMeier just wondering if the docs is up yet for configuring message rate through QGC?
