### ISSUE TITLE
Current state of ROS2 support

### ISSUE THREAD

**Issue by eMrazSVK** [mavlink/mavros#1785]
### Issue details

Hello, as it is said in main readme, currently ROS2 mavros version (2.0.0) is only in alpha release. I see for example that launch files are not ported yet. I plan to contribute to Mavros regarding ROS2 support. Could anyone please provide me a list of what is currently missing, what does not work yet in ROS2 in comparison with ROS1 version? 

Thank you, any responses are appreciated. 

### MAVROS version and platform

Mavros: 2.0.0
ROS: Foxy
Ubuntu: 20.04

### Autopilot type and version

[ x ] ArduPilot
[  ] PX4

Version: 4.2 SITL

**Comment by vooon** [comment]
Please look here: https://github.com/mavlink/mavros/projects/1

But most of plugins was ported, we're lacking on testing and fixing bugs.

For example i had some strange segfaults if UAS loaded by external runner (not by mavros_node), that functionality needed to test multidrone scheme, where you have one Router and several UASes.

**Comment by eMrazSVK** [comment]
Thank you.
