### ISSUE TITLE
is there a way to listen NAMED_VALUE_FLOAT through mavros?

### ISSUE THREAD

**Issue by shubham-shahh** [mavlink/mavros#1830]
### Issue details

is there a way to listen to [NAMED_FLOAT](https://mavlink.io/en/messages/common.html#NAMED_VALUE_FLOAT) through mavros?

### MAVROS version and platform

Mavros: 1.13.0 (can move to the latest version available for ROS1)
ROS: Melodic
Ubuntu: 18.04

### Autopilot type and version

[ X ] ArduPilot
[  ] PX4

Version: 4.1.5

**Comment by vooon** [comment]
https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/debug_value.cpp#L221

**Comment by shubham-shahh** [comment]
> https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/debug_value.cpp#L221

Hi,
Thanks for the info, how can I enable this?

**Comment by shubham-shahh** [comment]
> > https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/debug_value.cpp#L221
> 
> Hi, Thanks for the info, how can I enable this?

I was able to enable it from the plugin list, thanks again
