### ISSUE TITLE
Communication between 2 drones using MAVROS

### ISSUE THREAD

**Issue by AshwinDisa** [mavlink/mavros#1850]
Hello,

I'm using 2 Rpis with ROS1 installed, connected to their respective FCUs using apm.launch. I want to subscribe to the pose of the first drone from the second drone using this configuration. As they are running their own masters, is this communication feasible? Any alternative methods are also welcome. 

Thanks

**Comment by vooon** [comment]
Oh, as i remember communication between different masters is harsh topic.
I remember that there was some demo where several PR2's coordinate theirs movement but not in detail.
That was also one of the reasons for ROS2.

**Comment by AshwinDisa** [comment]
http://wiki.ros.org/swarm_ros_bridge solved my problem.
