### ISSUE TITLE
Can't locate mavrod_node

### ISSUE THREAD

**Issue by dpnebert** [mavlink/mavros#191]
I am able to install and use ROS (http://wiki.ros.org/indigo/Installation/Ubuntu)

Then I install MAVROS (https://github.com/mavlink/mavros) using the console command, 'sudo git clone https://github.com/mavlink/mavros.git'

I add the directory I installed mavros to the environment variable ROS_PACKAGE_PATH.

I am able to build the package using, 'rosmake mavros' which echos:

============================================================
dan@dan-HP-ProBook-6470b:~/indigo_workspace/mavros/mavros$ rosmake mavros
[ rosmake ] rosmake starting...                                                                                                                
[ rosmake ] Packages requested are: ['mavros']                                                                                                 
[ rosmake ] Logging to directory /home/dan/.ros/rosmake/rosmake_output-20150123-141534                                                         
[ rosmake ] Expanded args ['mavros'] to:
['mavros']                                                                                            
[rosmake-0] Starting >>> catkin [ make ]                                                                                                       
[rosmake-0] Finished <<< catkin ROS_NOBUILD in package catkin
 No Makefile in package catkin                                                   
[rosmake-0] Starting >>> genmsg [ make ]                                                                                                       
[rosmake-1] Starting >>> cpp_common [ make ]                                                                                                   
[rosmake-2] Starting >>> cmake_modules [ make ]                                                                                                
[rosmake-3] Starting >>> libmavconn [ make ]                                                                                                   
[rosmake-2] Finished <<< cmake_modules ROS_NOBUILD in package cmake_modules
 No Makefile in package cmake_modules                              
[rosmake-0] Finished <<< genmsg ROS_NOBUILD in package genmsg
 No Makefile in package genmsg                                                   
[rosmake-0] Starting >>> genlisp [ make ]                                                                                                      
[rosmake-2] Starting >>> genpy [ make ]                                                                                                        
[rosmake-1] Finished <<< cpp_common ROS_NOBUILD in package cpp_common
 No Makefile in package cpp_common                                       
[rosmake-1] Starting >>> gencpp [ make ]                                                                                                       
[rosmake-0] Finished <<< genlisp ROS_NOBUILD in package genlisp
 No Makefile in package genlisp                                                
[rosmake-0] Starting >>> rostime [ make ]                                                                                                      
[rosmake-0] Finished <<< rostime ROS_NOBUILD in package rostime
 No Makefile in package rostime                                                
[rosmake-0] Starting >>> roscpp_traits [ make ]                                                                                                
[rosmake-3] Finished <<< libmavconn ROS_NOBUILD in package libmavconn
 No Makefile in package libmavconn                                       
[rosmake-3] Starting >>> rospack [ make ]                                                                                                      
[rosmake-2] Finished <<< genpy ROS_NOBUILD in package genpy [ roscpp_traits: 0.0 sec ] [ rospack: 0.0 sec ]           [ 4 Active 7/58 Complete ]
 No Makefile in package genpy                                                      
[rosmake-1] Finished <<< gencpp ROS_NOBUILD in package gencpp
 No Makefile in package gencpp                                                   
[rosmake-1] Starting >>> roslang [ make ]                                                                                                      
[rosmake-0] Finished <<< roscpp_traits ROS_NOBUILD in package roscpp_traits
 No Makefile in package roscpp_traits                              
[rosmake-0] Starting >>> roscpp_serialization [ make ]                                                                                         
[rosmake-2] Starting >>> message_generation [ make ]                                                                                           
[rosmake-3] Finished <<< rospack ROS_NOBUILD in package rospack
 No Makefile in package rospack                                                
[rosmake-3] Starting >>> roslib [ make ]                                                                                                       
[rosmake-1] Finished <<< roslang ROS_NOBUILD in package roslang
 No Makefile in package roslang                                                
[rosmake-1] Starting >>> xmlrpcpp [ make ]                                                                                                     
[rosmake-0] Finished <<< roscpp_serialization ROS_NOBUILD in package roscpp_serialization
 No Makefile in package roscpp_serialization         
[rosmake-0] Starting >>> message_runtime [ make ]                                                                                              
[rosmake-3] Finished <<< roslib ROS_NOBUILD in package roslib
 No Makefile in package roslib                                                   
[rosmake-3] Starting >>> rosunit [ make ]                                                                                                      
[rosmake-1] Finished <<< xmlrpcpp ROS_NOBUILD in package xmlrpcpp
 No Makefile in package xmlrpcpp                                             
[rosmake-1] Starting >>> class_loader [ make ]                                                                                                 
[rosmake-2] Finished <<< message_generation ROS_NOBUILD in package message_generation
 No Makefile in package message_generation               
[rosmake-2] Starting >>> rosgraph [ make ]                                                                                                     
[rosmake-3] Finished <<< rosunit ROS_NOBUILD in package rosunit
 No Makefile in package rosunit                                                
[rosmake-3] Starting >>> rosclean [ make ]                                                                                                     
[rosmake-0] Finished <<< message_runtime ROS_NOBUILD in package message_runtime
 No Makefile in package message_runtime                        
[rosmake-0] Starting >>> std_msgs [ make ]                                                                                                     
[rosmake-1] Finished <<< class_loader ROS_NOBUILD in package class_loader
 No Makefile in package class_loader                                 
[rosmake-1] Starting >>> rosbuild [ make ]                                                                                                     
[rosmake-2] Finished <<< rosgraph ROS_NOBUILD in package rosgraph
 No Makefile in package rosgraph                                             
[rosmake-2] Starting >>> std_srvs [ make ]                                                                                                     
[rosmake-3] Finished <<< rosclean ROS_NOBUILD in package rosclean
 No Makefile in package rosclean                                             
[rosmake-0] Finished <<< std_msgs ROS_NOBUILD in package std_msgs
 No Makefile in package std_msgs                                             
[rosmake-3] Starting >>> rosparam [ make ]                                                                                                     
[rosmake-0] Starting >>> rosgraph_msgs [ make ]                                                                                                
[rosmake-1] Finished <<< rosbuild ROS_NOBUILD in package rosbuild
 No Makefile in package rosbuild                                             
[rosmake-2] Finished <<< std_srvs ROS_NOBUILD in package std_srvs
 No Makefile in package std_srvs                                             
[rosmake-3] Finished <<< rosparam ROS_NOBUILD in package rosparam
 No Makefile in package rosparam                                             
[rosmake-1] Starting >>> rosconsole [ make ]                                                                                                   
[rosmake-0] Finished <<< rosgraph_msgs ROS_NOBUILD in package rosgraph_msgs
 No Makefile in package rosgraph_msgs                              
[rosmake-2] Starting >>> geometry_msgs [ make ]                                                                                                
[rosmake-3] Starting >>> rosmaster [ make ]                                                                                                    
[rosmake-0] Starting >>> diagnostic_msgs [ make ]                                                                                              
[rosmake-3] Finished <<< rosmaster ROS_NOBUILD in package rosmaster
 No Makefile in package rosmaster                                          
[rosmake-1] Finished <<< rosconsole ROS_NOBUILD in package rosconsole
 No Makefile in package rosconsole                                       
[rosmake-3] Starting >>> angles [ make ]                                                                                                       
[rosmake-1] Starting >>> roscpp [ make ]                                                                                                       
[rosmake-0] Finished <<< diagnostic_msgs ROS_NOBUILD in package diagnostic_msgs
 No Makefile in package diagnostic_msgs                        
[rosmake-0] Starting >>> pluginlib [ make ]                                                                                                    
[rosmake-2] Finished <<< geometry_msgs ROS_NOBUILD in package geometry_msgs
 No Makefile in package geometry_msgs                              
[rosmake-2] Starting >>> rosconsole_bridge [ make ]                                                                                            
[rosmake-3] Finished <<< angles ROS_NOBUILD in package angles[ pluginlib: 0.0 sec ] [ rosconsole_bridge: 0.0 sec ]   [ 4 Active 30/58 Complete ]
 No Makefile in package angles                                                   
[rosmake-3] Starting >>> sensor_msgs [ make ]                                                                                                  
[rosmake-2] Finished <<< rosconsole_bridge ROS_NOBUILD in package rosconsole_bridge
 No Makefile in package rosconsole_bridge                  
[rosmake-2] Starting >>> actionlib_msgs [ make ]                                                                                               
[rosmake-1] Finished <<< roscpp ROS_NOBUILD in package roscpp
 No Makefile in package roscpp                                                   
[rosmake-0] Finished <<< pluginlib ROS_NOBUILD in package pluginlib
 No Makefile in package pluginlib                                          
[rosmake-1] Starting >>> rosout [ make ]                                                                                                       
[rosmake-0] Starting >>> rospy [ make ]                                                                                                        
[rosmake-3] Finished <<< sensor_msgs ROS_NOBUILD in package sensor_msgs
 No Makefile in package sensor_msgs                                    
[rosmake-3] Starting >>> roslz4 [ make ]                                                                                                       
[rosmake-2] Finished <<< actionlib_msgs ROS_NOBUILD in package actionlib_msgs
 No Makefile in package actionlib_msgs                           
[rosmake-2] Starting >>> tf2_msgs [ make ]                                                                                                     
[rosmake-1] Finished <<< rosout ROS_NOBUILD in package rosout
 No Makefile in package rosout                                                   
[rosmake-0] Finished <<< rospy ROS_NOBUILD in package rospy
 No Makefile in package rospy                                                      
[rosmake-1] Starting >>> roslaunch [ make ]                                                                                                    
[rosmake-3] Finished <<< roslz4 ROS_NOBUILD in package roslz4
 No Makefile in package roslz4                                                   
[rosmake-3] Starting >>> rosbag_storage [ make ]                                                                                               
[rosmake-0] Starting >>> mavros [ make ]                                                                                                       
[rosmake-0] Finished <<< mavros ROS_NOBUILD in package mavros
 No Makefile in package mavros                                                   
[rosmake-2] Finished <<< tf2_msgs ROS_NOBUILD in package tf2_msgs
 No Makefile in package tf2_msgs                                             
[rosmake-2] Starting >>> tf2 [ make ]                                                                                                          
[rosmake-1] Finished <<< roslaunch ROS_NOBUILD in package roslaunch
 No Makefile in package roslaunch                                          
[rosmake-1] Starting >>> rostest [ make ]                                                                                                      
[rosmake-3] Finished <<< rosbag_storage ROS_NOBUILD in package rosbag_storage
 No Makefile in package rosbag_storage                           
[rosmake-2] Finished <<< tf2 ROS_NOBUILD in package tf2
 No Makefile in package tf2                                                            
[rosmake-2] Starting >>> tf2_py [ make ]                                                                                                       
[rosmake-1] Finished <<< rostest ROS_NOBUILD in package rostest
 No Makefile in package rostest                                                
[rosmake-2] Finished <<< tf2_py ROS_NOBUILD in package tf2_py
 No Makefile in package tf2_py                                                   
[rosmake-1] Starting >>> diagnostic_updater [ make ]                                                                                           
[rosmake-2] Starting >>> message_filters [ make ]                                                                                              
[rosmake-0] Starting >>> topic_tools [ make ]                                                                                                  
[rosmake-1] Finished <<< diagnostic_updater ROS_NOBUILD in package diagnostic_updater
 No Makefile in package diagnostic_updater               
[rosmake-2] Finished <<< message_filters ROS_NOBUILD in package message_filters
 No Makefile in package message_filters                        
[rosmake-0] Finished <<< topic_tools ROS_NOBUILD in package topic_tools
 No Makefile in package topic_tools                                    
[rosmake-0] Starting >>> rosbag [ make ]                                                                                                       
[rosmake-0] Finished <<< rosbag ROS_NOBUILD in package rosbag
 No Makefile in package rosbag                                                   
[rosmake-0] Starting >>> rostopic [ make ]                                                                                                     
[rosmake-3] Starting >>> rosmsg [ make ]                                                                                                       
[rosmake-0] Finished <<< rostopic ROS_NOBUILD in package rostopic
 No Makefile in package rostopic                                             
[rosmake-0] Starting >>> rosnode [ make ]                                                                                                      
[rosmake-3] Finished <<< rosmsg ROS_NOBUILD in package rosmsg
 No Makefile in package rosmsg                                                   
[rosmake-0] Finished <<< rosnode ROS_NOBUILD in package rosnode
 No Makefile in package rosnode                                                
[rosmake-3] Starting >>> rosservice [ make ]                                                                                                   
[rosmake-0] Starting >>> actionlib [ make ]                                                                                                    
[rosmake-3] Finished <<< rosservice ROS_NOBUILD in package rosservice
 No Makefile in package rosservice                                       
[rosmake-3] Starting >>> roswtf [ make ]                                                                                                       
[rosmake-0] Finished <<< actionlib ROS_NOBUILD in package actionlib
 No Makefile in package actionlib                                          
[rosmake-0] Starting >>> tf2_ros [ make ]                                                                                                      
[rosmake-0] Finished <<< tf2_ros ROS_NOBUILD in package tf2_ros                                                      [ 2 Active 55/58 Complete ]
 No Makefile in package tf2_ros                                                
[rosmake-3] Finished <<< roswtf ROS_NOBUILD in package roswtf
 No Makefile in package roswtf                                                   
[rosmake-0] Starting >>> tf [ make ]                                                                                                           
[rosmake-0] Finished <<< tf ROS_NOBUILD in package tf
 No Makefile in package tf                                                               
[ rosmake ] Results:                                                                                                                           
[ rosmake ] Built 58 packages with 0 failures.                                                                                                 
[ rosmake ] Summary output to directory                                                                                                        
[ rosmake ] /home/dan/.ros/rosmake/rosmake_output-20150123-141534

==========================================================

After I build the package, I attempt to run the launch file, px4.launch, using the command: roslaunch mavros px4.launch, which echos:

===========================================================
dan@dan-HP-ProBook-6470b:~/indigo_workspace/mavros/mavros$ roslaunch mavros px4.launch
... logging to /home/dan/.ros/log/09903df0-a322-11e4-a29e-7446a03c3af8/roslaunch-dan-HP-ProBook-6470b-5079.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://dan-HP-ProBook-6470b:57951/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/conn_heartbeat: 5.0
 * /mavros/conn_system_time: 1.0
 * /mavros/conn_timeout: 10.0
 * /mavros/conn_timesync: 0.1
 * /mavros/fcu_url: /dev/ttyACM0:57600
 * /mavros/gcs_url:
 * /mavros/gps/frame_id: gps
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: fcu
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/mission/pull_after_gcs: True
 * /mavros/plugin_blacklist: ['3dr_radio']
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 50
 * /mavros/target_system_id: 1
 * /rosdistro: indigo
 * /rosversion: 1.11.10

NODES
  /
    mavros (mavros/mavros_node)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
ERROR: cannot launch node of type [mavros/mavros_node]: can't locate node [mavros_node] in package [mavros]
No processes to monitor
shutting down processing monitor...
... shutting down processing monitor complete
=============================================================
Note: I am not connected to the drone in anyway.  I am simply trying to get far enough through this that I can see the motors spin on the drone.  At what point should I try to get the FCU and GCS address entered in?  Or is that my problem?
For some reason, I can't figure out how to create a MAVROS_NODE object.  If anyone has any suggestion, I'd appreciate it.

**Comment by vooon** [comment]
Did you read this: [README Installation](https://github.com/mavlink/mavros/blob/master/mavros/README.md#installation)?
Mavros is catkin project, not rosbuild.

**Comment by dpnebert** [comment]
I did not read that far, I guess.  I see that now with the link you gave.  Thanks for the help, still new to all of this.
