### ISSUE TITLE
`mavros/cmd/arming` service is unable to specify the "force" parameter

### ISSUE THREAD

**Issue by NumbNutN** [mavlink/mavros#1937]
### Issue details

Hi there. I would like to automate a drone with Ardupilot firmware with `mavros`. 
I notice there's a `Force` parameter could be specified in command `MAV_CMD_COMPONENT_ARM_DISARM(400)`
[MAVLink - message](https://mavlink.io/en/messages/common.html)

In some cases Ardupilot will fail safety checks, for example, the main program loop cannot run at the required frequency in SITL environment, in which case we need to include the Force parameter in the mavlink packet to override it.

However `mavros/cmd/arming` service with message type `CommandBool` was unable to specify a `force` parameter so I have to use low level mavlink tool to pack a packet.

Is it possible to add a force parameter in service `mavros/cmd/arming` Request type?

### MAVROS version and platform

Mavros: 1.15.0
ROS: Noetic
Ubuntu: 20.04 LTS

### Autopilot type and version

[ Tick ] ArduPilot
[  ] PX4

**Comment by vooon** [comment]
I'd rather not to do so. Instead you can use `~/cmd/long`.

**Comment by NumbNutN** [comment]
Thanks. That's certainly what I'm looking for. @vooon
