### ISSUE TITLE
Pixhawk, PX4FLOW , Odroid, mavros, autonomous flight

### ISSUE THREAD

**Issue by fabiorubino** [mavlink/mavros#196]
Hi all,
I want to fly autonomously with Pixhawk, PX4FLOW, and Odroid. I can read data from Pixhawk and PX4FLOW separately (with two different launchers) inside Odroid  in the same time  through mavros. How can I send commands to Pixhawk for flying through mavros?

Bests
Fabio

**Comment by vooon** [comment]
Please better ask at px4users google group, and not spam to project bug tracker.
