### ISSUE TITLE
Post-Jazzy and Pre-Jazzy builds have diverged

### ISSUE THREAD

**Issue by evan-palmer** [mavlink/mavros#1989]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

I was reviewing the CI for #1988, and saw that the Jazzy/Rolling builds succeed, but the addition causes build failures in releases prior to Jazzy (e.g., [humble](https://github.com/mavlink/mavros/actions/runs/10863743005/job/30148243241)).

**Comment by evan-palmer** [comment]
It seems like the `ros2` branch may need to split to account for the different dependencies. What do you think @vooon? Do you have ideas for an alternative solution?

**Comment by vooon** [comment]
Probably better to add conditionals into CMakeLists.txt. Simply check version of rclcpp and then add or skip libyaml.

**Comment by evan-palmer** [comment]
Good idea. I'll submit a PR with that fix.
