### ISSUE TITLE
Upgrade MAVLink in dependencies.rosinstall

### ISSUE THREAD

**Issue by evan-palmer** [mavlink/mavros#1995]
### Issue details

The version of MAVLink targeted in the `dependencies.rosinstall` file (i.e., `release/foxy/mavlink`) does not include the latest changes to pymavlink needed to support Python 3.12 (available in [this](https://github.com/ArduPilot/pymavlink/blob/533161c47995ba47f5548636eed37a47e91072c0/generator/mavgen.py) commit from Tridge). These changes are needed to help address #1958.

**Comment by evan-palmer** [comment]
@vooon is there anything I can do to help with this? I took a look at the [mavlink-gpb-release](https://github.com/mavlink/mavlink-gbp-release) repo, and it looks like the bloom build needs to be manually triggered?

**Comment by vooon** [comment]
https://github.com/mavlink/mavlink-gbp-release/blob/release/noetic/mavlink/pymavlink/generator/mavgen.py

So 2024.6.6 should have it.

**Comment by vooon** [comment]
NOTE: this is the correct one for ROS2: https://github.com/ros2-gbp/mavlink-gbp-release

Foxy is EOLed, and no release accepted to EOLed distros.

**Comment by evan-palmer** [comment]
Oh perfect! I hadn't seen that repo. I just did some testing, and things work as expected with Jazzy. Thanks!
