### ISSUE TITLE
Edit rc.usb with mavftp

### ISSUE THREAD

**Issue by dani-carbonell** [mavlink/mavros#219]
Hi, 
I want to publish trough "/dev/ttyACM0" HIGHRES_IMU messages at 100 Hz since default config is 1Hz. I am able to set it with "mavlink stream" command but I want to make it permanent. 

I've tried to edit the rc.usb file with the mavftp but I am getting errors, I am afraid is still not fully implemented.

Is there a way to modify/append/upload files without flashing the Pixhawk?

**Comment by vooon** [comment]
FTP fully implemented, but you tried modify ROMFS entry (read only).
You can edit `etc/extras.txt` on SD, and disable px4 startup quirk.

**Comment by vooon** [comment]
https://pixhawk.org/dev/system_startup

**Comment by vooon** [comment]
Note: be careful with mode options, it may disable FTP :)

**Comment by dani-carbonell** [comment]
Thanks vooon :+1: 
I will try once I solve rencent problems with the USB.

**Comment by vooon** [comment]
Any update?

**Comment by mstuettgen** [comment]
@dani-carbonell, i suggest using TELEM2 for communication, as USB is quite unrelieable und unstable. 
 here is my extras.txt:

usleep 100000
mavlink start -m custom -d /dev/ttyS2 -b 921600 -x
usleep 100000
mavlink stream -d /dev/ttyS2 -s HEARTBEAT -r 5
usleep 100000
mavlink stream -d /dev/ttyS2 -s STATUSTEXT -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s SYS_STATUS -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s PARAM_VALUE -r 200
usleep 100000
mavlink stream -d /dev/ttyS2 -s HIGHRES_IMU -r 50
usleep 100000
mavlink stream -d /dev/ttyS2 -s ATTITUDE -r 50
usleep 100000
mavlink stream -d /dev/ttyS2 -s ATTITUDE_QUATERNION -r 50
usleep 100000
mavlink stream -d /dev/ttyS2 -s VFR_HUD -r 10
usleep 100000
mavlink stream -d /dev/ttyS2 -s GPS_RAW_INT -r 5
usleep 100000
mavlink stream -d /dev/ttyS2 -s GLOBAL_POSITION_INT -r 5
usleep 100000
mavlink stream -d /dev/ttyS2 -s LOCAL_POSITION_NED -r 5

note that /dev/ttyS2 is the internal port for TELEM2

**Comment by mstuettgen** [comment]
-x will activate FTP

**Comment by mhkabir** [comment]
Just use this : https://pixhawk.org/dev/companion_link

**Comment by vooon** [comment]
I think we may close.
