### ISSUE TITLE
Override RC inputs topic

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#22]

**Comment by pmukherj** [comment]
Quick question for @vooon on this! Do you know if there is a way to override just a few channels, while leaving the other channels under RC or autonomous control? 
I have a gimbal I'd like to control from mavros (connected to the pixhawk PWM out), but don't really want to override the other RC outputs. 
If the current plugin doesn't support single channel override, I'm thinking mavlink does and this plugin can be extended, I can look into that!

**Comment by tonybaltovski** [comment]
@pmukherj If you publish 0 for the channel. it will give control back to the RC. Similarly, -1 for a channel means no change should be made to that channel. In order to send the -1, you need to send the maximum of the int16_t which is 65535 (2^2-1).

**Comment by pmukherj** [comment]
Amazing! That's perfect.

**Comment by tonybaltovski** [comment]
Are you using the RC override with the pixhawk?

**Comment by mhkabir** [comment]
This won't work. We don't handle RC override in PX4 stack.

**Comment by pmukherj** [comment]
Yea, I noticed that conversation in the joystick plugin ticket. Boo!
For now, I may just hack my companion computer(Tk1 + odroid) to output the PWM into the gimbal. I have to stick with the px4 stack for testing the setpoint control.
Eventually though centralized method to control it all through the pixhawk will be awesome.

**Comment by mhkabir** [comment]
We can do it via the FMU auxiliary pins. I'm already working on getting the pins started up by default, as they are currently totally "dead"
Simple to add a handler and passthrough.

**Comment by LorenzMeier** [comment]
They are already enabled. Check the rcS / firefly script for the logic how to load a mixer in there.

**Comment by pmukherj** [comment]
My bad, I have the 3DR IRIS, so the gimbal connection is by default through the Aux out port (1 and 6 = roll and pitch of the gimbal).  I was going to move them to the RC out so I can control it through mavros, but this would potentially work much cleaner.

**Comment by vooon** [comment]
@pmukherj Look constant CHAN_RELEASE in http://docs.ros.org/indigo/api/mavros/html/msg/OverrideRCIn.html

But as mentioned by @mhkabir this message not supported by PX4.

@LorenzMeier it is possible to add messages for gimbal controller? Maybe it exist BGC with mavlink support?
I bought EvvGC and motors, but don't have working camera (camwrt stuck on video subsystem startup) and mounts for that. Also EvvGC seems dead, but it incredibly cheap...

**Comment by bduva002** [comment]
> This won't work. We don't handle RC override in PX4 stack.

Do you know if px4 support rc_channel_override yet ?

**Comment by fazlurnu** [comment]
> > This won't work. We don't handle RC override in PX4 stack.
> 
> Do you know if px4 support rc_channel_override yet ?

Yes, now you can use simply by publishing to mavros/rc/override topic

**Comment by W4li8** [comment]
This still doesn't work on PX4, does it?
``` rostopic pub -r 10 /mavros/rc/override mavros_msgs/OverrideRCIn "{channels: [1789, 65535, 65535, 65535, 65535, 65535, 65535, 800, 900, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535]}" ``` 
yields
``` [ WARN] [1690398217.820133869]: RC override not supported by this FCU! ```
I see some stuff about this only working from GS but that doesn't seem to help
