### ISSUE TITLE
Add support for direct actuator control 

### ISSUE THREAD

**Issue by mhkabir** [mavlink/mavros#229]
This will be a new plugin. A custom ROS message will need to be implemented too, ideally.

**Comment by mstuettgen** [comment]
Thanks for opening. 
where can i find the definitions of the actuator control messages? do you have some example code to start?

**Comment by mstuettgen** [comment]
https://pixhawk.ethz.ch/mavlink/#SET_ACTUATOR_CONTROL_TARGET

thats our baby

**Comment by vooon** [comment]
Description looks like [RCOut.msg](http://docs.ros.org/indigo/api/mavros/html/msg/RCOut.html).

**Comment by mstuettgen** [comment]
Hmm RCout unfortunately uses uint16t... i need float
i might begin with std_msgs/float for testing

**Comment by mstuettgen** [comment]
http://docs.ros.org/indigo/api/std_msgs/html/msg/Float32MultiArray.html should do for testing

**Comment by mhkabir** [comment]
@mstuettgen Awesome job on the plugin :) I just woke and saw the semicolon thing CD
I'll be closing this once you confirm that you have it working in Firmware

**Comment by mhkabir** [comment]
Also, please make a generic wiki page in the PX4 wiki regarding off board actuator control. I'll patch it up and integrate with the rest of the off board docs.
Also, regarding the rover page, I think you can remove it from ROS as of now. I might take the current controller up sometime later, add positiom controller and turn it into a new standalone platform ;)

Thanks!!
