### ISSUE TITLE
Change plugin topic namespaces

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#233]
I think that almost each plugin must be in their own namespace.
I don't like current mix in `~/setpoint/`, `global_location` and raw gps in `~/fix`.

Core plugins:
- [x] gps
- [x] local_position
- [x] global_position
- [x] setpoint_accel
- [x] setpoint_alttitude
- [x] setpoint_position
- [x] setpoint_velocity

**Comment by tonybaltovski** [comment]
+1

**Comment by vooon** [comment]
Done.
