### ISSUE TITLE
Better names for plugin topics

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#247]
We need some naming convention.
For now i only define that better use namespace with same name as plugin alias (where it is useful) (e.g. plugin `gps`: ns `~gps`).
That was common rule, but not strict. Also plugin with single topic (better with same name as plugin) may use `~`.

Current ns exceptions:

| plugin | namespace | topics |
| -------- | --------------- | ------- |
| `3dr_radio` | `~` | `radio_status` |
| `actuator_control` | `~` | `actuator_control` |
| `command` | `~cmd` | |
| `imu_pub` | `~imu` | |
| `rc_io` | `~rc` | |
| `sys_status` | `~` | |
| `sys_time` | `~` | |
| `vfr_hud` | `~` | `vfr_hud`, `wind_estimation` |
| `waypoint` | `~mission` | |
|  **extras**  | --- | --- |
| `image_pub` | `~image` | |
| `mocap_pose_estimate` | `~mocap` | |
| `vision_pose_estimate` | `~vision_pose` | |
| `vision_speed_estimate` | `~vision_speed` | |

That issue related to #226, #211, #206.

**Comment by tonybaltovski** [comment]
Perhaps use velocity instead of speed? Everything else +1.

**Comment by vooon** [comment]
My list of "bad" topic names and possible new names:

| plugin | topic | new name | comment |
| --- | --- | --- | --- |
| `actuator_control` | `~actuator_controls` | `~actuator_control` | plural |
| `local_position` | `~local_position/local` | ??? | |
| `px4flow` | `~px4flow/raw/optical_flow_rad` | ??? | raw? |
| `safety_area` | `~safety_area/set` | ??? | maybe place it to `~`? |
| `setpoint_position` | `~setpoint_position/local_position` | ??? | do we need `local_`? |
| `vision_pose_estimate` | `~vision_pose/vision` | ? | |
| `vision_speed_estimate` | `~vision_speed/speed_vector` | ? | |
| `global_position` | `~global_position/global` | `global_position/fix`? | |
| | `~global_position/local` | ? | |

**Comment by TSC21** [comment]
@vooon in the case of `~setpoint_position/local_position`, `local_` is needed if we want to add a plugin to send `global_position` (`SET_POSITION_TARGET_GLOBAL_INT` message).

**Comment by TSC21** [comment]
Agree with `~safety_area/set` be in `~`.

**Comment by vooon** [comment]
Hmm, i think better keep `~safety_area` ns for params, so i keep `set` for now.

**Comment by vooon** [comment]
Changed only `actuator_control`. Safety area are ok.

@mhkabir please look too.

**Comment by tonybaltovski** [comment]
Just throwing out ideas:

- `~vision_pose/vision`  -> `~vision/pose`
- `~vision_speed/speed_vector` -> `~vision/velocity`
- `~setpoint_position/local_position` -> `~setpoint_position/local`
-  `~local_position/local` -> `~local_position/pose`

**Comment by vooon** [comment]
I don't want merge namespaces between plugins anymore (`~setpoint/`).
But other looks ok. Table updated.

**Comment by vooon** [comment]
Updated table. Decided keep current names in `local_position`, `global_position` and `px4flow`.

**Comment by vooon** [comment]
Table updated.

Plugins updated too. And because no new changes proposed i close issue.
