### ISSUE TITLE
Sending commands to FCU

### ISSUE THREAD

**Issue by mhkabir** [mavlink/mavros#25]
What would be best way we could implement sending of messages via Mavlink to a connected FCU?

I want to send the VISION_POSITION_ESTIMATE mavlink message, with data from another node.

**Comment by BabakAkbari** [comment]
Hi 
I followed @vooon instruction and I was able to successfully build my custom plugin
But I am currently unable to run this plugin
Now I have .so file in my /devel directory
I don't know what to do further?

**Comment by vooon** [comment]
@BabakAkbari check that you sourced `~/ws/devel/setup.bash` after the build.

**Comment by BabakAkbari** [comment]
After sourcing ~/ws/devel/setup.bash and 
Launching mavros I should be able to see my topic I created? Does Mavros automatically find my package and plugin which is located in another workspace? @vooon

**Comment by vooon** [comment]
It's how http://wiki.ros.org/pluginlib works.

пт, 2 авг. 2019 г. в 11:56, BabakAkbari <notifications@github.com>:

**Comment by BabakAkbari** [comment]
Hi @vooon thanks for your response
I ran "rospack plugins --attrib=plugin mavros"
And it returned the name of my plugin but when I launch apm I can't see my plugin's name in the list of plugins mavros shows
Also I ran rostopic list and my plugin's topic not shown as well. Am I doing something wrong?

**Comment by vooon** [comment]
Check that your plugin have same format as present mavros. That issue is quite old, so it describe older plugins.
Also check that you have all necessary macroses called. Check dummy.cpp.
