### ISSUE TITLE
GPS OVERRIDE

### ISSUE THREAD

**Issue by dottantgal** [mavlink/mavros#250]
Hi all,
do you think it is possible to override the gps signal (getting datas from an optitrack system) and use mavros/pixhawk/ardupilot machine indoor to develop control loop algorithms ???
thank you

**Comment by vooon** [comment]
It is possible, but anyway you must change firmware first. Also note that extras alredy has mocap plugin.

**Comment by dottantgal** [comment]
Ok and how can i use them? Is it possible to substitute this data with gps then we can use the loiter mode (or to access it)?

**Comment by vooon** [comment]
I mean that currently FCU don't handle any mocap messages, only PX4 can handle vision position estimates (with inav).
So you should implement that in firmware, and for that you may use message implemented in mocap plugin.

**Comment by mhkabir** [comment]
Use the PX4 stack and not APM.

**Comment by dottantgal** [comment]
I've spent a lot of time whitin the code...What do you think if I'm going to write an internal app that  publishes the PX4s uORB vehicle_gps_position fake topic for the AP_GPS_PX4 driver that will present the data received to the APM?? I don't think that there is some kind of check about the data (maybe something about the uart connection of the hardware), so it could be possible.
Let me know 
Thanks

**Comment by vooon** [comment]
Better ask at [drone-discuss](https://groups.google.com/forum/#!forum/drones-discuss).

**Comment by mhkabir** [comment]
Or px4users

Depending on the flight stack you end up using.

**Comment by vooon** [comment]
Any update?

**Comment by dottantgal** [comment]
Yes, i'm creating a ROS node that is able to send GPS fake messages. At the moment i can get the green light using costants value, but i'm going to fix it using variable values!! It  seems to work because i can switch to Loiter mode without problems :dancer:
