### ISSUE TITLE
source install

### ISSUE THREAD

**Issue by blankered** [mavlink/mavros#259]
I am trying to compile from source the new mavros 0.11 on indigio armhf. I get stuck at 54% when I run catkin_make. I understand that this is all still under development and hasn't been officially released yet through ros but I thought I would post the error I am having anyway so to help with the development.

[ 54%] Building CXX object mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/sys_status.cpp.o
In file included from /opt/ros/indigo/include/ros/assert.h:35:0,
                 from /opt/ros/indigo/include/ros/common.h:36,
                 from /opt/ros/indigo/include/ros/publisher.h:32,
                 from /opt/ros/indigo/include/ros/node_handle.h:32,
                 from /opt/ros/indigo/include/diagnostic_updater/diagnostic_updater.h:42,
                 from /opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/include/mavros/mavros_plugin.h:21,
                 from /opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:17:
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp: In member function 'void mavplugin::SystemStatusPlugin::handle_autopilot_version(const mavlink_message_t*, uint8_t, uint8_t)':
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:589:9: error: 'mavlink_autopilot_version_t' has no member named 'flight_sw_version'
     apv.flight_sw_version,
         ^
/opt/ros/indigo/include/ros/console.h:342:165: note: in definition of macro 'ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER'
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
                                                                                                                                                                     ^
/opt/ros/indigo/include/ros/console.h:375:7: note: in expansion of macro 'ROSCONSOLE_PRINT_AT_LOCATION'
       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
       ^
/opt/ros/indigo/include/ros/console.h:516:35: note: in expansion of macro 'ROS_LOG_COND'
 #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/include/rosconsole/macros_generated.h:100:35: note: in expansion of macro 'ROS_LOG'
 #define ROS_INFO_NAMED(name, ...) ROS_LOG(::ros::console::levels::Info, std::string(ROSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:588:3: note: in expansion of macro 'ROS_INFO_NAMED'
   ROS_INFO_NAMED("sys", "VER: Flight software:     %08x (%*s)",
   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:590:12: error: 'mavlink_autopilot_version_t' has no member named 'flight_custom_version'
     8, apv.flight_custom_version);
            ^
/opt/ros/indigo/include/ros/console.h:342:165: note: in definition of macro 'ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER'
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
                                                                                                                                                                     ^
/opt/ros/indigo/include/ros/console.h:375:7: note: in expansion of macro 'ROSCONSOLE_PRINT_AT_LOCATION'
       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
       ^
/opt/ros/indigo/include/ros/console.h:516:35: note: in expansion of macro 'ROS_LOG_COND'
 #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/include/rosconsole/macros_generated.h:100:35: note: in expansion of macro 'ROS_LOG'
 #define ROS_INFO_NAMED(name, ...) ROS_LOG(::ros::console::levels::Info, std::string(ROSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:588:3: note: in expansion of macro 'ROS_INFO_NAMED'
   ROS_INFO_NAMED("sys", "VER: Flight software:     %08x (%*s)",
   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:592:9: error: 'mavlink_autopilot_version_t' has no member named 'middleware_sw_version'
     apv.middleware_sw_version,
         ^
/opt/ros/indigo/include/ros/console.h:342:165: note: in definition of macro 'ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER'
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
                                                                                                                                                                     ^
/opt/ros/indigo/include/ros/console.h:375:7: note: in expansion of macro 'ROSCONSOLE_PRINT_AT_LOCATION'
       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
       ^
/opt/ros/indigo/include/ros/console.h:516:35: note: in expansion of macro 'ROS_LOG_COND'
 #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/include/rosconsole/macros_generated.h:100:35: note: in expansion of macro 'ROS_LOG'
 #define ROS_INFO_NAMED(name, ...) ROS_LOG(::ros::console::levels::Info, std::string(ROSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:591:3: note: in expansion of macro 'ROS_INFO_NAMED'
   ROS_INFO_NAMED("sys", "VER: Middleware software: %08x (%*s)",
   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:593:12: error: 'mavlink_autopilot_version_t' has no member named 'middleware_custom_version'
     8, apv.middleware_custom_version);
            ^
/opt/ros/indigo/include/ros/console.h:342:165: note: in definition of macro 'ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER'
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
                                                                                                                                                                     ^
/opt/ros/indigo/include/ros/console.h:375:7: note: in expansion of macro 'ROSCONSOLE_PRINT_AT_LOCATION'
       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
       ^
/opt/ros/indigo/include/ros/console.h:516:35: note: in expansion of macro 'ROS_LOG_COND'
 #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/include/rosconsole/macros_generated.h:100:35: note: in expansion of macro 'ROS_LOG'
 #define ROS_INFO_NAMED(name, ...) ROS_LOG(::ros::console::levels::Info, std::string(ROSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:591:3: note: in expansion of macro 'ROS_INFO_NAMED'
   ROS_INFO_NAMED("sys", "VER: Middleware software: %08x (%*s)",
   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:595:9: error: 'mavlink_autopilot_version_t' has no member named 'os_sw_version'
     apv.os_sw_version,
         ^
/opt/ros/indigo/include/ros/console.h:342:165: note: in definition of macro 'ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER'
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
                                                                                                                                                                     ^
/opt/ros/indigo/include/ros/console.h:375:7: note: in expansion of macro 'ROSCONSOLE_PRINT_AT_LOCATION'
       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
       ^
/opt/ros/indigo/include/ros/console.h:516:35: note: in expansion of macro 'ROS_LOG_COND'
 #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/include/rosconsole/macros_generated.h:100:35: note: in expansion of macro 'ROS_LOG'
 #define ROS_INFO_NAMED(name, ...) ROS_LOG(::ros::console::levels::Info, std::string(ROSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:594:3: note: in expansion of macro 'ROS_INFO_NAMED'
   ROS_INFO_NAMED("sys", "VER: OS software:         %08x (%*s)",
   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:596:12: error: 'mavlink_autopilot_version_t' has no member named 'os_custom_version'
     8, apv.os_custom_version);
            ^
/opt/ros/indigo/include/ros/console.h:342:165: note: in definition of macro 'ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER'
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
                                                                                                                                                                     ^
/opt/ros/indigo/include/ros/console.h:375:7: note: in expansion of macro 'ROSCONSOLE_PRINT_AT_LOCATION'
       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
       ^
/opt/ros/indigo/include/ros/console.h:516:35: note: in expansion of macro 'ROS_LOG_COND'
 #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/include/rosconsole/macros_generated.h:100:35: note: in expansion of macro 'ROS_LOG'
 #define ROS_INFO_NAMED(name, ...) ROS_LOG(::ros::console::levels::Info, std::string(ROSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:594:3: note: in expansion of macro 'ROS_INFO_NAMED'
   ROS_INFO_NAMED("sys", "VER: OS software:         %08x (%*s)",
   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:597:63: error: 'mavlink_autopilot_version_t' has no member named 'board_version'
   ROS_INFO_NAMED("sys", "VER: Board hardware:      %08x", apv.board_version);
                                                               ^
/opt/ros/indigo/include/ros/console.h:342:165: note: in definition of macro 'ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER'
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
                                                                                                                                                                     ^
/opt/ros/indigo/include/ros/console.h:375:7: note: in expansion of macro 'ROSCONSOLE_PRINT_AT_LOCATION'
       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
       ^
/opt/ros/indigo/include/ros/console.h:516:35: note: in expansion of macro 'ROS_LOG_COND'
 #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/include/rosconsole/macros_generated.h:100:35: note: in expansion of macro 'ROS_LOG'
 #define ROS_INFO_NAMED(name, ...) ROS_LOG(::ros::console::levels::Info, std::string(ROSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:597:3: note: in expansion of macro 'ROS_INFO_NAMED'
   ROS_INFO_NAMED("sys", "VER: Board hardware:      %08x", apv.board_version);
   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:598:56: error: 'mavlink_autopilot_version_t' has no member named 'vendor_id'
   ROS_INFO_NAMED("sys", "VER: VID/PID: %04x:%04x", apv.vendor_id, apv.product_id);
                                                        ^
/opt/ros/indigo/include/ros/console.h:342:165: note: in definition of macro 'ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER'
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
                                                                                                                                                                     ^
/opt/ros/indigo/include/ros/console.h:375:7: note: in expansion of macro 'ROSCONSOLE_PRINT_AT_LOCATION'
       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
       ^
/opt/ros/indigo/include/ros/console.h:516:35: note: in expansion of macro 'ROS_LOG_COND'
 #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/include/rosconsole/macros_generated.h:100:35: note: in expansion of macro 'ROS_LOG'
 #define ROS_INFO_NAMED(name, ...) ROS_LOG(::ros::console::levels::Info, std::string(ROSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:598:3: note: in expansion of macro 'ROS_INFO_NAMED'
   ROS_INFO_NAMED("sys", "VER: VID/PID: %04x:%04x", apv.vendor_id, apv.product_id);
   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:598:71: error: 'mavlink_autopilot_version_t' has no member named 'product_id'
   ROS_INFO_NAMED("sys", "VER: VID/PID: %04x:%04x", apv.vendor_id, apv.product_id);
                                                                       ^
/opt/ros/indigo/include/ros/console.h:342:165: note: in definition of macro 'ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER'
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
                                                                                                                                                                     ^
/opt/ros/indigo/include/ros/console.h:375:7: note: in expansion of macro 'ROSCONSOLE_PRINT_AT_LOCATION'
       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
       ^
/opt/ros/indigo/include/ros/console.h:516:35: note: in expansion of macro 'ROS_LOG_COND'
 #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/include/rosconsole/macros_generated.h:100:35: note: in expansion of macro 'ROS_LOG'
 #define ROS_INFO_NAMED(name, ...) ROS_LOG(::ros::console::levels::Info, std::string(ROSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:598:3: note: in expansion of macro 'ROS_INFO_NAMED'
   ROS_INFO_NAMED("sys", "VER: VID/PID: %04x:%04x", apv.vendor_id, apv.product_id);
   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:599:65: error: 'mavlink_autopilot_version_t' has no member named 'uid'
   ROS_INFO_NAMED("sys", "VER: UID: %016llx", (long long int)apv.uid);
                                                                 ^
/opt/ros/indigo/include/ros/console.h:342:165: note: in definition of macro 'ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER'
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
                                                                                                                                                                     ^
/opt/ros/indigo/include/ros/console.h:375:7: note: in expansion of macro 'ROSCONSOLE_PRINT_AT_LOCATION'
       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
       ^
/opt/ros/indigo/include/ros/console.h:516:35: note: in expansion of macro 'ROS_LOG_COND'
 #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/include/rosconsole/macros_generated.h:100:35: note: in expansion of macro 'ROS_LOG'
 #define ROS_INFO_NAMED(name, ...) ROS_LOG(::ros::console::levels::Info, std::string(ROSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
                                   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:599:3: note: in expansion of macro 'ROS_INFO_NAMED'
   ROS_INFO_NAMED("sys", "VER: UID: %016llx", (long long int)apv.uid);
   ^
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp: In member function 'void mavplugin::SystemStatusPlugin::autopilot_version_cb(const ros::TimerEvent&)':
/opt/ros/indigo/share/mavros/workspace/src/mavros/mavros/src/plugins/sys_status.cpp:628:26: error: 'MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES' was not declared in this scope
    cmd.request.command = MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES;
                          ^
make[2]: *** [mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/sys_status.cpp.o] Error 1
make[1]: *** [mavros/mavros/CMakeFiles/mavros_plugins.dir/all] Error 2
make: *** [all] Error 2
make: INTERNAL: Exiting with 4 jobserver tokens available; should be 3!
Invoking "make" failed
ubuntu@tegra-ubuntu:/opt/ros/indigo/share/mavros/workspace$ _FileRemoveDir
bash: _FileRemoveDir: command not found
ubuntu@tegra-ubuntu:/opt/ros/indigo/share/mavros/workspace$ Scanning dependencies of target _mavros_generate_messages_check_deps_ActuatorControl
bash: Scanning: command not found
ubuntu@tegra-ubuntu:/opt/ros/indigo/share/mavros/workspace$ [  2%] Built target _mavros_generate_messages_check_deps_ActuatorControl
bash: [: missing `]'
ubuntu@tegra-ubuntu:/opt/ros/indigo/share/mavros/workspace$ Scanning dependencies of target _mavros_generate_messages_check_deps_WaypointPull
bash: Scanning: command not found
ubuntu@tegra-ubuntu:/opt/ros/indigo/share/mavros/workspace$ [  2%] Built target _mavros_generate_messages_check_deps_WaypointPull
bash: [: missing `]'
ubuntu@tegra-ubuntu:/opt/ros/indigo/share/mavros/workspace$ Scanning dependencies of target _mavros_generate_messages_check_deps_FileRemove
bash: Scanning: command not found
ubuntu@tegra-ubuntu:/opt/ros/indigo/share/mavros/workspace$ _FileRemoveDir
bash: _FileRemoveDir: command not found
ubuntu@tegra-ubuntu:/opt/ros/indigo/share/mavros/workspace$ Scanning dependencies of target _mavros_generate_messages_check_deps_ActuatorControl
bash: Scanning: command not found
ubuntu@tegra-ubuntu:/opt/ros/indigo/share/mavros/workspace$ [  2%] Built target _mavros_generate_messages_check_deps_ActuatorControl
bash: [: missing `]'
ubuntu@tegra-ubuntu:/opt/ros/indigo/share/mavros/workspace$ Scanning dependencies of target _mavros_generate_messages_check_deps_WaypointPull
bash: Scanning: command not found
ubuntu@tegra-ubuntu:/opt/ros/indigo/share/mavros/workspace$ [  2%] Built target _mavros_generate_messages_check_deps_WaypointPull
bash: [: missing `]'
ubuntu@tegra-ubuntu:/opt/ros/indigo/share/mavros/workspace$ Scanning dependencies of target _mavros_generate_messages_check_deps_FileRemove
bash: Scanning: command not found

**Comment by MarcGyongyosi** [comment]
There's something wrong with the mavlink version as far as I know and the message definitions mess up. There is a workaround described in one of the closed/solved issues on here. You have to install mavlink separately. I got it working on a jetson tk1.

**Comment by blankered** [comment]
was this your solution?
https://github.com/mavlink/mavros/issues/240

**Comment by blankered** [comment]
I installed mavlink from source but catkin_make in /opt/ros/indigo/share/mavros/workspace still fails

**Comment by blankered** [comment]
I was trying to compile a modified local_position.cpp file and think this was the cause of the error.
