### ISSUE TITLE
Add support to DISTANCE_SENSOR msg coder/decoder

### ISSUE THREAD

**Issue by TSC21** [mavlink/mavros#264]
Related to https://github.com/PX4/Firmware/issues/1986.

**Comment by TSC21** [comment]
Ideally, this has the following features:
- [ ] rosserial connection
- [ ] `DISTANCE_SENSOR` coder (decoder may only make sense if sensor is connected on the FCU)

**Comment by mhkabir** [comment]
A decoder probably makes more sense since it is better to connect whatever low level peripherals you want (e.g Laser ranger)  to your flight controller. 
Not much point using the companion computer for this. It would use up a serial port too. 
And serial isn't the best bus for external sensors. Use a more appropriate bus  (SPI,  UAVCAN) for interfacing external sensors. 

For the decoder to ROS, see the flow plugin. Add a appropriate handler in a new plugin and send in a a PR :D

**Comment by mhkabir** [comment]
PX4 implementation would involve adding a mavlink message stream to read from the distance sensor uORB topic.

**Comment by TSC21** [comment]
@mhkabir thanks for your inputs. I wasn't really asking to this to be implemented, more like this is an ongoing implementation where ideas are welcomed :D 
The decoder is certainly easy to get done, also as the coder. The PX4 implementation though can involve adding support to this message I think.

**Comment by vooon** [comment]
Plugin almost done, by #292 . Need test and fix todo.

**Comment by vooon** [comment]
(#292 merged, my fixes also uses that number. Perhaps better use this issue, but too late)

**Comment by TSC21** [comment]
@vooon new sensor type was added: https://github.com/mavlink/mavlink/pull/381/files. So, ideally @tfoote could add `LASER` `radiation_type` to `Range.msg` enum (reason: as I explained in the comment on https://github.com/mavlink/mavros/pull/292#issuecomment-101754507).

**Comment by TSC21** [comment]
Another thing: https://github.com/mavlink/mavlink/pull/383/files - can this enum be added then to `/mavros/mavros/include/mavros` in `sensor_orientation.h` or similar?

**Comment by vooon** [comment]
@TSC21 as soon as it merged i will do release of mavlink package.

**Comment by TSC21** [comment]
OK. Any ideas how to then include it here: https://github.com/TSC21/mavros/blob/external_sensors_connect/mavros_extras/src/plugins/distance_sensor.cpp#L231?

**Comment by TSC21** [comment]
Update: https://github.com/mavlink/mavros/pull/296#issuecomment-102821032

**Comment by vooon** [comment]
Make a std::array with orientations then choose one by orientation enum.
Also add param for setting parent frame_id, child frame_id same as in Range.header.

As i understand tf: you don't need actually rotate FCU frame_id, only publish sensor orientation value.

**Comment by TSC21** [comment]
OK I think I will do this in a next PR. You can merge this one in the mean time, if everything's ok.

**Comment by TSC21** [comment]
@vooon https://github.com/mavlink/mavlink/pull/383 was merged. You can do mavlink release now.

**Comment by vooon** [comment]
Already done.

**Comment by vooon** [comment]
- https://github.com/ros/rosdistro/pull/8482
- https://github.com/ros/rosdistro/pull/8483
- https://github.com/ros/rosdistro/pull/8484

**Comment by TSC21** [comment]
> Also add param for setting parent frame_id, child frame_id same as in Range.header.

Why do we need parent frame_id, if we only want tf between `fcu` and the sensor? Doesn't make sense to add other tfs, I think.

> As i understand tf: you don't need actually rotate FCU frame_id, only publish sensor orientation value.

We don't rotate fcu frame. We rotate the sensor id accoriding to the enum and then the tf between the fcu and the sensor is published, with the proper orientation of the sensor being updated.

**Comment by TSC21** [comment]
And do you merge now or are you waiting for the orientation stuff?

**Comment by vooon** [comment]
Waiting orientation and **test results**.

**Comment by TSC21** [comment]
Results from which side? Cause ROS side working ok. I'm getting the PX4 side worked on now.

**Comment by vooon** [comment]
Ok, if you say that plugin works, it's enough for now. I can merge current PR if you need that. But probably better merge when all features done.

**Comment by TSC21** [comment]
No need to merge, unless some other PR is added. I'm advancing to create the `std::array sensor_orientation`. One question: isn't it better to add it to `uas` definition, so to be used by other plugins if needed?

**Comment by vooon** [comment]
Because it not depend on uas data it may be simple helper function in
libmavros. Please make new cpp.
18.05.2015 23:29 пользователь "TSC21" <notifications@github.com> написал:

**Comment by TSC21** [comment]
You mean here: https://github.com/mavlink/mavros/tree/master/mavros/include/mavros?

**Comment by vooon** [comment]
I mean src/lib, and add function definition to utils.h
19.05.2015 0:24 пользователь "TSC21" <notifications@github.com> написал:

**Comment by TSC21** [comment]
so what do I put in `/src/lib/sensor_orientation.h` and what do I put in `/include/mavros/utils.h`?

**Comment by vooon** [comment]
C++ and C split definition and implementation in `.h` and `.cpp` (`.c`) files. So you should put function definition in `utils.h` and implementation in `/src/lib/sensor_orientation.cpp`.

Then just use `<mavros/utils.h>`.

**Comment by TSC21** [comment]
> C++ and C split definition and implementation in .h and .cpp (.c) files. So you should put function definition in utils.h and implementation in /src/lib/sensor_orientation.cpp.
Then just use <mavros/utils.h>.

OK that was what I was already doing :) thanks

**Comment by TSC21** [comment]
In `utils.h`, do I have to use `inline`, since the method implementation is in `/src/lib/sensor_orientation.cpp`?

**Comment by vooon** [comment]
No! Inline for `.h` files. And there regular function, so no `static`, no `inline` no `constexpr`.

**Comment by TSC21** [comment]
Willco :+1:

**Comment by TSC21** [comment]
This is tested and working ;) so can be closed, since https://github.com/mavlink/mavros/pull/292 has been merged!
