### ISSUE TITLE
Fix mavsetp script to use new topics

### ISSUE THREAD

**Issue by mhkabir** [mavlink/mavros#270]
Currently : 
```
Mavros not started, nobody subcsribes to /mavros/setpoint/local_position

```

**Comment by vooon** [comment]
Strange, i fixed all names when introduce [`mavros.setpoint`][1] module. Maybe you run old version?

[1]: https://github.com/mavlink/mavros/blob/master/mavros/src/mavros/setpoint.py

**Comment by vooon** [comment]
@mhkabir any update?

**Comment by mhkabir** [comment]
OK, this works on latest.

Must've been issue with old version. Closing.
