### ISSUE TITLE
HIGHRES_IMU bitmask

### ISSUE THREAD

**Issue by hitimo** [mavlink/mavros#280]
Why is this bitmask needed?
https://github.com/mavlink/mavros/blob/master/mavros/src/plugins/imu_pub.cpp#L240

Thanks a lot!

**Comment by vooon** [comment]
Look documentation: https://pixhawk.ethz.ch/mavlink/#HIGHRES_IMU

**Comment by hitimo** [comment]
Ah yes that makes sense, thank you.
