### ISSUE TITLE
Mavros_extra plugin not found

### ISSUE THREAD

**Issue by Royalcheese** [mavlink/mavros#282]
Hi everyone ! 
i experiment some problem with mavros extra plugins, mavros don’t find the associated library of the mavros_extra plugins in order to make mocap vision working. Any idea why does it not find them ? 
Thanks in advanced,
best regards.

**Comment by vooon** [comment]
Did you do `source ~/your_ws/devel/setup.bash` after build?

**Comment by vooon** [comment]
Updates?

**Comment by Royalcheese** [comment]
The source setup.bash was done, and Mavros/ px4 have been updated 2 hours before..

**Comment by vooon** [comment]
What ROS version used? I seen similar bug on Hydro when updated to REP 140 package.xml.
I recommend to update at least to Indigo (Jade release soon, but now it lack some useful packages like rviz).

**Comment by Royalcheese** [comment]
You're right , upgrading to Indigo makes this problem not happening . Thank you !
