### ISSUE TITLE
Can VICON data replace local_postion data?

### ISSUE THREAD

**Issue by wangsen1312** [mavlink/mavros#289]
Now I have get the position from VICON, I can send the attitude and position to TOPIC vision_pose_estimate. Because I don't have GPS now, So can I transfer VICON data to local_position instead so that I can navigation indoor.

**Comment by Royalcheese** [comment]
I don't see the question :p

**Comment by wangsen1312** [comment]
@Royalcheese  Thank you for your attention. 
Now what I want to is using VICON data instead the local_position calculated by FCU. 
Can you give me some suggestion?

**Comment by Royalcheese** [comment]
I've experimented same problem last week ^^ In fact the purpose is done, but you have to remap data in node.launch file.
Something like that : <remap from="/mavros/vision_pose/pose" to="/mavros/mocap/pose">
you have more explanation on remap here : http://wiki.ros.org/roslaunch/XML/remap
and some remap example here : https://pixhawk.org/dev/ros/visual_estimation
I Hope it will help :)
have a good day!

**Comment by wangsen1312** [comment]
@Royalcheese Thank you very much! I will try it ASAP.

**Comment by Royalcheese** [comment]
Take care of the weight of "vision sensor" in parameter of the fcu : you can set it via QGC . It must be very higher than the other parameter of position (GPS..) because it work like a vision sensor ( as i understood) and the weight is the credit accorded to the sensor. If you want to be full with vision sensor you should increase this weight high.
Take care at CBRK_no_vision = 0 too 
have a good day !

**Comment by wangsen1312** [comment]
@Royalcheese   Thank you for your reminder!  There is still something wrong that why I still can't see the local_position.   I get the vicon data and publish it to vision_pose_estimate topic and I add the remap in launch file.  
Do you have the same setup as me?  Can you share what you do? Thank you very much!

**Comment by wangsen1312** [comment]
@Royalcheese  Now I can get the local_position NOW. But I still cannot change the local_position data with the VICON when I use the remap?
Did your works well? Thank you very much!

**Comment by Royalcheese** [comment]
Mine works, have you decreased the weight of other sensors in QGC ?

**Comment by Royalcheese** [comment]
https://pixhawk.org/dev/ros/visual_estimation?s[]=odroid

**Comment by wangsen1312** [comment]
@Royalcheese   In QGC, How can I find the weight of sensors parameters? I only find the CBRK_no_vision and change it to 0.
Thank you very much~

**Comment by wangsen1312** [comment]
@Royalcheese  Thank you very much! I can make the local_position workable. Does this workable when use setposition/local topic?

**Comment by vooon** [comment]
I think yes, as i understood commander uses same local position uORB that you can see in mavros topic.

**Comment by Royalcheese** [comment]
I'm on it ;) like vooon I think it does, but offboard control behaviour is somehow.. strange for now ^^

**Comment by wangsen1312** [comment]
@Royalcheese Thank you very much~ I will try it ASAP. If I can get the stable result, I will tell you soon.

**Comment by Royalcheese** [comment]
Thanks you ! right now i've connected ground PC to ODROID to FCU. i will test vicon data and offboard soon

**Comment by congleetea** [comment]
@Royalcheese Hi, i also send the mocap data to local position(use vision_pose no speed via mavros ) , but the z value drifts, how is your result?maybe you can give me some advice. i set all weight parameter to zero except for vision weight. and the flyer also can not track the setpoint position . thanks a lot in advanced.

**Comment by Royalcheese** [comment]
Hi :)
please tell me :
I have : INAV_w_z_vis_p = 8 , INAV_w_z_vis_p = 7 ,CBRV_no_vision = 0 but I guess you've this too.
please tell me :
Where do you remap your mocap data ?
where do you remap your setpoint pos stream ?
Are x,y setting well ?

**Comment by jgoppert** [comment]
Try using this instead of inav, mocap is directly supported. https://github.com/PX4/Firmware/pull/2096

**Comment by wangsen1312** [comment]
@jgoppert  Thank you very much~ How Can I update my firmware and use it directly? Thank you very much~

**Comment by jgoppert** [comment]
```bash
git clone https://github.com/PX4/Firmware.git
cd Firmware
git remote add jgoppert https://github.com/jgoppert/Firmware.git
git fetch jgoppert
git checkout -t jgoppert/cart_pos_estimator
git submodules init
git submodules update
J=4 make archives
make -j4 px4fmu-v2_default upload
```

**Comment by congleetea** [comment]
@Royalcheese I set the vision weight max value 10, others are zero. I remap mocap data to /mavros/vision_pose/pose in launch file . the setpoints are directly publish on /mavros/setpoint_position_local/local. x y are well set. Now I can make the uav fly to setpoint , but I can not get vision_speed.  I just differential the pose simply, but the FCU have no any info on vision_speed.

**Comment by wangsen1312** [comment]
@congleetea    Thank you for share your progress. You can use remap and setpoint well, so can you offer me the demo launch file and setpoint file. I may have something wrong. Thank you in advance

**Comment by congleetea** [comment]
I use optitrack. just write a setpoint node , it is very simply . you can learn from ros tutorials.

**Comment by Royalcheese** [comment]
Hum I need more time to master it, but you have to have a look on mc_pos_control module and INAV module (if you're not using jgoppert estimator, but it seems to be better for mocap) 
you have several PID controller, their parameters are the parameters you set on QGC. 
With a XY_vision_V set to 0, I expect the gain to be 0 and so you see nothing. But if this parameter too high , you will have extreme variation of estimated speed, and excessive thrust variation ( +40, -40, no saturation ).
by the way, what kind of precaution have you used for Offboard test ?

**Comment by Royalcheese** [comment]
@congleetea  I have several question : 
What is the header.frame you're sending in setpoint pos ?
What header.fram you're sending in mocap, and vision_pos ?
All INAV parameter are set to 0 except vis_p_z and vis_p_xy and it works well ?
What are your remap 
by the way, what kind of precaution have you used for Offboard test ?
![truyc](https://cloud.githubusercontent.com/assets/12081886/7860520/2b839260-054a-11e5-97db-eac6491fe722.png)
from now I got this with 10 vis_z and intial other value for parameter
I can get this :
![screenshot from 2015-05-28 10 22 41](https://cloud.githubusercontent.com/assets/12081886/7860543/44d955d8-054a-11e5-88c7-96304d1e3c15.png)
but remap from local_position/local to vision_pose, and mocap to vision pose, but this is a mistake...
I can't test indoor without good simulation

**Comment by Royalcheese** [comment]
I got it ! Matter of ros::time

**Comment by Royalcheese** [comment]
![up1](https://cloud.githubusercontent.com/assets/12081886/7862222/d3253c6c-0554-11e5-9a7a-9045a60c6e73.png)
with your config i got this..

What precaution have you taken for testing offboard indoor ?

**Comment by Royalcheese** [comment]
This is because vel_z_derivator is default set to 0. And this is why we have no phase shift.
Any idea why @vooon ?

**Comment by Royalcheese** [comment]
@congleetea , have you change parameter on MPC ?
Could you send me your graph of trust and z_pos when you are rea

**Comment by TSC21** [comment]
@wangsen1312 are you able to test https://github.com/PX4/Firmware/pull/2361?
