### ISSUE TITLE
mavsys in .launch

### ISSUE THREAD

**Issue by tuloski** [mavlink/mavros#293]
Now it is not possible to put mavsys in the .launch file.
It'd be a nice feature to have.

**Comment by vooon** [comment]
Implementation steps:

1. [ ] extend mavros/State: add connection status flag
2. [ ] make `~/state` latched type
3. [ ] add flag (`--wait`) to mavsys that:
  a. waits rostopic creation
  b. waits until connection establish.

**Comment by vooon** [comment]
Also that flag may be very useful in some other tools.

- [ ] mavsafety, but perhaps w/o arm
- [ ] ??? Discussion?

**Comment by vooon** [comment]
@tuloski  Mavcmd wait implemented, need decide what tools also need it.

**Comment by vooon** [comment]
Done.

**Comment by tuloski** [comment]
Thank you very much ;)
