### ISSUE TITLE
Connection problem between Ground Control Station APM Planner and mavros using UDP link.

### ISSUE THREAD

**Issue by MauroPagliarella** [mavlink/mavros#297]
Hi all
I'm building a robot running ROS on board, and I would like to receive robot telemetries and send telecommands to the robot using the 
APM ground control station v2.0.17 using the mavros UDP link. I performed the test described here below but it didn't work.
Any help is appreciated. Thank you very much.
Mauro

SYSTEM CONFIGURATION:
1: Laptop running Ubuntu 14.04 & ROS Indigo with the following packages installed: 
	1262779 drwxr-xr-x   3 root  4096 mag 12 23:19 mavlink		
	1270356 drwxr-xr-x   6 root  4096 mag 12 23:19 mavros		
	1270615 drwxr-xr-x   5 root  4096 mag 12 23:19 mavros_extras	

2: The APM Planner v2.0.17 is installed and runs on the same laptop.

3: Arduino 1R3 with dummy firmware connectd to one of the laptop usb port.(Dummy only to have a connection on the serial port to allow ROS node to start). 

4: ROS Launch file (prova.launch) reported here below:

	<launch>
		
		

		<arg name="fcu_url" default="/dev/ttyACM0:57600" />
		<arg name="gcs_url" default="udp://@localhost:14550" />
		<arg name="tgt_system" default="1" />
		<arg name="tgt_component" default="50" />

		<include file="$(find mavros)/launch/node.launch">
			<arg name="pluginlists_yaml" value="$(find mavros)/launch/px4_pluginlists.yaml" />
			<arg name="config_yaml" value="$(find mavros)/launch/px4_config.yaml" />

			<arg name="fcu_url" value="$(arg fcu_url)" />
			<arg name="gcs_url" value="$(arg gcs_url)" />
			<arg name="tgt_system" value="$(arg tgt_system)" />
			<arg name="tgt_component" value="$(arg tgt_component)" />
		</include>
	</launch>

OBJECTIVE:
Connect the APM ground Control Station v2.0.17 to mavros UDP port 14550 to send commands to ROS and receive messages from ROS

PERFORMED OPERATIONS:
1: Open terminal session and start mavros on port 14550 using shell command: roslaunch mavros prova.launch 
2: start QGC: APM Planner v2.0.17 using shell command: ./release/apmplanner2

OPERATION 1 RESULTS:
mauro@mauro-HP-Pavilion-dv7-Notebook-PC:
mauro@mauro-HP-Pavilion-dv7-Notebook-PC:~$ roslaunch mavros prova.launch 
... logging to /home/mauro/.ros/log/8b90949a-fce5-11e4-80e1-6159cf7aef84/roslaunch-mauro-HP-Pavilion-dv7-Notebook-PC-4287.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://mauro-HP-Pavilion-dv7-Notebook-PC:42874/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat: 5.0
 * /mavros/conn/system_time: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync: 0.1
 * /mavros/fcu_url: /dev/ttyACM0:57600
 * /mavros/gcs_url: udp://@localhost:...
 * /mavros/global_position/child_frame_id: fcu
 * /mavros/global_position/frame_id: local_origin
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/send_tf: False
 * /mavros/gps/frame_id: gps
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: fcu
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/child_frame_id: fcu
 * /mavros/local_position/frame_id: local_origin
 * /mavros/local_position/send_tf: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/plugin_blacklist: ['image_pub']
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.0
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/child_frame_id: attitude
 * /mavros/setpoint_attitude/frame_id: local_origin
 * /mavros/setpoint_attitude/listen_tf: False
 * /mavros/setpoint_attitude/listen_twist: False
 * /mavros/setpoint_attitude/pose_with_covariance: False
 * /mavros/setpoint_attitude/reverse_throttle: False
 * /mavros/setpoint_attitude/tf_rate_limit: 10.0
 * /mavros/setpoint_position/child_frame_id: setpoint
 * /mavros/setpoint_position/frame_id: local_origin
 * /mavros/setpoint_position/listen_tf: False
 * /mavros/setpoint_position/tf_rate_limit: 50.0
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 50
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/vision_pose/child_frame_id: vision
 * /mavros/vision_pose/frame_id: local_origin
 * /mavros/vision_pose/listen_tf: False
 * /mavros/vision_pose/pose_with_covariance: False
 * /mavros/vision_pose/tf_rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /mavros/visualization/child_frame_id: fcu
 * /mavros/visualization/fixed_frame_id: local_origin
 * /mavros/visualization/marker_scale: 2.0
 * /rosdistro: indigo
 * /rosversion: 1.11.10

NODES
  /
    mavros (mavros/mavros_node)

auto-starting new master
process[master]: started with pid [4299]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8b90949a-fce5-11e4-80e1-6159cf7aef84
process[rosout-1]: started with pid [4312]
started core service [/rosout]
process[mavros-2]: started with pid [4330]
[ INFO] [1431902355.660706005]: FCU URL: /dev/ttyACM0:57600
[ INFO] [1431902355.661050812]: serial0: device: /dev/ttyACM0 @ 57600 bps
[ INFO] [1431902355.661529224]: GCS URL: udp://@localhost:14550
[ INFO] [1431902355.661758932]: udp1: Bind address: 0.0.0.0:14555
[ INFO] [1431902355.661958818]: udp1: Remote address: 127.0.0.1:14550
[ INFO] [1431902355.769189353]: Plugin 3dr_radio loaded and initialized
[ INFO] [1431902355.774063227]: Plugin actuator_control loaded and initialized
[ INFO] [1431902355.786747382]: Plugin command loaded and initialized
[ INFO] [1431902355.807565812]: Plugin ftp loaded and initialized
[ INFO] [1431902355.842113711]: Plugin global_position loaded and initialized
[ INFO] [1431902355.846146556]: Plugin gps loaded and initialized
[ INFO] [1431902355.846213324]: Plugin image_pub blacklisted
[ INFO] [1431902355.860693098]: Plugin imu_pub loaded and initialized
[ INFO] [1431902355.876255971]: Plugin local_position loaded and initialized
[ INFO] [1431902356.011910862]: Plugin mocap_pose_estimate loaded and initialized
[ INFO] [1431902356.016325739]: Plugin param loaded and initialized
[ INFO] [1431902356.030626021]: Plugin px4flow loaded and initialized
[ INFO] [1431902356.037952371]: Plugin rc_io loaded and initialized
[ INFO] [1431902356.053401682]: SA: Set safty area: P1(1.000000 1.000000 1.000000) P2(-1.000000 -1.000000 -1.000000)
[ INFO] [1431902356.059832458]: Plugin safety_area loaded and initialized
[ INFO] [1431902356.068275082]: Plugin setpoint_accel loaded and initialized
[ INFO] [1431902356.099076555]: Plugin setpoint_attitude loaded and initialized
[ INFO] [1431902356.120106604]: Plugin setpoint_position loaded and initialized
[ INFO] [1431902356.126373602]: Plugin setpoint_velocity loaded and initialized
[ INFO] [1431902356.149579486]: Plugin sys_status loaded and initialized
[ INFO] [1431902356.158961894]: Plugin sys_time loaded and initialized
[ INFO] [1431902356.161856955]: Plugin vfr_hud loaded and initialized
[ INFO] [1431902356.188444553]: Plugin vision_pose_estimate loaded and initialized
[ INFO] [1431902356.195364987]: Plugin vision_speed_estimate loaded and initialized
[ INFO] [1431902356.209803205]: Plugin visualization loaded and initialized
[ INFO] [1431902356.219869709]: Plugin waypoint loaded and initialized
[ INFO] [1431902356.220119741]: Autostarting mavlink via USB on PX4
[ INFO] [1431902356.220270458]: Built-in mavlink dialect: ardupilotmega
[ INFO] [1431902356.220402668]: MAVROS started. MY ID [1, 240], TARGET ID [1, 50]

OPERATION 2 RESULTS:
mauro@mauro-HP-Pavilion-dv7-Notebook-PC:~/Qt/MyProjects/apm_planner$
mauro@mauro-HP-Pavilion-dv7-Notebook-PC:~/Qt/MyProjects/apm_planner$ ./release/apmplanner2
 INFO 2015-05-18T00:41:46.335 QGCCore::initialize() 
 INFO 2015-05-18T00:41:46.335 Current Build Info 
 INFO 2015-05-18T00:41:46.335 Git Hash: c454c66aa2dc40e2f58cbfa0709748955cb9030d 
 INFO 2015-05-18T00:41:46.335 Git Commit: 2.0.17-43-gc454c66 
 INFO 2015-05-18T00:41:46.335 APPLICATION_NAME: "APM Planner" 
 INFO 2015-05-18T00:41:46.335 APPLICATION_VERSION: "v2.0.17" 
 INFO 2015-05-18T00:41:46.335 APP_PLATFORM: ubuntu64 
 INFO 2015-05-18T00:41:46.335 APP_TYPE: stable 
 INFO 2015-05-18T00:41:46.461 Start Link Manager 
DEBUG 2015-05-18T00:41:46.461 Create MAVLinkDecoder:  MAVLinkDecoder(0x1c5f340) 
 INFO 2015-05-18T00:41:46.464 Start UAS Manager 
DEBUG 2015-05-18T00:41:46.518 Creating MainWindow 
 INFO 2015-05-18T00:41:46.697 Creating SubMainWindow:  SubMainWindow(0x1cf9190) 
 INFO 2015-05-18T00:41:46.698 setting objectName:  "VIEW_MISSION" 
 INFO 2015-05-18T00:41:46.752 Creating SubMainWindow:  SubMainWindow(0x1db0140) 
 INFO 2015-05-18T00:41:46.752 setting objectName:  "VIEW_FLIGHT" 
 INFO 2015-05-18T00:41:46.793 Creating SubMainWindow:  SubMainWindow(0x1de9430) 
 INFO 2015-05-18T00:41:46.793 setting objectName:  "VIEW_HARDWARE_CONFIG" 
DEBUG 2015-05-18T00:41:46.949 fillPortsInfo  
 INFO 2015-05-18T00:41:46.956 Inserting  "ttyACM0" 
 INFO 2015-05-18T00:41:46.956 Inserting  "ttyUSB0" 
 INFO 2015-05-18T00:41:46.957 Inserting  "ttyUSB1" 
 INFO 2015-05-18T00:41:46.957 Inserting  "ttyUSB2" 
 INFO 2015-05-18T00:41:46.957 Inserting  "ttyUSB3" 
 INFO 2015-05-18T00:41:46.957 Changed Link to: "ttyACM0" 
 INFO 2015-05-18T00:41:47.341 Creating SubMainWindow:  SubMainWindow(0x1ea1dc0) 
 INFO 2015-05-18T00:41:47.341 setting objectName:  "VIEW_SOFTWARE_CONFIG" 
DEBUG 2015-05-18T00:41:47.369 Disable Controls 
 INFO 2015-05-18T00:41:47.631 Creating SubMainWindow:  SubMainWindow(0x2caa010) 
 INFO 2015-05-18T00:41:47.631 setting objectName:  "VIEW_ENGINEER" 
QObject::connect: No such signal QTableView::currentCellChanged(int,int,int,int)
QObject::connect:  (sender name:   'tableWidget')
QObject::connect:  (receiver name: 'AP2DataPlot2D')
 INFO 2015-05-18T00:41:47.669 Creating SubMainWindow:  SubMainWindow(0x2d89c80) 
 INFO 2015-05-18T00:41:47.669 setting objectName:  "VIEW_SIMULATOR" 
DEBUG 2015-05-18T00:41:47.732 MODE: 0 
DEBUG 2015-05-18T00:41:47.733 "D|PREFLIGHT" 
DEBUG 2015-05-18T00:41:47.733 MODE: 80 
DEBUG 2015-05-18T00:41:47.733 "D|STABILIZED" 
DEBUG 2015-05-18T00:41:47.734 MODE: 64 
DEBUG 2015-05-18T00:41:47.734 "D|MANUAL" 
DEBUG 2015-05-18T00:41:47.735 MODE: 88 
DEBUG 2015-05-18T00:41:47.735 "D|VECTOR|STABILIZED" 
DEBUG 2015-05-18T00:41:47.735 MODE: 92 
DEBUG 2015-05-18T00:41:47.736 "D|AUTO|STABILIZED" 
DEBUG 2015-05-18T00:41:47.736 MODE: 66 
DEBUG 2015-05-18T00:41:47.736 "D|TEST" 
DEBUG 2015-05-18T00:41:47.844  QUrl( "file:///home/mauro/Qt/MyProjects/apm_planner/qml/PrimaryFlightDisplayQML.qml" )  
DEBUG 2015-05-18T00:41:47.938 QML Status: 1 
DEBUG 2015-05-18T00:41:47.941  QUrl( "file:///home/mauro/Qt/MyProjects/apm_planner/qml/PrimaryFlightDisplayQML.qml" )  
DEBUG 2015-05-18T00:41:48.000 QML Status: 1 
 INFO 2015-05-18T00:41:48.008 UASActionsWidget creating  UASActionsWidget(0x33268b0) 
DEBUG 2015-05-18T00:41:48.012 QuickView: load settings 
DEBUG 2015-05-18T00:41:48.013 QuickView: loading key:  "GCS Status.Altitude (GPS) (m)"  type: "text" 
DEBUG 2015-05-18T00:41:48.018 QuickView: loading key:  "GCS Status.Altitude (REL) (m)"  type: "text" 
DEBUG 2015-05-18T00:41:48.021 QuickView: loading key:  "GCS Status.Battery (%)"  type: "text" 
DEBUG 2015-05-18T00:41:48.024 QuickView: loading key:  "GCS Status.Climb (m/s)"  type: "text" 
DEBUG 2015-05-18T00:41:48.028 QuickView: loading key:  "GCS Status.Current (A)"  type: "text" 
DEBUG 2015-05-18T00:41:48.032 QuickView: loading key:  "GCS Status.GPS Fix ()"  type: "text" 
DEBUG 2015-05-18T00:41:48.036 QuickView: loading key:  "GCS Status.GPS HDOP (m)"  type: "text" 
DEBUG 2015-05-18T00:41:48.041 QuickView: loading key:  "GCS Status.GPS Sats ()"  type: "text" 
DEBUG 2015-05-18T00:41:48.046 QuickView: loading key:  "GCS Status.Pitch (deg)"  type: "text" 
DEBUG 2015-05-18T00:41:48.051 QuickView: loading key:  "GCS Status.Roll (deg)"  type: "text" 
DEBUG 2015-05-18T00:41:48.057 QuickView: loading key:  "GCS Status.Voltage (V)"  type: "text" 
DEBUG 2015-05-18T00:41:48.063 QuickView: loading key:  "GCS Status.Yaw (deg)"  type: "text" 
DEBUG 2015-05-18T00:41:48.074 QuickView: load settings END 
 INFO 2015-05-18T00:41:48.159 Using Alsa Audio driver 
 WARN 2015-05-18T00:41:48.159 Dir directory tmp_audio exists 
DEBUG 2015-05-18T00:41:48.170 qmlBaseDir "/home/mauro/Qt/MyProjects/apm_planner" 
DEBUG 2015-05-18T00:41:48.170  QUrl( "file:///home/mauro/Qt/MyProjects/apm_planner/qml/ApmToolBar.qml" )  
APMToolBar:  SELECTED
DEBUG 2015-05-18T00:41:48.210 QML Status: 1 
DEBUG 2015-05-18T00:41:48.219 Loading widget: "PRIMARY_FLIGHT_DISPLAY_QML_DOCKWIDGET" 
DEBUG 2015-05-18T00:41:48.220 Loading widget: "UAS_INFO_INFOVIEW_DOCKWIDGET" 
 INFO 2015-05-18T00:41:48.492 UDP Created  "UDP Link (port:14550)" 
 INFO 2015-05-18T00:41:48.494 UDP disconnect 
 INFO 2015-05-18T00:41:48.496 UDPLink::UDP connect   QHostAddress( "0.0.0.0" )  : 14550 
ERROR 2015-05-18T00:41:48.496 bind failed!   QHostAddress( "0.0.0.0" )  : 14550 
DEBUG 2015-05-18T00:41:48.498 Create Serial Connection: SerialConnection(0x32971c0) 
 INFO 2015-05-18T00:41:48.499 "ttyACM0" 115200 
DEBUG 2015-05-18T00:41:48.502 APMToolBar: new Serial Link Created 2 
DEBUG 2015-05-18T00:41:48.502 APMToolBar setConnection: false 
DEBUG 2015-05-18T00:41:48.503 APMToolBar: updateLinkDisplay "ttyACM0" : "115200"  connected: false 
DEBUG 2015-05-18T00:41:48.565 SCW: Link is disconnected 
DEBUG 2015-05-18T00:41:48.573 Baud rate: 115200 Expected: 4 
DEBUG 2015-05-18T00:41:53.168 "retrieve versionobject from server: http://firmware.diydrones.com/Tools/APMPlanner/apm_planner_version.json" 
DEBUG 2015-05-18T00:41:53.580 Downloading: 2780 / 2780 
DEBUG 2015-05-18T00:41:53.580 Downloading: 2780 / 2780 
DEBUG 2015-05-18T00:41:53.581 AutoUpdateCheck::httpFinished() 
DEBUG 2015-05-18T00:42:01.045 Dronshare: remind later

**Comment by vooon** [comment]
Mavros desined to be just a bridge for FCU-ROS, not ROS-GCS. For GCS they provide transparent proxy, so it acts like direct FCU-GCS connection.
GCS messages even not passed to plugin system, and i don't want to change that (there lots of error prone).

So it you want to communicate ROS-GCS you should implement ROS node that mimic to FCU.
Mavros here not fit, but it's part **libmavconn** may be used.
As example you can look at [PX4 SITL mavlink node][1].

Other strategy may be used if you want to use real FCU (e.g. pixhawk) but react to few commands from GCS in ROS.
You may write your own **gcs_bridge** node with handling of that messages.
Look at [gcs_image_bridge.cpp][2].

[1]: https://github.com/PX4/Firmware/blob/master/src/platforms/ros/nodes/mavlink/mavlink.cpp
[2]: https://github.com/mavlink/mavros/blob/master/mavros_extras/src/gcs_image_bridge.cpp

**Comment by MauroPagliarella** [comment]
I don't use an FCU. 
I control my robot by ROS (running on board), and I need to send some control commands to the robot from a ground control station. Moreover, I would like to receive robot telemetries (imu, encoder, gps etc.), by means of a control application running on a laptop,  so I thought to use for this purpose the GCS.  
I'll check the links in your answer.

Thank you very much for the clarification. 
Bye

**Comment by vooon** [comment]
Updates?

**Comment by MauroPagliarella** [comment]
I decided not to use the APM GCS, and developed a custom ground control station based on two tcp-ip links toward ROS. One link for TM messages and the other to send telecommands to my robot.
I created a ros-qt package, using the cmd "catkin_create_qt_package" and developed my ground control station using Qt 5.
At the moment it doesn't work very well. The TM messages, generated by my robot and sent to my ground control station, using the tcp-ip telemetry link, seem correctly sent (there is no telemetry packet lost), but the packet transmission appens at a rate minor w.r.t the rate of the packet generation. (The rate of the tm packet generation is 1pkt/sec while the rate of the received pkts is 1 packet every 2 seconds). Probably the tcp-ip socket accumulates the packets and sent them slowly. Now I'm investigating on this aspect. 

Do you have  any idea on the possible solutions?

Thank you very much
Mauro Pagliarella

**Comment by vooon** [comment]
Use UDP, it is better for telemetry, but lossy.
But if you have IP telemetry, why not simply write RQT plugin (like dashboard) and connect to robot's roscore?
Than much simpler than reinventing protocol and write support nodes.

Anyway now it offtopic for mavros, so i close this issue.

**Comment by MauroPagliarella** [comment]
I don't want to lose packets.
RQT seems to need ROS, and I would like to develop a ground control station running on a system without ros, e.g a tablet. 

I agree with you, my problem is not related to mavros, this issue can be closed.

Thank you for your help
Mauro

**Comment by vooon** [comment]
@AfshinMr what are you described is not transparent, as you want to modify messages coming trough proxy.
Mavros have build-in proxy that can be enabled by `gcs_url` parameter.
But to be able to modify messages it's easier to write your proxy that will decode and reencode messages back to mavlink stream.
I think that it should be relatively easy with pymavlink.

**Comment by AfshinMr** [comment]
@vooon Thank you for your answer. In fact, I need to modify the messages if they are way-points or pass them without modification if they are not way-points.
can you give me a hint or any source code to do with pymavlink? or the steps I need to follow?
I appreciate it.

**Comment by vooon** [comment]
@AfshinMr i don't have code, but what are you need is following

1. create 2 mavlink interfaces, one for FCU side and another on GCS
2. Check MSGID and if that is not `MISSION_*` pass from one link to another
3. In case of MISSION_* do whatever you want.

**Comment by AfshinMr** [comment]
@vooon Thank you again for your answer.  I try to do that.

**Comment by AfshinMr** [comment]
@vooon  Sorry Vladimir, I am completely confused when I tried to implement what you described. could you explain me in more details? I need to create an interface which listens to the GCS? Do I need to use a GCS like QGCS to send MAVLINK messages? if yes, How to connect them?
or I need to just create a MAVLINK message simulator to send the messages to the created interface?
I need another interface in FCU side to send te modified messages to the FCU. How to connect the two interfaces? I mean how to connect the interface in FCU side and the interface in GCS side? 
I am not sure if I got your description right ? Please explain in more details. I really appreciate your help.

**Comment by vooon** [comment]
@AfshinMr i mean that you need instance that operate with udp/tcp/serial and parse and send messages.
I don't remember API of pymavlink, on libmavconn that will look like following (pseudocode):
```cpp

auto fcu_link = MAVConnInterface::open_url("serial:///dev/ttyACM0:57600");
auto gcs_link = MAVConnInterface::open_url("udp://localhost:14555@localhost:14550");

fcu_link->message_received_cb = [gcs_link] (const mavlink::mavlink_message_t *msg, const Framing framing) {
    gcs_link->send_message(msg);
};

gcs_link->message_received_cb = [fcu_link] (const mavlink::mavlink_message_t *msg, const Framing framing) {
    if (msg->msgid == OUR_MSGID) {
        DO_SOMETHING(msg);
        return;
    }
    // forward original message
    fcu_link->send_message(msg);
}
```

**Comment by AfshinMr** [comment]
Thank you very much @vooon , appreciate your help. I try that :-)

**Comment by AfshinMr** [comment]
Hi @vooon , 
I have created the interfaces as you described to me in Python. Here is the code:

          `gcs_conn = mavutil.mavlink_connection('tcpin:localhost:15795')
           gcs_conn.wait_heartbeat()
           print("Heartbeat from system (system %u component %u)" % (gcs_conn.target_system, gcs_conn.target_system))
           vehicle = mavutil.mavlink_connection('tcp:localhost:5760')
           vehicle.wait_heartbeat() # recieving heartbeat from the vehicle
           print("Heartbeat from system (system %u component %u)" % (vehicle.target_system, vehicle.target_system))
           while True:
                     gcs_msg = gcs_conn.recv_match()
                     if gcs_msg == None:
                            pass
                     else:
                            vehicle.mav.send(gcs_msg)
                            print(gcs_msg)

                     vcl_msg = vehicle.recv_match()
                     if vcl_msg == None:
                            pass
                     else:
                            gcs_conn.mav.send(vcl_msg)
                            print(vcl_msg)
`

First, Here I just want to receive and forward the messages !(without modification)
But, I still cannot send the messages from vehicle to the QGC ! and QGC does not recognize the vehicle !
Here is what I see when I run the code:
![selection_005](https://user-images.githubusercontent.com/42065599/48776813-1cc82980-ecd1-11e8-9db1-2758e7af8f8c.png)

**Comment by vooon** [comment]
I don't know, i don't use pymavlink for most time. Maybe you can find some hints in mavproxy, it's very powerful.

**Comment by AfshinMr** [comment]
@vooon  Thank you for your response. You mean, I can use MAVProxy as a proxy that I explained for you?

**Comment by vooon** [comment]
I don't know how hard it will be to add code to modify messages.
But it can be used as a good example on how to forward messages in pymavlink.
