### ISSUE TITLE
Add support for `VIBRATION` msg

### ISSUE THREAD

**Issue by TSC21** [mavlink/mavros#308]
It's usage on firmware will be applied on the next weeks, according to: https://github.com/mavlink/mavlink/pull/398. In the meantime, I think I can add a decoder to it.

**Comment by TSC21** [comment]
@vooon can you update mavlink release so this can compile?

**Comment by vooon** [comment]
What FCU will support that? I can release, but there only 6 days from last one...

**Comment by TSC21** [comment]
Both!  Please send it so I can test compilation

**Comment by vooon** [comment]
Releasing....

**Comment by TSC21** [comment]
>Releasing....

How can one update it now?

**Comment by vooon** [comment]
- https://github.com/ros/rosdistro/pull/8664
- https://github.com/ros/rosdistro/pull/8665
- https://github.com/ros/rosdistro/pull/8667

**Comment by TSC21** [comment]
Ok I'll be waiting for those to get merged then :)

**Comment by TSC21** [comment]
@vooon changes were merged but how can I update mavlink version now?

**Comment by TSC21** [comment]
Closed via https://github.com/mavlink/mavros/pull/309
