### ISSUE TITLE
Transfer math to Eigen

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#319]
We already have some matrix math done by hand and TF bullet.
Also other dev's use Eigen with TF2, so seems that it required for #71.

TODO:
- [x] imu_pub
- [x] global_position
- [x] local_position
- [x] safety_area
- [x] setpoint_accel
- [x] setpoint_attitude
- [x] setpoint_position
- [x] setpoint_velocity
- [x] mocap_pose_estimate
- [x] px4flow
- [x] vision_pose_estimate
- [x] vision_speed_estimate
- [x] visualization
- [x] UAS class

**Comment by TSC21** [comment]
:+1: finally! Just let me know what's needed.

**Comment by vooon** [comment]
Ok, all code without tf listener are moved.
Exception is visualization because #336.

**Comment by vooon** [comment]
Ok, #71 now closed. So most of tf::Vector3 and tf::Quaternion are gone.

But i find strange code at distance_sensor, @TSC21 how RPY-Q may work if you give degrees to that function?
It wants radians. I think to refactor orientation enum.
I don't see where really may be needed euler angles (in degrees), while quaternions may be useful.
(even in your code - *single usage of method* - converts to q).
