### ISSUE TITLE
Merge gps and global_position plugins

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#325]
I think we may merge that plugins, because their output needed for one purpose: provide global position data.

**Comment by TSC21** [comment]
Seems good. Assign that task to me, if you may

**Comment by vooon** [comment]
First we need to discus proposal.

**Comment by TSC21** [comment]
What do you have in mind?

**Comment by vooon** [comment]
Past versions of APM don't send fused global position, so for that old firmwares blacklisting global_position may save little ram.
But those plugins are coupled, because gp can't properly work without gps.

So in one hand i have splitted raw and fused data and possibility to disable fused part
and in other e.g. apm antenna tracker uses only fused coordinates.

**Comment by TSC21** [comment]
You can use `#if #endif` clauses depending on the autopilot. So then you can keep the plugin active. What do you think?

**Comment by vooon** [comment]
Compile time option not useful, ros buildfarm cant produce several packages with different compile time options.

Currently ros binaries uses APM's dialect, but because almost all used messages exists in common PX4 don't require special binary.

**Comment by TSC21** [comment]
So we can add a parameter `is_raw`, which when set publishes on raw gps, but when not set publishes filtered position.

**Comment by vooon** [comment]
No, stream raw and fused, just like imu_pub.

**Comment by TSC21** [comment]
At the same time but for different topics, right? Seems legit then.

**Comment by vooon** [comment]
Merge is done. GPS raw topics now in `~global_position/raw`, and we moved to TF2.
Also parameters changed, tf things moved to `tf` subnamespace.
