### ISSUE TITLE
Does Mavros provide the current roll, pitch and yaw data from the APM?

### ISSUE THREAD

**Issue by Tomofoye** [mavlink/mavros#329]
Sorry if this is too simple a question, I'm still getting used ROS and C++. I'm trying to write code that will display the current roll, pitch and yaw of the quad, and I'm wondering which header to include.

**Comment by vooon** [comment]
That data provided via `imu_pub` plugin.
It is use `sensor_msgs/Imu`, so attitude stored in quaternion.

For visualization you may use [rviz_imu_plugin](https://github.com/ccny-ros-pkg/imu_tools.git).

**Comment by LorenzMeier** [comment]
Closing, since question.
