### ISSUE TITLE
Add topics for orientation control setpoint.

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#33]

**Comment by mhkabir** [comment]
@vooon This works fine, as tested by users.

**Comment by vooon** [comment]
@mhkabir Yeah, but @TSC21 some time ago wanted to keep issue opened for discussion.
Maybe now we can close?

**Comment by TSC21** [comment]
Can close now. Doing some restruct on my linux machine now. Will be back at the project soon ;)
