### ISSUE TITLE
undefined symbol: _ZN3ros8DurationC1ERKNS_4RateE

### ISSUE THREAD

**Issue by jabberwack** [mavlink/mavros#330]
Hello. I'm new to mavros and I'm getting this error whenever I launch the node.

/home/odroid/catkin_ws/devel/lib/mavros/mavros_node: symbol lookup error: /home/odroid/catkin_ws/devel/lib//libmavros_plugins.so: undefined symbol: _ZN3ros8DurationC1ERKNS_4RateE

can anyone help?

I installed mavros from source.

Thank you.

**Comment by TSC21** [comment]
That's because mavros lib is not being linked. Please delete `devel` and `build` folders from your `catlin_ws`, delete CMakeList file on your src folder, do `catkin_init_workspace` on it again then do `catkin_make` on home folder of your workspace.

**Comment by TSC21** [comment]
Also make sure you have all dependencies installed. Did you followed the instructions from https://github.com/mavlink/mavros/blob/master/mavros/README.md?

**Comment by TSC21** [comment]
I advise to also use `catkin_tools` if you are using Jade. You can installed it on Indigo following http://catkin-tools.readthedocs.org/en/latest/installing.html. Much more versatile.

**Comment by vooon** [comment]
What version of ROS do you use?

**Comment by jabberwack** [comment]
Hello guys. Thnx for the help. Really appreciate it.

@TSC21 I tries deleteing devel and build folders as you said but launching the px4.launch just gives me the same error.
Something might have gone wrong when I removed the apt-get version of the MAVROS and re-compiled it from the source.
I'm thinking about just starting from scratch.

@vooon I'm using Indigo.

Thank you.

**Comment by jabberwack** [comment]
Hey guys.

So I installed everything again and I'm still getting the exact same error.

/home/odroid/catkin_ws/devel/lib/mavros/mavros_node: symbol lookup error: /home/odroid/catkin_ws/devel/lib//libmavros_plugins.so: undefined symbol: _ZN3ros8DurationC1ERKNS_4RateE

The px4flow.launch of mavros_extras works fine.

Btw, I installed mavlink from source code that I got from mavlink-gbp-release.
The apt-get version was giving me error about 'MAV_SENSOR_ORIENTATION has not been declared.'

**Comment by vooon** [comment]
Use mavlink from [shadow repo][1], main repo not updated yet (also note that next release tomorrow).

`_ZN3ros8DurationC1ERKNS_4RateE` it is not mavros or mavlink part, it is ROS part.
Strange that i can't find that definition in my Jade installation (while libmavros_plugins.so has it).

[1]: http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/r/ros-indigo-mavlink/

**Comment by vooon** [comment]
Just to point: i think it is constructor for `ros::Duration(ros::Rate)`.

**Comment by vooon** [comment]
Hmm, related: https://github.com/ros/roscpp_core/issues/30
https://github.com/ros/roscpp_core/commit/26e74bcbc759f4c7a78b7f12a2f66068140fc063

**Comment by vooon** [comment]
Ok, `/opt/ros` binaries stripped, so no symbols available.
I done `wstool set roscpp_core --git https://github.com/ros/roscpp_core.git -v indigo-devel` and then `catkin build`.

Then:
```
vovan@robert:~/ros/src$ objdump -x ../devel/lib/librostime.so | grep _ZN3ros8DurationC1ERKNS_4RateE
000000000002e1d0 g     F .text	00000000000000bc              _ZN3ros8DurationC1ERKNS_4RateE
```

**Comment by jabberwack** [comment]
@vooon  Ok. Fixed the problem by reinstalling the roscpp_core.

Thank you so much.

**Comment by archenroot** [comment]
ufff, this also was causing issues with different package, but finally, I just used different term => environment.
