### ISSUE TITLE
Mavros not Publishing

### ISSUE THREAD

**Issue by TempleWaterfOWLS** [mavlink/mavros#335]
I just put the erle-debian-flash-25-4-15.img.gz image on the BeagleBone Black. I'm looking to use APMrover2 so I made it and I got mavros to run. But when I go to $rostopic echo any of the mavros topics.

Here a list of warnings that I got before I killed the copter startup script:
```g
[ERROR] [1436391593.335363009]: FCU: Initialising APM...
[ INFO] [1436391593.340575093]: CON: Got HEARTBEAT, connected.
[ WARN] [1436391604.347705136]: PR: request list timeout, retries left 2
[ WARN] [1436391604.418798427]: VER: request timeout, retries left 1
[ WARN] [1436391605.429735969]: PR: request list timeout, retries left 1
[ WARN] [1436391606.433376094]: PR: request list timeout, retries left 0
[ WARN] [1436391609.347714761]: WP: timeout, retries left 2
[ WARN] [1436391609.539454844]: VER: request timeout, retries left 0
[ WARN] [1436391610.360942761]: WP: timeout, retries left 1
[ WARN] [1436391611.367641220]: WP: timeout, retries left 0
[ERROR] [1436391612.434586345]: WP: timed out.
[ WARN] [1436391614.562060803]: VER: your FCU don't support AUTOPILOT_VERSION, switched to default capabilities
[ WARN] [1436391623.347379429]: CON: Lost connection, HEARTBEAT timed out.
```

Here's the last output of mavros after I killed the copter startup script:
```k
[ INFO] [1436391732.854899901]: Built-in mavlink dialect: ardupilotmega
[ INFO] [1436391732.857788109]: MAVROS started. MY ID [1, 240], TARGET ID [1, 1]
```

@vmayoral any ideas?

**Comment by TempleWaterfOWLS** [comment]
Going to add @vooon to this as well

**Comment by vooon** [comment]
I need:
1. `/diagnostics`
2. which launch script do you use, and parameters
3. full mavros log output

**Comment by vooon** [comment]
Now only what i can say, that you have bad link.

**Comment by TSC21** [comment]
@TempleWaterfOWLS any updates on this?

**Comment by CrazyPopLin** [comment]
Hi, I reinstalled **mavlink 11.25** and **mavros 0.16** from source in odroid xu4 which installed ros indigo and build successfully. I am using pixhawk with apm stack.
But when I launch the apm.launch, the **HEARTBEAT** connected first and time out. Like each time I reboot odroid board, it connect and time out. Restart pixhawk won't connect at all. Also I try to update the apm firmware to 3.3.2, that didn't change anything. 
Before I update the mavlink and mavros, everything works fine. 
Is that problem of installation of mavlink?

**PARAMETERS**
>
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 10.0
 * /mavros/conn/system_time_rate: 0.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 0.0
 * /mavros/fcu_url: /dev/ttyUSB0:57600
 * /mavros/gcs_url: 
 * /mavros/global_position/frame_id: fcu
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: fcu_utm
 * /mavros/global_position/tf/frame_id: local_origin
 * /mavros/global_position/tf/send: False
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: fcu
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: fcu
 * /mavros/local_position/tf/child_frame_id: fcu
 * /mavros/local_position/tf/frame_id: local_origin
 * /mavros/local_position/tf/send: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/plugin_blacklist: ['actuator_contro...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.0
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_throttle: False
 * /mavros/setpoint_attitude/tf/child_frame_id: attitude
 * /mavros/setpoint_attitude/tf/frame_id: local_origin
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 10.0
 * /mavros/setpoint_position/tf/child_frame_id: setpoint
 * /mavros/setpoint_position/tf/frame_id: local_origin
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/startup_px4_usb_quirk: False
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/vibration/frame_id: vibration
 * /mavros/vision_pose/tf/child_frame_id: vision
 * /mavros/vision_pose/tf/frame_id: local_origin
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: indigo
 * /rosversion: 1.11.16
>

**Mavros logout:**
>NODES
  /
    mavros (mavros/mavros_node)
>
auto-starting new master
process[master]: started with pid [1862]
ROS_MASTER_URI=http://localhost:11311
>
setting /run_id to 7b95d214-9cca-11e5-9607-7cdd908e11ff
process[rosout-1]: started with pid [1875]
started core service [/rosout]
process[mavros-2]: started with pid [1879]
[ INFO] [1449482919.671572938]: FCU URL: /dev/ttyUSB0:57600
[ INFO] [1449482919.674878665]: serial0: device: /dev/ttyUSB0 @ 57600 bps
[ INFO] [1449482919.680454834]: GCS bridge disabled
[ INFO] [1449482919.970373934]: Plugin 3dr_radio loaded and initialized
[ INFO] [1449482919.971102346]: Plugin actuator_control blacklisted
[ INFO] [1449482920.555700928]: Plugin cam_imu_sync loaded and initialized
[ INFO] [1449482920.596640851]: Plugin command loaded and initialized
[ INFO] [1449482920.597011140]: Plugin distance_sensor blacklisted
[ INFO] [1449482920.597108681]: Plugin ftp blacklisted
[ INFO] [1449482920.672027241]: Plugin global_position loaded and initialized
[ INFO] [1449482920.672509571]: Plugin image_pub blacklisted
[ INFO] [1449482920.733973725]: Plugin imu_pub loaded and initialized
[ INFO] [1449482920.776967466]: Plugin local_position loaded and initialized
[ INFO] [1449482920.781619183]: Plugin manual_control loaded and initialized
[ INFO] [1449482920.781925015]: Plugin mocap_pose_estimate blacklisted
[ INFO] [1449482920.799403434]: Plugin param loaded and initialized
[ INFO] [1449482920.799684307]: Plugin px4flow blacklisted
[ INFO] [1449482920.826109414]: Plugin rc_io loaded and initialized
[ INFO] [1449482920.826419829]: Plugin safety_area blacklisted
[ INFO] [1449482920.857152989]: Plugin setpoint_accel loaded and initialized
[ INFO] [1449482920.857422362]: Plugin setpoint_attitude blacklisted
[ INFO] [1449482920.898555408]: Plugin setpoint_position loaded and initialized
[ INFO] [1449482920.970327323]: Plugin setpoint_raw loaded and initialized
[ INFO] [1449482920.989817104]: Plugin setpoint_velocity loaded and initialized
[ INFO] [1449482921.029916532]: Plugin sys_status loaded and initialized
[ INFO] [1449482921.050486680]: CON: Got HEARTBEAT, connected.
[ INFO] [1449482921.059952364]: Plugin sys_time loaded and initialized
[ INFO] [1449482921.075600630]: Plugin vfr_hud loaded and initialized
[ INFO] [1449482921.076488540]: Plugin vibration blacklisted
[ INFO] [1449482921.076833329]: Plugin vision_pose_estimate blacklisted
[ INFO] [1449482921.077184160]: Plugin vision_speed_estimate blacklisted
[ INFO] [1449482921.132539690]: Plugin waypoint loaded and initialized
[ INFO] [1449482921.133691515]: Built-in SIMD instructions: None
[ INFO] [1449482921.134237970]: Built-in MAVLink dialect: ardupilotmega
[ INFO] [1449482921.134731342]: MAVROS started. MY ID [1, 240], TARGET ID [1, 1]
[ INFO] [1449482922.122815897]: VER: 1.1: Capabilities 0x0000000000000b83
[ INFO] [1449482922.125493670]: VER: 1.1: Flight software:     030302ff (7f16e4d634e1d5437c5ef883?)
[ INFO] [1449482922.129432351]: VER: 1.1: Middleware software: 00000000 (34e1d5437c5ef883?)
[ INFO] [1449482922.131351004]: VER: 1.1: OS software:         00000000 (7c5ef883?)
[ INFO] [1449482922.133459323]: VER: 1.1: Board hardware:      00000000
[ INFO] [1449482922.135363518]: VER: 1.1: VID/PID: 0000:0000
[ INFO] [1449482922.138105165]: VER: 1.1: UID: 0000000000000000
[ WARN] [1449482922.143073131]: CMD: Unexpected command 520, result 0
 **_[ERROR] [1449482931.085932448]: FCU: APM:Copter V3.3.2 (7f16e4d6)_**
 **_[ERROR] [1449482931.090064794]: FCU: PX4: 34e1d543 NuttX: 7c5ef883_**
 **_[ERROR] [1449482931.095757005]: FCU: Frame: QUAD_**
 **_[ERROR] [1449482931.104878566]: FCU: PX4v2 004B0036 30345106 36353832_**
[ INFO] [1449482941.144363806]: PR: parameters list received
[ WARN] [1449483000.296174701]: CON: Lost connection, HEARTBEAT timed out.
>
Also I noticed some FCU info are red and error, that's wired.

**/diagnostics**
>
header: 
  seq: 108
  stamp: 
    secs: 1449483062
    nsecs: 636493655
  frame_id: ''
status: 
  - 
    level: 1
    name: mavros: FCU connection
    message: not connected
    hardware_id: /dev/ttyUSB0:57600
    values: 
      - 
        key: Received packets:
        value: 724
      - 
        key: Dropped packets:
        value: 0
      - 
        key: Buffer overruns:
        value: 0
      - 
        key: Parse errors:
        value: 0
      - 
        key: Rx sequence number:
        value: 198
      - 
        key: Tx sequence number:
        value: 139
      - 
        key: Rx total bytes:
        value: 20968
      - 
        key: Tx total bytes:
        value: 24137
      - 
        key: Rx speed:
        value: 0.000000
      - 
        key: Tx speed:
        value: 255.000000
  - 
    level: 2
    name: mavros: GPS
    message: No satellites
    hardware_id: /dev/ttyUSB0:57600
    values: 
      - 
        key: Satellites visible
        value: 0
      - 
        key: Fix type
        value: 0
      - 
        key: EPH (m)
        value: Unknown
      - 
        key: EPV (m)
        value: Unknown
  - 
    level: 2
    name: mavros: Heartbeat
    message: No events recorded.
    hardware_id: /dev/ttyUSB0:57600
    values: 
      - 
        key: Heartbeats since startup
        value: 70
      - 
        key: Frequency (Hz)
        value: 0.000000
      - 
        key: Vehicle type
        value: Quadrotor
      - 
        key: Autopilot type
        value: ArduPilotMega
      - 
        key: Mode
        value: STABILIZE
      - 
        key: System status
        value: Standby
  - 
    level: 0
    name: mavros: System
    message: Normal
    hardware_id: /dev/ttyUSB0:57600
    values: 
      - 
        key: Sensor present
        value: 0x00000000
      - 
        key: Sensor enabled
        value: 0x00000000
      - 
        key: Sensor helth
        value: 0x00000000
      - 
        key: CPU Load (%)
        value: 0.0
      - 
        key: Drop rate (%)
        value: 0.0
      - 
        key: Errors comm
        value: 0
      - 
        key: Errors count #1
        value: 0
      - 
        key: Errors count #2
        value: 0
      - 
        key: Errors count #3
        value: 0
      - 
        key: Errors count #4
        value: 0
  - 
    level: 2
    name: mavros: Battery
    message: No data
    hardware_id: /dev/ttyUSB0:57600
    values: 
      - 
        key: Voltage
        value: -1.00
      - 
        key: Current
        value: 0.0
      - 
        key: Remaining
        value: 0.0
---
>

**/mavros/state**
>
header: 
  seq: 71
  stamp: 
    secs: 1449483000
    nsecs: 298424602
  frame_id: ''
connected: False
armed: False
guided: False
mode: ''
>

Thanks for your help.

**Comment by vooon** [comment]
Try to increase connection timeout.

---
```
[ INFO] [1449482921.050486680]: CON: Got HEARTBEAT, connected.
...
[ WARN] [1449483000.296174701]: CON: Lost connection, HEARTBEAT timed out.
```

Strange: you got 79 second timeout. Default apm_config.yaml is 10.

---
Nope: something strange: we got 70 HEARTBEAT's (1 Hz), then APM stops talking, +10 sec -> disconnect.

**Comment by CrazyPopLin** [comment]
Yes, the default is 1HZ, then I change to 10 Hz want to fix the problem.
What is **increase connection timeout** means?

**Comment by vooon** [comment]
Timeout param from apm_config.yaml. But it is not hope. APM just shuts telemetry down - i do not see repeated *connected* messages.

You tried to use USB port? Just to ensure that problem is in TELEM2 operation.

**Comment by CrazyPopLin** [comment]
yes, I am using USB FDTI cable connect pihxaw(TELEM2) to odroid, the same cable I used before which works fine.

**Comment by vooon** [comment]
I mean pixhawk's side microUSB.

**Comment by CrazyPopLin** [comment]
no

**Comment by CrazyPopLin** [comment]
quick question, why `/mavros/local_position/pose ` didn't publish, do i need to setup something?

**Comment by killerlayup** [comment]
@CrazyPopLin  I have the same issue, `/mavros/local_position/pose` didn't publish, have you solved this issue?
