### ISSUE TITLE
use of plugin actuator_control

### ISSUE THREAD

**Issue by congleetea** [mavlink/mavros#350]
Hi, 
     i want write a controller in the computer to control the mav to fly a trajectory, in my controller, I can compute the thrust(Newton) and moments(for roll, pitch and yaw), most of these value are beyond range [0,1] or [-1,1] , but in the pixhawk firmware mc_pos_control app and mc_att_control app, thrust_sp is limited to [0,1], _actuators.control[0]~_actuators.control[2] alse have familiar limitation. 
   can someone tell me what should i compute the data of actuator_control or there are other way to do it. thanks very much.

**Comment by TSC21** [comment]
This is out of scope of mavros issues or code. Please use the forums/gitter to discuss this.
