### ISSUE TITLE
mavros/vision_pose/pose doesn't accept PoseWithCovarianceStamped anymore

### ISSUE THREAD

**Issue by MarcGyongyosi** [mavlink/mavros#362]
Hi,

I updated mavros today in the morning. Now I am getting an error because the vision plugin is expecting a pose stamped although I set pose_with_covariance to true.... 

![screen shot 2015-08-05 at 2 50 56 pm](https://cloud.githubusercontent.com/assets/7433584/9086104/7e2963e6-3b82-11e5-8fd5-39515db26994.png)
![screen shot 2015-08-05 at 2 51 04 pm](https://cloud.githubusercontent.com/assets/7433584/9086106/80975c14-3b82-11e5-888a-979d83b0c7f8.png)

What exactly do I need to change to make this work again?

Thanks,
Marc

**Comment by MarcGyongyosi** [comment]
Just found this: https://github.com/mavlink/mavros/commit/f22ab3bfc9467965e9e9113a3ecc868e47d93fce why did you guys take out the covariance listener?

**Comment by vooon** [comment]
Just to reduce support complexity. Anyway covariance not used.

**Comment by mhkabir** [comment]
We will "upgrade" to PoseWithCovariance when we support the mavlink messages with covariance.

**Comment by MarcGyongyosi** [comment]
That's two different answers... And tbh I don't see how removing one callback for a topic that's used in wikis removes support complexity. After all you will have people following the MSF tutorial and then end up running into the same issue. But anyways, I added the callback again in my mavros copy and now it works again.
