### ISSUE TITLE
RcIn message is periodically empty

### ISSUE THREAD

**Issue by v01d** [mavlink/mavros#381]
The "channels" fields is most of the time populated with channel values, but about once or twice per second it is empty. I'm using turnigy 9x receiver with PPM encoder. On QGC it does not seem that RC is lost.

**Comment by vooon** [comment]
Perhaps firmware send empty [RC_CHANNELS][1] message (chancount=0)

[1]: https://pixhawk.ethz.ch/mavlink/#RC_CHANNELS

**Comment by v01d** [comment]
I was also wondering if it is a response to noise. Sounds reasonable.
Strange thing is that if I turn off transmitter the behavior does not
change (I read noise, of course).
But I guess that for another receiver which is able to inform of actual
link loss might not do this.

If you feel this is expected, then, feel free to close it.

**Comment by vooon** [comment]
I'm not sure that is what expected, but that it works now. If rc subsystem lost link it changes channel count to 0.
Perhaps you have unreliable connections or high-amp wires near PPM.

**Comment by v01d** [comment]
Ok, I will check it. Thanks

**Comment by v01d** [comment]
This ended up being a hardware problem, not having sufficient current when just powering the autopilot + receiver using from USB.
