### ISSUE TITLE
[setpoint_attitude] Don't work with APM

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#396]
For now this issue is a note to remember.

APM implementation PR: https://github.com/diydrones/ardupilot/pull/2959

**Comment by vooon** [comment]
Possible way to solve this is to use Message Filters to syncronize two subscribers and construct one SET_ATTITUDE_TARGET with quaternion and thrust.

**Comment by CrazyPopLin** [comment]
hi @vooon ，does the setpoint works with APM right now. Thanks.

**Comment by vooon** [comment]
Attitude - nope.

**Comment by TSC21** [comment]
Closing this as this in not MAVROS related.

**Comment by TSC21** [comment]
Closing as solved. APM supports attitude setpoints now. Just use `setpoint_raw` plugin while https://github.com/mavlink/mavros/pull/700 is not merged.
