### ISSUE TITLE
how to hold the MAV altitude by mavros

### ISSUE THREAD

**Issue by suimo** [mavlink/mavros#400]
now I use odroid xu3 to control pixhawk by mavros,I can arm the MAV and make it takeoff by giving the setpoint of throttle.but I can't hold the altitude ,when I change the flight mode from offboard to ALTCTL ,the failsafe mode is on,and the flight mode change to auto-land not altctl mode .I don't know why.
please who can help me with this issue? thanks a lot!

**Comment by vooon** [comment]
What FCU do you use? What version of firmware? How OBC connected to FCU?

**Comment by suimo** [comment]
@vooon hi,I use pixhawk with px4 firmware. and I use odroid to control pixhawk via the TELEM2 port,could you give me some help about this?

**Comment by vooon** [comment]
What you trying to do?

If you want to use OFFBOARD for whole flight control, then simply send position setpoint with same altitude.
If you only needs automatic takeoff/land use `~cmd/takeoff` services (see documentation).

**Comment by suimo** [comment]
Dear,vooon!  Thank you so much for your reply,I just want to use offboard to send position setpoint,and make the MAV takeoff and hold the position  automaticly, now I just want to use px4flow to implement this goal, but there are some issues during  parameter tuning ,could you give me some help?

**Comment by mhkabir** [comment]
@suimo Please refer to the PX4 wiki/mailing list for more help. See README.

**Comment by chenshiyuhit** [comment]
@suimo  Hi,I also use Odroid XU3 to connect to the piahawk, but I can not set the mode to OFFBOARD mode, I don't know why?
My pixhawk firmware may be not the latest, because this?

**Comment by suimo** [comment]
@chenshiyuhit hi，I think you can refer to this page  http://pixhawk.org/dev/ros/mavros_offboard
