### ISSUE TITLE
/imu/data publishes at 2 Hz?

### ISSUE THREAD

**Issue by saihv** [mavlink/mavros#401]
All of my previous tests with mavros had the imu data coming in at ~ 90 Hz, but recently I have noticed it drop to 2 Hz (I am using a Pixhawk with ArduCopter 3.3). Is this an issue with the firmware, or has there been a config change somewhere in mavros?

**Comment by vooon** [comment]
I think you configured rates in params for higher rate.
Anyway you might to require stream groups using `mavsys rate`.

**Comment by vooon** [comment]
Duplicate #397
