### ISSUE TITLE
Errors are reported duing my installation, anyone could help? Thanks a lot

### ISSUE THREAD

**Issue by peilibuaa** [mavlink/mavros#405]
Some problems come out when I try to build and install this tool with the following codes
And i make no change to the source code.
"""
wstool init src # (if not already initialized)
wstool set -t src mavros --git https://github.com/mavlink/mavros.git
wstool update -t src
rosdep install --from-paths src --ignore-src --rosdistro indigo -y
catkin_make
"""
I'm not familiar with this package. Anyone could help me to sovle this problem?
![error](https://cloud.githubusercontent.com/assets/13134399/10663376/82c7f590-78ed-11e5-9572-6a72f0143687.png)

**Comment by vooon** [comment]
Update mavlink package from shadow-fixed repo:
- http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/r/ros-indigo-mavlink/
- http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/r/ros-jade-mavlink/

**Comment by vooon** [comment]
Ping.
