### ISSUE TITLE
can't arm the pixhawk installed APM through Mavros

### ISSUE THREAD

**Issue by CrazyPopLin** [mavlink/mavros#408]
Hi, I using pixhawk installed APM 3.2.1 which connected Odroid through telem2 with FDTI cable according the [tutorial](https://pixhawk.org/dev/companion_link).
Then I use `roslaunch mavros apm.launch` , get the **SUMMARY**
` 
 > CLEAR PARAMETERS
 >  * /mavros/

> PARAMETERS
> * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 0.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 0.0
 * /mavros/fcu_url: /dev/ttyUSB0:115200
 * /mavros/gcs_url: 
 * /mavros/global_position/frame_id: fcu
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: fcu_utm
 * /mavros/global_position/tf/frame_id: local_origin
 * /mavros/global_position/tf/send: False
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: fcu
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: fcu
 * /mavros/local_position/tf/child_frame_id: fcu
 * /mavros/local_position/tf/frame_id: local_origin
 * /mavros/local_position/tf/send: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/plugin_blacklist: ['actuator_contro...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.0
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_throttle: False
 * /mavros/setpoint_attitude/tf/child_frame_id: attitude
 * /mavros/setpoint_attitude/tf/frame_id: local_origin
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 10.0
 * /mavros/setpoint_position/tf/child_frame_id: setpoint
 * /mavros/setpoint_position/tf/frame_id: local_origin
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/startup_px4_usb_quirk: False
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/vibration/frame_id: vibration
 * /mavros/vision_pose/tf/child_frame_id: vision
 * /mavros/vision_pose/tf/frame_id: local_origin
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: indigo
 * /rosversion: 1.11.13

>NODES
> /
>   mavros (mavros/mavros_node)
>
>ROS_MASTER_URI=http://localhost:11311
>
>core service [/rosout] found
>process[mavros-1]: started with pid [6933]
[ INFO] [1445931894.270784606]: FCU URL: /dev/ttyUSB0:115200
[ INFO] [1445931894.271501564]: serial0: device: /dev/ttyUSB0 @ 115200 bps
[ INFO] [1445931894.275478231]: GCS bridge disabled
[ INFO] [1445931894.456389481]: Plugin 3dr_radio loaded and initialized
[ INFO] [1445931894.456713689]: Plugin actuator_control blacklisted
[ INFO] [1445931894.505642189]: Plugin command loaded and initialized
[ INFO] [1445931894.505804522]: Plugin ftp blacklisted
[ INFO] [1445931894.549754939]: Plugin global_position loaded and initialized
[ INFO] [1445931894.581239022]: Plugin imu_pub loaded and initialized
[ INFO] [1445931894.596881272]: Plugin local_position loaded and initialized
[ INFO] [1445931894.607362022]: Plugin param loaded and initialized
[ INFO] [1445931894.623299689]: Plugin rc_io loaded and initialized
[ INFO] [1445931894.623452814]: Plugin safety_area blacklisted
[ INFO] [1445931894.647036064]: Plugin setpoint_accel loaded and initialized
[ INFO] [1445931894.647193981]: Plugin setpoint_attitude blacklisted
[ INFO] [1445931894.679802481]: Plugin setpoint_position loaded and initialized
[ INFO] [1445931894.690673189]: Plugin setpoint_velocity loaded and initialized
[ INFO] [1445931894.713947231]: Plugin sys_status loaded and initialized
[ INFO] [1445931894.743329272]: Plugin sys_time loaded and initialized
[ INFO] [1445931894.750769481]: Plugin vfr_hud loaded and initialized
[ INFO] [1445931894.778813772]: Plugin waypoint loaded and initialized
[ INFO] [1445931894.779099356]: Built-in mavlink dialect: ardupilotmega
[ INFO] [1445931894.779275189]: MAVROS started. MY ID [1, 240], TARGET ID [1, 1]
[ INFO] [1445931895.673222939]: CON: Got HEARTBEAT, connected.
[ WARN] [1445931897.713762981]: VER: broadcast request timeout, retries left 4
[ WARN] [1445931898.713489856]: VER: broadcast request timeout, retries left 3
[ WARN] [1445931899.738289315]: VER: unicast request timeout, retries left 2
[ WARN] [1445931900.738274606]: VER: unicast request timeout, retries left 1
[ WARN] [1445931901.739367898]: VER: unicast request timeout, retries left 0
[ WARN] [1445931902.720452732]: VER: your FCU don't support AUTOPILOT_VERSION, switched to default capabilities
[ INFO] [1445931905.696441357]: FCU: ArduCopter V3.2.1 (36b405fb)
[ INFO] [1445931905.700789649]: FCU: PX4: ce602658 NuttX: 475b8c15
[ INFO] [1445931905.706976732]: FCU: Frame: QUAD
[ INFO] [1445931905.712084732]: FCU: PX4v2 004B0036 30345106 36353832
[ERROR] [1445931906.753300440]: FCU: PreArm: Need 3D Fix
[ INFO] [1445931907.425516857]: PR: parameters list received
[ INFO] [1445931910.719410941]: WP: item #0 GAA WAYPOINT     params: 0, 0, 0, 0 x: 0 y: 0 z: 0
[ INFO] [1445931910.738838732]: WP: item #1 GRA TAKEOFF     params: 0, 0, 0, 0 x: 0 y: 0 z: 10
[ INFO] [1445931910.760883691]: WP: item #2 GAA UNK 183     params: 11, 1100, 0, 0 x: 0 y: 0 z: 0
[ INFO] [1445931910.777805316]: WP: item #3 GRA WAYPOINT     params: 10, 0, 0, 0 x: 30.303 y: 120.226 z: 10
>[ INFO] [1445931910.797380649]: WP: item #4 GAA UNK 183     params: 11, 1900, 0, 0 x: 0 y: 0 z: 0
>[ INFO] [1445931910.818518691]: WP: item #5 GRA RTL     params: 0, 0, 0, 0 x: 0 y: 0 z: 0
> [ INFO] [1445931910.819098441]: WP: mission received>
 
After I use ` rosrun mavros mavsys rate --all 30 ` I can get some data like `/mavros/imu/data` and `mavros/battery`
Here is the infomation about `/diagnostics`:

>header: 
  seq: 62
  stamp: 
    secs: 1445931748
    nsecs: 331244713
  frame_id: ''
status: 
  - 
    level: 0
    name: mavros: FCU connection
    message: connected
    hardware_id: /dev/ttyUSB0:115200
    values: 
      - 
        key: Received packets:
        value: 563
      - 
        key: Dropped packets:
        value: 0
      - 
        key: Buffer overruns:
        value: 0
      - 
        key: Parse errors:
        value: 0
      - 
        key: Rx sequence number:
        value: 51
      - 
        key: Tx sequence number:
        value: 73
      - 
        key: Rx total bytes:
        value: 16948
      - 
        key: Tx total bytes:
        value: 1359
      - 
        key: Rx speed:
        value: 17.000000
      - 
        key: Tx speed:
        value: 17.000000
  - 
    level: 2
    name: mavros: GPS
    message: No satellites
    hardware_id: /dev/ttyUSB0:115200
    values: 
      - 
        key: Satellites visible
        value: 0
      - 
        key: Fix type
        value: 0
      - 
        key: EPH (m)
        value: Unknown
      - 
        key: EPV (m)
        value: Unknown
  - 
    level: 0
    name: mavros: Heartbeat
    message: Normal
    hardware_id: /dev/ttyUSB0:115200
    values: 
      - 
        key: Heartbeats since startup
        value: 57
      - 
        key: Frequency (Hz)
        value: 0.899445
      - 
        key: Vehicle type
        value: Quadrotor
      - 
        key: Autopilot type
        value: ArduPilotMega
      - 
        key: Mode
        value: RTL
      - 
        key: System status
        value: Standby
  - 
    level: 0
    name: mavros: System
    message: Normal
    hardware_id: /dev/ttyUSB0:115200
    values: 
      - 
        key: Sensor present
        value: 0x00000000
      - 
        key: Sensor enabled
        value: 0x00000000
      - 
        key: Sensor helth
        value: 0x00000000
      - 
        key: CPU Load (%)
        value: 0.0
      - 
        key: Drop rate (%)
        value: 0.0
      - 
        key: Errors comm
        value: 0
      - 
        key: Errors count #1
        value: 0
      - 
        key: Errors count #2
        value: 0
      - 
        key: Errors count #3
        value: 0
      - 
        key: Errors count #4
        value: 0
  - 
    level: 2
    name: mavros: Battery
    message: No data
    hardware_id: /dev/ttyUSB0:115200
    values: 
      - 
        key: Voltage
        value: -1.00
      - 
        key: Current
        value: 0.0
      - 
>      key: Remaining
>        value: 0.0

Then I just run `rosrun mavros mavsafety arm` and I got failed. I try band with 57600 has same result. Anyone give me some suggestions. Thanks so much.

**Comment by vooon** [comment]
`FCU: PreArm: Need 3D Fix`.

**Comment by Tondy** [comment]
Hello. I have same issue. I even disabled the pre-check.

After running: roslaunch mavros amp2.launch and successfully connected.

I have tried arming the apm with : rosrun mavros mavsafety arm.

Result is: Request failed. Check mavros logs

Hope you can help.

**Comment by CrazyPopLin** [comment]
try to post your ros information when you launch the launch apm.launch.

**Comment by Tondy** [comment]
Hello when I run: rosrun mavros mavsafety arm.

Request failed. Check mavros logs appears. What can I do so I get more log information
of what happens. When I run the command. Do I get logs from mission planner or through
an addition lunix command.

**Comment by vooon** [comment]
@Tondy stop necroposting and please answer in your issue #538.
