### ISSUE TITLE
Error connecting MAVROS to APM 2.6 using telemetry

### ISSUE THREAD

**Issue by Tomofoye** [mavlink/mavros#416]
Hey, 

I am trying to connect an APM 2.6 to a MAVROS on a linux computer using the 3DR telemetry radios. I got the connection to work using a USB cable, but when I changed to the radios, I get the error: 

core service [/rosout] found
process[mavros-1]: started with pid [5672]
[ INFO] [1446439832.330939867]: FCU URL: /dev/ttyACM0:57600
[ INFO] [1446439832.331682277]: serial0: device: /dev/ttyACM0 @ 57600 bps
[FATAL] [1446439832.332496664]: FCU: DeviceError:serial:open: No such file or directory
================================================================================REQUIRED process [mavros-1] has died!
process has finished cleanly
log file: /home/dukerama/.ros/log/34b8deea-811d-11e5-8552-3ca9f46bddc4/mavros-1*.log
Initiating shutdown!
================================================================================
[mavros-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete

It looks like MAVROS might not be recognizing the radios connected to the computer. What can I do to fix this? Below is the launch file I use to initiate the connection. 

<launch>
	
	

	<arg name="fcu_url" default="/dev/ttyACM0:57600" />
	<arg name="gcs_url" default="" />
	<arg name="tgt_system" default="1" />
	<arg name="tgt_component" default="1" />

	<include file="$(find mavros)/launch/node.launch">
		<arg name="pluginlists_yaml" value="$(find mavros)/launch/apm_pluginlists.yaml" />
		<arg name="config_yaml" value="$(find mavros)/launch/apm_config.yaml" />

		<arg name="fcu_url" value="$(arg fcu_url)" />
		<arg name="gcs_url" value="$(arg gcs_url)" />
		<arg name="tgt_system" value="$(arg tgt_system)" />
		<arg name="tgt_component" value="$(arg tgt_component)" />
	</include>
</launch>

**Comment by vooon** [comment]
You should provide right URL.

```
roslaunch mavros apm.launch fcu_url:=/dev/ttyUSB0:57600
```
