### ISSUE TITLE
MAVROS sends DO_SET_MODE with armed flag not based on current arming state

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/mavros#423]
As described here this can lead to disarming the system in-air:
https://github.com/PX4/Firmware/issues/3142#issuecomment-154612992

**Comment by vooon** [comment]
But i thikned that with custom mode flag system only accept that value and not parse base_mode.

**Comment by vooon** [comment]
Also obvious listen to SYSTEM_STATUS and save arm flag give race that may happen between COMMAND_LONG-ARMING and receiving next SYSTEM_STATUS (<=1 sec window).

**Comment by vooon** [comment]
So i thinking that better react only to arming command and not base_mode...

**Comment by vooon** [comment]
Fixed, but testing required.

**Comment by vooon** [comment]
Checked with SITL.

**Comment by mhkabir** [comment]
What about the race conditions? This could cause weird issues or corner cases in the future.

**Comment by LorenzMeier** [comment]
The protocol is getting support to address transaction support. In the meantime you could just disallow mode switches if not armed.
