### ISSUE TITLE
Communication between QGC---->Mavros is failing

### ISSUE THREAD

**Issue by iceicehyhy** [mavlink/mavros#427]
@vooon  
hi, any idea about QGC ---> Mavros connection keep failing after mavros is updated?

I'll upload pic for your reference later.

Thanks.

**Comment by vooon** [comment]
Did you tried different connection methods? TCP for example?

**Comment by vooon** [comment]
Updates?

**Comment by iceicehyhy** [comment]
@vooon  it works, thank you!
