### ISSUE TITLE
HELP! I am unable to do a catkin_make for the mavros and mavlink packages on my Odroid XU4

### ISSUE THREAD

**Issue by iamveloci** [mavlink/mavros#429]
Hi,
I am trying to get mavros and mavlink built on my Odroid XU4 and had an error during the catkin_make process. This version of mavlink and mavros did not give me any trouble while building on my Beagle Bone Black. I am trying to switch to the Odroid XU4 since it is a faster computing platform in comparison to the BBB. I have attached the screen shot for your reference and the error is visible on the left terminal. Thanks in advance!
![catkin error](https://cloud.githubusercontent.com/assets/15251661/11174615/de486acc-8be3-11e5-992d-6ec11f250517.png)

**Comment by saihv** [comment]
Did you try "sudo apt-get install ros-indigo-tf"?

**Comment by iamveloci** [comment]
It worked! Thanks a ton!

**Comment by vooon** [comment]
Just follow installetion instructions: https://github.com/mavlink/mavros/tree/master/mavros#source-installation
