### ISSUE TITLE
libmavconn reports "compiler /usr/bin/c++ has no C++11 support" with g++-4.8 and 4.9

### ISSUE THREAD

**Issue by saihv** [mavlink/mavros#430]
Tried it with both gcc/g++ 4.8 and 4.9, and the update-alternatives was set correctly as well; yet libmavconn complains about C++11 support. I am on Linux Mint 17.2 (based off of Ubuntu 14.04)

Output of "/usr/bin/c++ -v"

    Using built-in specs.
    COLLECT_GCC=/usr/bin/c++
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.3-5ubuntu1~14.04' --with-       bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
    Thread model: posix
    gcc version 4.9.3 (Ubuntu 4.9.3-5ubuntu1~14.04)

**Comment by vooon** [comment]
Check your environment variables, perhaps you have setted `CXX=g++4.5` or so.

Anyway mavros compile with GCC 4.6 on Travis without a problem. So check what compiller used.
Also check `g++` alternative.

But you may simply do that:
```sh
export CC="gcc-4.9" CXX="g++-4.9"
catkin clean --all
catkin build
```

**Comment by saihv** [comment]
Still does not work after setting the variable CXX and CC to 4.9. It's quite confusing.

**Comment by vooon** [comment]
That command should print cmake coutput:
```sh
catkin build -v
```

Look for this line:
```
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```

**Comment by vooon** [comment]
Updates?

**Comment by saihv** [comment]
So sorry about the delay, this completely slipped my mind. Here's what the verbose output says.

    -- The C compiler identification is GNU 4.9.3
    -- The CXX compiler identification is GNU 4.9.3
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done

    Failed to build package 'libmavconn' because the following command:

    # Command to reproduce:
    cd /home/sai/catkin_ws/build/libmavconn && /home/sai/catkin_ws/build/libmavconn/build_env.sh /usr/bin/make --jobserver-fds=3,5 -j; cd -

    # Path to log:
    cat /home/sai/catkin_ws/build/build_logs/libmavconn.log

    Exited with return code: 2 

The log file is full of errors about keywords not being recognized.

**Comment by saihv** [comment]
Update: I just cloned the latest commit and now it builds fine!
