### ISSUE TITLE
Make second bugfix release for 0.16

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#431]
We have bug in setpoint_raw. Need release fix.

**Comment by vooon** [comment]
@AndreasAntener can you check agianst another bugs?

**Comment by AndreasAntener** [comment]
Which bug?

**Comment by vooon** [comment]
Any related to new features. Maybe something missed like mavros.mission import error in 0.16.0.

**Comment by vooon** [comment]
- Indigo: https://github.com/ros/rosdistro/pull/9824
- Jade:
