### ISSUE TITLE
Sending attitude commands to the Pixhawk using mavros

### ISSUE THREAD

**Issue by hridaybavle** [mavlink/mavros#433]
Hello all, 
I am trying to control the pixhawk with px4 native stack using an external stack. The external stack is 
installed on an odroid and communicates serially with the pixhawk.
I am not connecting the px4flow to the pixhawk, but connecting it using a USB to the odroid, so that I can send the px4flow data serially to the external stack (I know I can get px4flow data using mavros by connecting it to the i2c port on the pixhawk)

The external stack needs rotation angles (imu data) and the px4flow data and it can then send the roll, pitch, yaw and throttle commands to a UAV. I want to implement this external stack as a high level controller on the pixhawk. 

I am successfully able to get the imu data from the pixhawk, I can also successfully send throttle from the external stack by using the topic "mavros/setpoint_attitude/att_throttle". 

The problem I am facing now is controlling the roll, pitch and yaw. I want to send the roll, pitch and yaw values to the pixhawk using the external stack in the same way as one can be send it by using an RC.
Since I am not connecting the px4flow or the GPS to the pixhawk so the local position estimate being published wont be accurate (I dont know if I am correct with this one) and hence if I send the commands using the topic "mavros/setpoint_velocity/cmd_vel" or using "mavros/setpoint_attitude/cmd_vel" topics I don't see any commands being accepted by the pixhawk properly. 
I also figured that the topic "mavros/actuator_control" is not the correct one to send the roll, pitch, yaw commands in my case because I want to send commands to the pixhawk as they are sent by an RC but by using the external stack and not directly to the actuators.  

So my questions are
1. Do I always have to connect a px4flow or a GPS to the pixhawk when using offboard mode or I can use the setup mentioned above?
2. Is there anyway I can send the attitude commands to the pixhawk with mavros using a method like manual control (except in this case the external stack would be sending this commands to the pixhawk instead of an RC) ? 

I know there is topic called rc_override but since I am using px4 native stack I cannot use this topic as well.

UPDATE: I am now able to send Roll, Pitch, yaw and throttle commands to the Pixhawk using the actuator_control topic, the problem was that I was continuously sending setpoints to the pixhawk along with sending the actuator commands for putting it to offboard mode and hence the this was interfering with the commands I was sending, making the motors jitter. 
I did not know that continuously sending actuator commands can also put it in offboard mode. So now I have it fixed. 

Thanks.

**Comment by vinhk** [comment]
@hridaybavle Could you share your code? I am working on it as well. I do not have GPS. My issue is that attitude control did not make the quad fly. Although, the topics display the throttle value.

**Comment by LArayane** [comment]
@vinhk  how could you solve the problem!! which topic you are publishing in because I don't have GPS either

**Comment by mandelyoni** [comment]
Hi Hriday,

How are you using 'actuator_control' topic to command the desired Roll, Pitch, Yaw and Throttle values, directly? Can you upload a short publisher example?

Thanks, Yoni.

**Comment by vinhk** [comment]
@LArayane excuse me for the late reply. I don't it working at this point. Hoping the other user may help.

**Comment by mandelyoni** [comment]
Ok, thanks.
