### ISSUE TITLE
Make documentation more explicit

### ISSUE THREAD

**Issue by martinbeentjes** [mavlink/mavros#441]
When I visit the [mavros](http://wiki.ros.org/mavros) documentation it is not very clear which parameters, services and such may not be called by anothe ros node. Besides that, the text is not very well written as I see some spelling errors and such.

Can this be improved? Or how can we help improve that?

**Comment by andre-nguyen** [comment]
It's a wiki site. If you create an account, you can edit the page like any other wiki.
