### ISSUE TITLE
throttle mapping 

### ISSUE THREAD

**Issue by JM-SNU** [mavlink/mavros#449]
Hi, 
In my controller, the thrust command and roll, pitch, yaw command is obtained to control the UAV. In here, the thrust command has Newton units.
However, as I know, when I use mavros to send the command using attitude control, thrust range is 0.0 to 1.0.
How can I convert our thrust command(Newton) to analog value (0 to 1)??
Should I use force sensor to obtain mapping curve between above thing?
Thank you.

**Comment by vooon** [comment]
I'm not sure how to do that mapping. But keep in mind that field interpretation may be different.
E.g. APM defines that throttle 0.5 == *hovering*, 0.0/1.0 == parameter defined minimum (*descending*) and maximum (*ascending*) speeds.
