### ISSUE TITLE
Mavros not getting heartbeat SITL with gazebo (PX4)

### ISSUE THREAD

**Issue by alejodosr** [mavlink/mavros#453]
Hi,

I am trying to run this SITL simulation: https://pixhawk.org/dev/ros/sitl

However, Mavros is not receiving any HEARTBEAT (no connection despite UDP IP and ports seems to be correctly mapped). Do you have any idea?

Does anyone has successfully run a SITL simulation using Gazebo and px4?

**Comment by vooon** [comment]
As i know that guide is outdated.

I think you duplicate #446. Also connect https://github.com/PX4/Firmware/issues/3368 .
