### ISSUE TITLE
ENU to NED wrong conversion (BUG)

### ISSUE THREAD

**Issue by rosn** [mavlink/mavros#455]
Hi everyone,

In your code when you try to transform from ENU to NED, you only apply an PI rotation.
The real rotation should be :
UAS::quaternion_from_rpy(M_PI, 0.0,M_PI_2)

The thing is that this transformation, isn't symetric, So some modifications will be needed in your ENU to NED and NED to ENU transformation.

Thank you for your attention.

**Comment by mhkabir** [comment]
@rosn Could you please go over this here : https://github.com/mavlink/mavros/issues/438
And please let us know your comments with respect to the ongoing discussion. Thanks!
