### ISSUE TITLE
Update BatteryState

### ISSUE THREAD

**Issue by khancyr** [mavlink/mavros#458]
Hi,

I was reading mavros_msgs specification and it appends that BatteryState has been merge in sensors_msgs ! (in indigo and jade ) 
https://github.com/ros/common_msgs/commit/ea900b6fd10300867b373fe1fc37bd17ecba6225

When somebody got some time to update mavros side !

**Comment by vooon** [comment]
As soon as repo update. Also there problem with Travis (Hydro).
