### ISSUE TITLE
Normalized throttle value for SITL on gazebo using mavros

### ISSUE THREAD

**Issue by gokoreas** [mavlink/mavros#469]
I am using a custom built quadrotor to fly offboard using MAVROS

I measured the actual thrust compared to the normalized throttle value in the topic(/mavros/setpoint_attitude/att_throttle) to implement a offboard control code using attitude control

However, trying to use IRIS in the gazebo simulation with mavros, I have no idea what the normalized throttle values should be for the IRIS model

A guideline is needed for the thrust generated compared to the normalized thrust values at least for the standardized quadrotors such as IRIS or Solo

**Comment by vooon** [comment]
http://mavlink.org/messages/common#SET_ATTITUDE_TARGET

**Comment by gokoreas** [comment]
@voon 

What I mean by mapping is the thrust in N(force) to the value of throttle!

**Comment by vooon** [comment]
I don't thing that FCU operate in newtons (because it depends on many factors like battery charge).
So i do not have quick answer.

**Comment by gokoreas** [comment]
I understand. But we need the scales of normalized throttle value in order to fly in rate or acceleration control

Currently we are just measuring the thrust by experiments to match the normalized throttle values to N 

However for standardized quadrotors such as IRIS  which can run px4, if we have a guideline of on which battery voltage and thrust value creates which thrust(by real dimensions such as N), 

It can reduce the need for time and equipment to find the throttle value!

**Comment by IeiuniumLux** [comment]
@vooon , why did you close this?  I believe the main problem is that the on-board pid controller uses normalized thrust values @Jaeyoung-Lim is trying to use absolute thrust values instead.

Was guideline or map created to resolve this?
