### ISSUE TITLE
Wrong mavros topic in ROS wiki

### ISSUE THREAD

**Issue by gokoreas** [mavlink/mavros#472]
In the documentation of mavros in ROS wiki, ( http://wiki.ros.org/mavros )

local_position/pose
local_position/velocity

topics should be changed into 

local_position/local
where the PoseStamped message includes orientation and position

For reference for the mavros package, rqt_graph shows the topics which are currently implemented in mavros
![mavros_raw](https://cloud.githubusercontent.com/assets/5248102/12386570/d59ce4c2-be09-11e5-91b5-426f23409e9f.png)

**Comment by gokoreas** [comment]
I wonder if there is an alternative for the 

local_position/velocity

**Comment by vooon** [comment]
https://github.com/mavlink/mavros/blob/master/mavros/src/plugins/local_position.cpp#L50
