### ISSUE TITLE
'module' object has no attribute 'guided_enable'

### ISSUE THREAD

**Issue by srees** [mavlink/mavros#478]
I get the above error when running
'rosrun mavros mavsetp local -p 2 2 2 2' (for example) It's associated to line 40 of the mavsetp script.

Could this be related to issue #407 ? I'm guessing it's an easy fix but not sure what to do myself.

**Comment by vooon** [comment]
@srees can you check fix?

**Comment by srees** [comment]
Works for me. Thanks for the fast turnaround!
