### ISSUE TITLE
No `mavros/local_position/local` Topic

### ISSUE THREAD

**Issue by weiweikong** [mavlink/mavros#480]
I installed mavros by 
```
sudo apt-get install ros-indigo-ros*
```
and connected with Pixhawk (Stable Firmware) by
```
roslauch mavros px4.launch
```
I could get the topics and received data correctly such as `imu/data`, `local_position/pose` and `local_position/velocity`, however, there was no topic named `local_position/local`.
Also, I checked the ROS wiki (http://wiki.ros.org/mavros#mavros.2BAC8-Plugins.local_position),
where did not introduce such topic.
So I am confused about this topic?

**Comment by LorenzMeier** [comment]
@vooon Do you still need to arm to get those? It would seem like this should not depend on arming.

**Comment by vooon** [comment]
@LorenzMeier i'm not sure about publishing rates, but i think question not about "not publishing" issue.

@weiweikong Use `rostopic list`! And i'm pretty sure you missed *~* symbol, which means private node namespace (`/mavros` by default).

**Comment by weiweikong** [comment]
@LorenzMeier @vooon I tried some further test.
## mavros without arming the system
- Use `roslaunch mavros px4.launch`
![snapshot31](https://cloud.githubusercontent.com/assets/2463397/12539983/ce883ce2-c339-11e5-8151-f4d3c597ce8f.png)

- Then run `rostopic list`
![snapshot32](https://cloud.githubusercontent.com/assets/2463397/12539984/cf277ee2-c339-11e5-9624-402a5e5766f2.png)

- It seems that there was no `mavros/local_position/local` publishing.


## mavros with arming the system
- Arm the system by RC
![snapshot33](https://cloud.githubusercontent.com/assets/2463397/12539993/13c602d0-c33a-11e5-893d-a6526fe4752a.png)

- Then run `rostopic list`, still no `/mavros/local_position/local`. But other nodes receive data smoothly, such as `/mavros/local_position/pose`, by running 
```
rostopic ehco /mavros/local_position/pose
```
![snapshot34](https://cloud.githubusercontent.com/assets/2463397/12539998/3055979e-c33a-11e5-83b5-29eb6f1feb6a.png)

**Comment by weiweikong** [comment]
I checked the Pull https://github.com/mavlink/mavros/pull/420,
and in `master` branch, the `local_position.cpp` has, 
https://github.com/mavlink/mavros/blob/master/mavros/src/plugins/local_position.cpp#L50-L51,
renamed the publish nodes from `local_position/local` to
```
local_position = lp_nh.advertise<geometry_msgs::PoseStamped>("pose", 10);
local_velocity = lp_nh.advertise<geometry_msgs::TwistStamped>("velocity", 10);
```
So, it could be no `/mavros/local_position/local` topic in current version, no matter installing from `master` branch from github or using `sudo apt-get install ros-indigo-mavros*`.

**Comment by vooon** [comment]
Yes, just use `~local_position/pose`.
