### ISSUE TITLE
rosdep install --from-paths src --ignore-src --rosdistro jade -y

### ISSUE THREAD

**Issue by damanfb** [mavlink/mavros#484]
I can't get the installation from source of mavros completed on my Odroid XU4. 

I run get the following error

`odroid@odroid:~/ros_catkin_ws$ rosdep install --from-paths src --ignore-src --rosdistro jade -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
resource_retriever: No definition of [python-urlgrabber] for OS version [vivid]`

I have install python-urlgrabber already but I keep getting the same error.

**Comment by vooon** [comment]
As you can see: [rosdistro/rosdep/python.yaml][1], rosdep do not know about vivid.
You can work-around by making local_rosdep.yaml:
```yaml
python-urlgrabber:
  ubuntu: [python-urlgrabber]
```

And then add to `/etc/ros/rosdep/sources.list.d` link:
```sh
sudo tee /etc/ros/rosdep/sources.list.d/local_rosdep.list <<EOF
yaml file:///home/user/ros/local_rosdep.yaml
EOF
rosdep update
```

Alternative is to use `--os ubuntu:trusty`, but it may pull outdated packets.

[1]: https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L2069
