### ISSUE TITLE
Request param timeout

### ISSUE THREAD

**Issue by mangritosh** [mavlink/mavros#485]
Hello, 

I am receiving request param timeout warnings when connecting APM based quad-copter to mavros. Is this normal or is this a bug? (see screenshot attached). 
I am connecting via the radio link connected to USB.  Using latest Mavros version.

Thanks!

![screenshot from 2016-01-30 15 31 02](https://cloud.githubusercontent.com/assets/4015316/12696669/60b4be92-c768-11e5-862a-6ee368dc729c.png)

**Comment by vooon** [comment]
Not a bug. And not a problem since retry counter not reached 0.
