### ISSUE TITLE
Can't read /mavros/rc/in channels

### ISSUE THREAD

**Issue by damanfb** [mavlink/mavros#487]
I have a node that subscribes to /mavros/rc/in and attempts to read the switch value in /mavros/rc/in.channels[4] but whenever I try to access any of the .channels[] my node dies. Has anyone had success doing this?

**Comment by vooon** [comment]
Did you checked `channels` array size before accessing 4-th element?
Did you requested FCU to stream RC_CHANNELS?

What FCU, Firmware, version? Mavros logs?
