### ISSUE TITLE
Check frame conversions (NED->ENU ROS)

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#49]
Current implementation use this definitions [av8n.com](http://www.av8n.com/physics/coords.htm) of NED and ENU. Conversion is just invert Y & Z axis (all right-handed).

But according to [CoordinateFramConventions](http://wiki.ros.org/geometry/CoordinateFrameConventions) it is left-handed?

**Comment by ziyangli** [comment]
@vooon 
I have the same question ---- Why magnetometer use different conversion?

**Comment by tonybaltovski** [comment]
The mag is absolute and the others are relative.

**Comment by supermice** [comment]
Hi, everyone
     Does that means the attitude and position use the different base_coordinates in ROS? I tried to display the 'tf' data in ROS rviz use mavros . I find that the attitude's x axis is in red and when I move the aircraft along the attitude's x axis the 'tf' shows move to left(-y direction).  Is there any problem  with the local_origin tf or I use the old mavros version?
