### ISSUE TITLE
Multi-Vehicle support using PX4 SITL on gazebo?

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [mavlink/mavros#501]
https://www.youtube.com/watch?v=mJ2B3DeYhfQ

I guess the current implementation of PX4 SITL on gazebo only allows a single quadrotor to be controlled. The video above shows that all the quadrotors receive the same command as they are on the same udp port(?), and mavros cannot access each of the different quadrotors.

The plug in was launched using the following[ tutorial](http://dev.px4.io/simulation-ros-interface.html)

However, it will be nice to have multi-vehicle support as swarming can be very time consuming to implement without a robust simulation

What will be the direction if this feature could be implemented?

**Comment by gokoreas** [comment]
http://answers.ros.org/question/41433/multiple-robots-simulation-and-navigation/

This thread may be a good reference in implementing such a feature
