### ISSUE TITLE
libmavconn: Generate mavlink_dialect.h

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#522]
Since ROS version of mavlink package provide list of supported dialects we may generate that file.

At least that allow more easy inclusion of custom dialects.

**Comment by vooon** [comment]
Not sure on status, since in mavlink 2.0 we may support all dialects at once.

**Comment by samacumen** [comment]
Guys, how do we create this mavlink_dialect.h file. This is the only file missing in this project and I am trying to compile libMavConn library (without ROS - as it is independent of it). Any lead/instructions on how to generate the mavlink_dialect.h will be helpful.

Thanks!
