### ISSUE TITLE
Mavros tf broadcast

### ISSUE THREAD

**Issue by SyluxDX** [mavlink/mavros#528]
I have installed the newer version of mavros, and when I roslaunch the mavros node it publish a tf from map to base_link. My question is how can I disable this tf broadcast or change its name, since my code already publish the tf.

**Comment by vooon** [comment]
```
rosparam set /mavros/local_position/tf/send false
```

**Comment by SyluxDX** [comment]
Setting "/mavros/local_position/tf/send" don't seems to work, but black listing the local_position do. Is there another away to achieve it?

**Comment by SyluxDX** [comment]
Thank you. After updating the px4_config file and setting that parameter to false the tf stopped being publish.
