### ISSUE TITLE
Multiple Iris on Gazebo using PX4 Firmware

### ISSUE THREAD

**Issue by ItzMeJP** [mavlink/mavros#532]
Hello guys,

I am working with some SITL simulation on Gazebo v6.0, using PX4 firmware.

I have satisfactory results using MAVROS and only one model of the UAV Iris. So, I tried to insert another model of the quadrotor, but the mavros can't recognize it, even changing the MAVLINK's field "system_id" to zero (broadcast).

Anyone know how can i resolve this problem?

**Comment by vooon** [comment]
Each drone require it's own mavros node instance.

**Comment by ItzMeJP** [comment]
Yes,
even running two mavros instances, they both don't differentiate the quadrotos on Gazebo. 

I am looking for some help in this link:
https://github.com/PX4/sitl_gazebo/pull/20

**Comment by Jaeyoung-Lim** [comment]
How does the UDP port for the IRIS change when you have multiple quadrotors?

**Comment by cynthiamoon** [comment]
how to insert another PX4 model on gazebo?
