### ISSUE TITLE
RC override not supported by this FCU!

### ISSUE THREAD

**Issue by ozgurerbulan** [mavlink/mavros#535]
I am using version 16.06 with no problem but on another computer I have installed newest release and having this error when I start the px4.launch

**Comment by vooon** [comment]
Seems that you installed pretty old release or FCU do not send HEARTBEATs.

**Comment by ozgurerbulan** [comment]
FCU is fine on 16.06 but it does not work on 17.1

**Comment by vooon** [comment]
As you can see both 0.16.1+ and 0.17 has same code: https://github.com/mavlink/mavros/commits/master/mavros/src/plugins/rc_io.cpp

Do you have "got heartbeat" message? What `/diagnostics` show?

**Comment by ozgurerbulan** [comment]
Sorry for late answer. Problem solved when I updated the firmware of px4. Thank you a lot.
