### ISSUE TITLE
local_position/odom - velocity frame

### ISSUE THREAD

**Issue by spurnvoj** [mavlink/mavros#541]
We noticed that the velocity in local_position/odom is in a different frame (baselink) than velocity in the  local_position/velocity (ENU). Is this on purpose?

https://github.com/mavlink/mavros/blob/master/mavros/src/plugins/local_position.cpp#L118

**Comment by scott-eddy** [comment]
Yes,
The velocity in the odom message is represented in the baselink frame:
["The twist in this message corresponds to the robot's velocity in the child frame, normally the coordinate frame of the mobile base, along with an optional covariance for the certainty of that velocity estimate."](http://wiki.ros.org/navigation/Tutorials/RobotSetup/Odom)
