### ISSUE TITLE
distinguish arrived waypoint through mavros

### ISSUE THREAD

**Issue by CrazyPopLin** [mavlink/mavros#542]
Hi, I am just wondering if I get the informations that indicated the waypoints had been arrived from the rostopic "/mavros/mission/waypoints". 
For example: 4 waypoints in the list, I can find the first two mission items have been arrived. "is_current" is described what I am talking about?

**Comment by vooon** [comment]
What do you mean on "arrived"? List is updated only after full transfer completion, except current flag (which anyway changes after recv).

`is_current` indicate that FCU execute this item.

**Comment by CrazyPopLin** [comment]
I am using APM stack. 
The "arrived" means the waypoints have been went through or passed  by UAV.
*is_current* indicate the waypoint UAV flying to?
Thx.

**Comment by vooon** [comment]
Yes, and at least APM do that (tested by me).

**Comment by CrazyPopLin** [comment]
Hi @vooon , I found **seq** is the one I need to figure out what is passed waypoint. So I change the **mavros_msgs/Waypoint** to add seq and also the **waypoint.cpp**.
but I got issue: 
>The dependencies of the message/service 'mavros_msgs/Waypoint' have changed. Please rerun cmake.  

How I build mavros after change it. Thx

**Comment by vooon** [comment]
Why do you need it?! Siple array index is not enough?
