### ISSUE TITLE
MAVLink 2.0 support required

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/mavros#553]
@vooon In order to not stall the further development and addition of new messages we will need MAVLink 2.0 support (not for signing and v2.0 format, but for the MAVLink 2.0 binaries which support v1.0 and v2.0 messaging).

**Comment by vooon** [comment]
Lorenz, #543 & #545. But first i need some testing target like SITL.
As i know APM already merged to master, so i hope to go with #543 soon.

**Comment by LorenzMeier** [comment]
PX4 has MAVLink 2.0 support in master for about two weeks as well.

**Comment by vooon** [comment]
MAVLink 2.0 support is done, but: only Kinetic and require C++11 generator from `mavlink2-cxx11`.
