### ISSUE TITLE
What happened to mocap_fake_gps.cpp?

### ISSUE THREAD

**Issue by gitrahulhub** [mavlink/mavros#568]
I am following the indoor/fake gps tutorial on the px4 development guide at http://dev.px4.io/advanced-fake-gps.html, but on step 6 of the guide it requires the mocap_fake_gps file. When I build mavros from source can I just paste the file in the package before building or is there an alternative to using this file?

**Comment by vooon** [comment]
This is incomplete PR: https://github.com/mavlink/mavros/pull/442
