### ISSUE TITLE
compass data drift

### ISSUE THREAD

**Issue by Linjason314** [mavlink/mavros#571]
I use the MAVROS to read global_position/compass_hdg and I got compass inf.
But when Drone rotation any angle ,the compass data will drift about ±20 deg.
Does someone have successful experience can share with me? Thanks a lot.

**Comment by mhkabir** [comment]
This is a flightstack "issue". It is normal for compasses to drift. Make sure your sensors are calibrated.

**Comment by Linjason314** [comment]
Yes, I'm sure my sensors are calibrated.
But I use QGC to see compass data ,it's very stable.It's just use MAVROS will happened this issue.
those data are mean different things?

**Comment by mhkabir** [comment]
Which topic are you reading from?
