### ISSUE TITLE
Stream rates above 10 Hz possible?

### ISSUE THREAD

**Issue by andreasbaldur** [mavlink/mavros#573]
Hi
I'm using ArduSub [http://ardusub.com/](url) for PixHawk firmware which is connected to an Odroid XU4 running the mavros package. It is based on the APM flight stack. I want to increase the stream rate of the sensor output sent from the PixHawk.

I have tried to run:
`rosrun mavros mavsys rate --raw-sensors 10`
but 
`rostopic hz /mavros/imu/data`
indicates a limit is reach of 10 Hz. This is not very useful for my application.

Is there a workaround to this limit? I'm also open for modifying the ArduSub firmware.

/Andreas

**Comment by vooon** [comment]
Rates not limited by mavros at all. Limits may be in firmware or selected baud rate.
