### ISSUE TITLE
why there is no data in mavros/local_position/pose?

### ISSUE THREAD

**Issue by walkeryu123** [mavlink/mavros#582]
I use mavros with px4 firmware , and i use px4.launch file, i send vision data to mavros/vision_pose/pose or mavros/vision_pose/pose_cov, the terminal shows :
```
 [ INFO] [1469801065.372217112]: FCU: [inav] VISION estimate valid
```
 but there is no data in mavros/local_position/pose, what is wrong with it?
    thanks for any help

**Comment by Jaeyoung-Lim** [comment]
Does no data in mavros/local_position/pose mean that all values are zero?

**Comment by walkeryu123** [comment]
no data means there is nothing in mavros/local_position/pose

**Comment by mhkabir** [comment]
Please use latest PX4 master and companion link @ 921600.

**Comment by walkeryu123** [comment]
it works, thank you
