### ISSUE TITLE
mavros: rc  offboard mode

### ISSUE THREAD

**Issue by zer1988** [mavlink/mavros#583]
Hi everybody,
Currently I would like to receive  RC signal using mavors/rc_in and add with the chirping signal generated by my code. After that,  I will produce this signal again to FCU (maybe mavros_msgs/OverrideRCin) to override RC signal. My platform is PX4 native stack.
To do that, I had to change my system to Offboard mode through service mavros/setmode. But when I run my launch file, it shows me one error like 
[INFO] offboard enabled.
{Error] FCU: rejecting mode switch cmd.
Some one tell me how I can solve this problem or how to achieve this purpose.
Thanks.

**Comment by vooon** [comment]
RC override do not require offboard. But i strongly not recommend to use it for automatic control.
