### ISSUE TITLE
Mavros/Imu/data Conversion from Quaternion to Rotation 

### ISSUE THREAD

**Issue by zer1988** [mavlink/mavros#585]
Hi everybody,
some friends can guide me how we can convert the data of orientation of mavros/imu/data from quaternion to proper spatial rotaion roll pitch and yaw?

Many Thanks
Vu.

**Comment by vooon** [comment]
Just use python tf or Eigen.

**Comment by zer1988** [comment]
I used tf and transfer successfully IMU data using getRPY(). But i would like to know we need to do convert the coordination or not Voon.
Thanks

**Comment by vooon** [comment]
Mavros does frame conversion: ENU-NED, base_link-aircraft.

Also i recommend to use quaternions, not Euler  angles in controllers.
