### ISSUE TITLE
Rosbag records empty file

### ISSUE THREAD

**Issue by Muttle** [mavlink/mavros#590]
Hi all,

I am trying to use rosbag to record certain topics on my drone for an experiment. I am using an edison coupled with the px4 on a conventional helicopter running APM arducopter 3.3.3.

Now, due to a lack of free space on my edison, I am forced to used sshfs to mount an external drive and store the file offboard. I understand that this is not desirable however, I do not need extremely high sample rates and will only be concerned with a few topics so this should be ok? 

My problem is when I record topics no data appears in the file when I play it back or whilst it is running.

Thanks in advance.

```
px4@ubilinux:~/ros_catkin_ws/expdata$ rosbag info 2016-08-18-09-02-57.bag
path:        2016-08-18-09-02-57.bag
version:     2.0
duration:    57.9s
start:       Aug 18 2016 09:02:57.48 (1471510977.48)
end:         Aug 18 2016 09:03:55.36 (1471511035.36)
size:        127.3 KB
messages:    1439
compression: none [1/1 chunks]
types:       mavros_msgs/BatteryStatus [8ba4ae7c602c5ae6a7e8f3ffb652dc5f]
topics:      /mavros/battery   1439 msgs    : mavros_msgs/BatteryStatus
```

**Comment by vooon** [comment]
What `rqt_bag` shows?

**Comment by Muttle** [comment]
Hi vooon, 

rqt_bag shows it is all there. 

For some reason (probably me) I could not plot it using rqt_plot. But I have had a friend plot it on another machine.

Thanks!
