### ISSUE TITLE
Checkid app has hardcoded mavlink topic instead of namespace one

### ISSUE THREAD

**Issue by AlexisTM** [mavlink/mavros#597]
Dear,

Checkid app does not take the mavros namespace in account for the mavlink topic. My app actually uses a global namespace for Mavros, so the topics are : `\namespace\mavlink\...` and `\namespace\mavros\...`.

https://github.com/mavlink/mavros/blob/master/mavros/scripts/checkid#L33

Should I create a PR to add an argument for mavlink namespace ?

**Comment by vooon** [comment]
You may change ns via `__ns:=<ns>` command line option (common to all ROS nodes).
