### ISSUE TITLE
question: handle_local_position_ned(), the pose.x is puzzled me...

### ISSUE THREAD

**Issue by asimay** [mavlink/mavros#598]
In handle_local_position_ned() function, the odom->pose.pose has x & y elements. so the odom->pose.pose.x is equal to Vx *deltT, or ve \* deltT? (Vx is of body-enu frame, ve is local enu frame). if sensor didn't report x, y, z directly, I don't know use which velocity to calculate the pose?

**Comment by vooon** [comment]
Please give me a link to source file + line (click on line number, copy & paste url).

**Comment by asimay** [comment]
Thank you very much ! @vooon .
https://github.com/mavlink/mavros/blob/master/mavros/src/plugins/local_position.cpp#L116

**Comment by asimay** [comment]
I mean: if we calculate the pose according to the velocity, here is some ambiguous. should 

> pose.x = vx * deltT 
or

> pose.x = ve * deltT 
? this confuse me a lot. or use transform_frame_baselink_enu() to transform body's position to enu position, but this still need to calculate body position.

**Comment by vooon** [comment]
What is *vx*, *ve*? Define please. On L116 pose message copied to odom. `pose.position.{xyz} = enu_position.{xyz}`

**Comment by asimay** [comment]
sorry for misleading. 
vx is vehicle-body velocity x WRT ENU. ve is east velocity of INS output WRT NED.

**Comment by vooon** [comment]
Position provided by FCU. Only frame rotation needed.
