### ISSUE TITLE
Timeout quicker for vision_position plugin

### ISSUE THREAD

**Issue by ggregory8** [mavlink/mavros#60]
@vooon 
I think we need to find a way to stop sending the vision estimate if the tf is not updated (when using tf_listener). For example there is about an 8s delay from when I stop the vision estimate (ar_track_alvar) and when the vision_position plugin stops sending the vision_estimate to PX4.

Any ideas on this? Is there a way to check if a transform is older than a time, say 1s? Or alternatively we could also check the pose topic (/ar_pose_marker in the case of ar_track_alvar package) and only do the tf lookup if we get a valid estimate on this topic?

**Comment by MaMadDl** [comment]
i think there's a bug here 
i was trying to send vision_pose to px4 with topic and not tf and i got the following error 
[DEBUG] Vision: Same transform as last one, dropped.
i traced it to this line of code 
`		if (last_transform_stamp == stamp) {
			ROS_DEBUG_THROTTLE_NAMED(10, "vision_pose", "Vision: Same transform as last one, dropped.");
			return;
		}`
and i tried a quick fix by removing it and recompiling and message now goes through the mavros

**Comment by TSC21** [comment]
@MaMadDi if you read the comments on this issue carefully, you will see this is not a bug - it was inserted there for a purpose.

**Comment by TSC21** [comment]
Update your message timestamp instead of removing those lines (Check and update the msg `header`). Also you will required the timestamp for proper estimation on the FCU side.
