### ISSUE TITLE
ROS/Gazebo Simulator with SITL

### ISSUE THREAD

**Issue by hemjyoti** [mavlink/mavros#604]
I was following the steps as ,mentioned in the site. But it shows error while doing catkin_make
![screenshot from 2016-09-23 16 20 52](https://cloud.githubusercontent.com/assets/15228634/18783519/c8d4365a-81a9-11e6-849f-bceaa81ad55f.png)

**Comment by vooon** [comment]
Downgrade mavlink or update mavros to 0.18.

**Comment by TSC21** [comment]
@hemjyoti updates?

**Comment by TSC21** [comment]
Closing as there are no updates
