### ISSUE TITLE
CMakeLists file not present

### ISSUE THREAD

**Issue by vjayara1** [mavlink/mavros#607]
Hello all, 
I am trying to compile mavros packages on yocto, and i plan to use one recipe file at the top level (say mavros.bb) for all of mavros, mavros_extras, mavros_msgs and test_mavros pakages, but am facing a "CMake Error: source directory does not contain CMakeLists.txt". How do i change the recipe file so that it goes in and does CMake inside all 4 of these package directories. Thanks.

**Comment by vjayara1** [comment]
Can I have append multiple source directories to S variable ?

**Comment by vooon** [comment]
Then use as example some bb of ROS package stack (as it called before catkin). Check recipes of base ros repos.
