### ISSUE TITLE
mavros source build error in ROS kinetic

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [mavlink/mavros#621]
I am running ROS kinetic in Ubuntu 16.04

I was following the installation instruction on the [mavros git](https://github.com/mavlink/mavros/blob/master/mavros/README.md#installation)
But had a strange error while trying to do

```
wstool update -t src -j4
```

![screenshot from 2016-10-28 17-11-11](https://cloud.githubusercontent.com/assets/5248102/19811483/e6e383fa-9d31-11e6-8884-a793d88a9405.png)

I cannot find any other issues related to the issue which I am having.
Has anyone had problems with a source build in ROS kinetic?

**Comment by vooon** [comment]
Problem in version string (== git tag). Fixed in f08c7c0ac73added9d2b16ca405e8b280e67463a
