### ISSUE TITLE
libmavconn not compiling on OSX

### ISSUE THREAD

**Issue by pvechersky** [mavlink/mavros#626]
libmavconn is failing to compile on OSX due to an error in thread_utils.h (https://github.com/mavlink/mavros/blob/master/libmavconn/include/mavconn/thread_utils.h). This appears to be due to an issue with the different APIs for pthread_setname_np (http://stackoverflow.com/questions/2369738/can-i-set-the-name-of-a-thread-in-pthreads-linux/7989973#7989973).

Would it be possible to extend libmavconn to support OSX?

Thank you!

**Comment by vooon** [comment]
It is possible, and relatively easy, but i don't has any OSX machine where i can check changes.

**Comment by TSC21** [comment]
@pvechersky are you able to compile it already on MAC OS X?

**Comment by pvechersky** [comment]
@TSC21 unfortunately I don't have access to an OSX machine so I am not able to test this :(

**Comment by TSC21** [comment]
Is there anyone with a OSX machine that can test this?

**Comment by pvechersky** [comment]
I believe that @ffurrer has access to an OSX machine but could be wrong

**Comment by TSC21** [comment]
@ffurrer would you be kind to test this on your OSX? Thanks

**Comment by TSC21** [comment]
@pvechersky can this be closed now?
