### ISSUE TITLE
Imu corrdinate true direction

### ISSUE THREAD

**Issue by xiaopenghuang** [mavlink/mavros#651]
### Issue details

can anyone tell me the device imu raw direction , and mavros output imu direction .I am confused about it.

According to mpu6050 datasheet , the direction  is 
![screenshot from 2017-02-08 10 53 41](https://cloud.githubusercontent.com/assets/7861326/22721644/fbe629ae-edec-11e6-9e7e-0eb866c12247.png)

If  laid it flat on the ground , i think the acceleration is (0,0,-9.8), but the mavros output is (0,0,9.8).

use the positive direction define in mpu6050 datasheet , i draw the direction accrding to `/mavros/imu/data`

![img_20170208_110053](https://cloud.githubusercontent.com/assets/7861326/22721925/99958428-edee-11e6-9bb5-92f1bd6785cb.jpg)

according to acceleration and gyro , i found the direction is reverse, why.

**Comment by mhkabir** [comment]
Mavros follows the ENU convention according to ROS REP 103 (http://www.ros.org/reps/rep-0103.html). It is correct.

**Comment by xiaopenghuang** [comment]
@mhkabir can you tell me in pixhawk imu device direction , why when i laid flat ,get the acceleration (0,0,9.8) , not (0,0,-9.8),it really werid
