### ISSUE TITLE
Plugin distance_sensor loaded but Topic Not found!

### ISSUE THREAD

**Issue by MasterRos** [mavlink/mavros#669]
Hi..
[ INFO] [1488479645.789276243]: Plugin distance_sensor loaded
[ WARN] [1488479645.789853753]: DS: plugin not configured!
[ INFO] [1488479645.789883228]: Plugin distance_sensor initialized
rostopic list 
not found topic with name "distance_sensor" ??

i removed that from this list (apm_pluginlists.yaml):

plugin_blacklist:
.# common
..
.# extras
...
distance_sensor
...

**Comment by vooon** [comment]
That plugin require configuration like that: https://github.com/mavlink/mavros/blob/master/mavros/launch/px4_config.yaml#L116
But APM do not support DISTANCE_SENSOR message anyway.

**Comment by Ahrovan** [comment]
I checked this (ardupilot-Copter-3.4.5 - GCS_Mavlink.cpp):
void GCS_MAVLINK_Copter::handleMessage(mavlink_message_t* msg)
{
...
    case MAVLINK_MSG_ID_DISTANCE_SENSOR:
    {
        result = MAV_RESULT_ACCEPTED;
        copter.rangefinder.handle_msg(msg);
        break;
    }
..
}
and ( ardupilot-Copter-3.4.5 - AP_RangeFInder_Mavlink.cpp):
void AP_RangeFinder_MAVLink::handle_msg(mavlink_message_t *msg)
{
    mavlink_distance_sensor_t packet;
    mavlink_msg_distance_sensor_decode(msg, &packet);

    last_update_ms = AP_HAL::millis();
    distance_cm = packet.current_distance;
}
//
last line show APM can set distance_cm from DISTANCE_SENSOR message!

**Comment by Ahrovan** [comment]
what mean  DS: plugin not configured!
I check mavros with PX4 stack too, but this warning Remained.

**Comment by vooon** [comment]
Ok, looks like APM now implemented that. Update to master, it added config in #670.

**Comment by Ahrovan** [comment]
that's work.. but parameter for select pub or sub do not work well.

**Comment by TSC21** [comment]
@Ahrovan any updates? Did you check the px4_config.yaml for how it works?

**Comment by Ahrovan** [comment]
No, just i checked apm_pluginlists.yaml

**Comment by TSC21** [comment]
Apply the configs the same way as you find on px4_config. See if you want to publish the data comming from the FCU or you want to subscribe data coming from a sensor on your computer and send it to the FCU.

**Comment by TSC21** [comment]
@Ahrovan updates?

**Comment by TSC21** [comment]
Closing as staled. @MasterRos please reopen if you still have problems.

**Comment by khancyr** [comment]
distance_sensor is now full implemented on ardupilot side for sensor output and as input

**Comment by TSC21** [comment]
> distance_sensor is now full implemented on ardupilot side for sensor output and as input

Thanks for confirming @khancyr.
