### ISSUE TITLE
gazebo & ros & px4(Firmware) connection problems.

### ISSUE THREAD

**Issue by yajingwang94** [mavlink/mavros#671]
Hi. I have already run the SITL package using rotorcraft model in gazebo successfully. Now I want to add a new UAV model to the framework (to use px4 in my model's simulation). I have spent several days studying the codes. I failed to understand the communication mechanism between mavros node and px4(the firmware part). 
To be specific: could someone please tell me something about the following topics?
/mavlink/to
/mavlink/from
/mavros/rc/in
/mavros/rc/out
/mavros/rc/override

I would be really grateful if anyone can help.

**Comment by weiweikong** [comment]
![default](https://cloud.githubusercontent.com/assets/2463397/23584984/79492068-01ac-11e7-9ef2-003c3435c654.png)

**Comment by mhkabir** [comment]
@weiweikong That's an awesome diagram! Many thanks! 

Can we use it for the PX4 Devguide (https://dev.px4.io) with appropriate credits to you?

**Comment by weiweikong** [comment]
@mhkabir Sure, my pleasure. Please check the details and I would like to update the diagram along with the further development. 
In which way is much convenient for you to add it to PX4 Devguide and I could cancel the water marker and my e-mail address.

**Comment by mhkabir** [comment]
Awesome. The diagram is very complete and easy to understand. Removing the watermark and email would be nice, and I'll make sure your name is on the page (https://dev.px4.io/simulation-gazebo.html) as creator.

We're having some issues with the Devguide at the moment, so it would be great if you could email it to me and I'll bring it in when we fix it again. For maintainability - you can share the original design files and tell us what software you used to make it. I will upload to the Devguide repository and it can be used/edited very easily as development happens.

**Comment by weiweikong** [comment]
@mhkabir Original files send to your uasys.io address.

**Comment by yajingwang94** [comment]
Thanks a lot for the help.
