### ISSUE TITLE
vision_position_estimate timestamp

### ISSUE THREAD

**Issue by tuofeichen** [mavlink/mavros#678]
### Issue details

Hi All, 
I'm using vision_position_estimate to feed in some VSLAM estimate from my onboard computer to a pixhawk. Namely, I'm publishing to the topic /vision_pose/pose.

However, the timestamp value (everything else were sent accurately) that I sent (and double checked until [this point](https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/vision_pose_estimate.cpp#L105) is not the same as what I see from the mavlink inspector under the topic VISION_POSITION_ESTIMATE. 

Is there any syncing / conversion of time during `send_message` ? or anything I'm not aware of ? 

Thank you.

Best Regards,
Tuofei 

### MAVROS version and platform

Mavros: `0.17.4`
ROS: `Indigo `
Ubuntu: `14.04`

### Autopilot type and version

[  ] ArduPilot
[*] PX4

**Comment by mhkabir** [comment]
Yes timesync is performed automatically.
