### ISSUE TITLE
Setting up mavros node to run inside 2 UAVs

### ISSUE THREAD

**Issue by zer1988** [mavlink/mavros#683]
### Issue details
Hi everybody. Currently, I was successful in controlling 1 drone using mavros. However, to run 2 drones at the same time using launch file, I do not know the right way to edit since we cannot run the mavros node in 2 drones at the same node. I tried to change the name of mavros node to mavros 1 and mavros 2 in  mavros_node.cpp. It can arm motors now as well as i can read the topics of mavros under the prefix mavros1/ and mavros2/, but my drone is unstable and cannot take off as while i used the old node of mavros.

### MAVROS version and platform
Mavros: ?0.18.4?
ROS: Indigo
Ubuntu: 14.04 LTS

### Autopilot type and version

[  ] PX4
Version: 1.5.5

**Comment by vooon** [comment]
You may use namespaces and better assign different SYSTEM_ID to FCU (and mavros).

**Comment by zer1988** [comment]
Hi Voon,
I tried to add namespace but my motor cannot arm as usual. Further more, I assigned different system_id to fcu, but how about the mavros?. Thanks

**Comment by zer1988** [comment]
Hi voon, it works nơ. Thank you for your help. The problem is that I added one group ns but i do not add the ns prefix for each node of mavros while I use. I think we can close this topic now. Thanks.

**Comment by michael1874888** [comment]
Hi , We are trying to do the same thing as you , but we face some problems . Can you please show me your launch file ? It would be very helpful to us .

**Comment by cnpcshangbo** [comment]
I think we need to open a new issue to ask.
