### ISSUE TITLE
global_position/local not consistent with nav_msgs::Odometry frames definition

### ISSUE THREAD

**Issue by lukvacek** [mavlink/mavros#685]
Hello, the definition for nav_msgs/Odometry states that while the pose should be in the header.frame_id, the twist portion of the message should be in child_frame_id. I don't believe this is the case in handle_global_position_int as it passes the GPS vx, vy, vz velocities directly to the Odometry message.

**Comment by TSC21** [comment]
@lukvacek in the `global_position` plugin, for the odometry, we assume that there is not transform required, meaning that a `child_frame_id` doesn't exist.
