### ISSUE TITLE
Does anyone have code for Px4 using Mavros to send basic movements such as takeoff, forward, backward, left, and right without GPS?

### ISSUE THREAD

**Issue by vinhk** [mavlink/mavros#701]
I am using Px4flow with Pixhawk. Would like to see if there is a position control code for this case.

Thanks

**Comment by TSC21** [comment]
The src for position estimation doesn't influence the position control. So the same code sending setpoints works if you use only GPS, only flow or both, cause it is the estimation modules that rely on those, not the position controllers. So https://dev.px4.io/en/ros/mavros_offboard.html will do the job.

**Comment by vinhk** [comment]
@TSC21 How about left right movements?

**Comment by TSC21** [comment]
Considering ENU frame, that would be changing `y` values, to positive or negative depending on the `local_origin`. Back and forward would be the `x` values.

**Comment by vinhk** [comment]
if i want to change y values, I just need to do ` pose.pose.position.y = 2;` inside the `while` loop?

**Comment by TSC21** [comment]
That means you are setpointing the vehicle 2 meters to the right of the local origin and it will stick in that position if you don't send a different stream of setpoints. But you can try it yourself with SITL for example

**Comment by vinhk** [comment]
Okay, thanks. I think my issue is with altitude and position hold.

**Comment by vinhk** [comment]
But in terms of testing in Stil I have that part.

**Comment by TSC21** [comment]
Offboard mode is as it states, a mode. The same goes to altitude hold and position hold, which are also other modes. Both of them do not depende on external setpoints and only work based of the feedback of the onboard position control and estimation.

**Comment by vinhk** [comment]
Thanks
