### ISSUE TITLE
delay in mavros/rc/override

### ISSUE THREAD

**Issue by rouzbehfarhadi** [mavlink/mavros#702]
hi
 i have 1 second delay for to do when i publish in mavros/rc/override   . where is the problem from?

**Comment by vooon** [comment]
Check CPU usage, communication speeds & usage.
How you measure that delay?

**Comment by rouzbehfarhadi** [comment]
tnx.i publish data and wait for motor effect.
i have control position by optical position but not stable in setpoint position.

**Comment by TSC21** [comment]
@rouzbehfarhadi any updates on this?

**Comment by TSC21** [comment]
Closing as staled. @rouzbehfarhadi please reopen if this subsists.
