### ISSUE TITLE
Disable unnecessary topics of mavros

### ISSUE THREAD

**Issue by zer1988** [mavlink/mavros#705]
Issue details

I would like to disable the unnecessary topics of mavros for my project such as mavros/local_position/pose while run launch file (as in attached file) because there are many topics I did not use while run 2 drones at the same time but they occupy a large amount of network load. I opened "px4_pluginlists.yaml" file and add the name of unnecessary topics as well as run rosparam load="file" ( as in attached files), but it is unsuccessful. Can you guide me how to do this?
Thanks
[launch.docx](https://github.com/mavlink/mavros/files/980711/launch.docx)
[plugin.docx](https://github.com/mavlink/mavros/files/980713/plugin.docx)

Thanks,

MAVROS version and platform

Mavros: ?0.18.4?
ROS: Indigo
Ubuntu: 14.04

Autopilot type and version

PX4
Version: 1.5.5

**Comment by TSC21** [comment]
Please don't duplicate the issues.
