### ISSUE TITLE
mavros Documentation - broken/missing message documentation links

### ISSUE THREAD

**Issue by fbalaban** [mavlink/mavros#720]
### Issue details

In [wiki](http://wiki.ros.org/mavros), links for message documentation for srv types  : 

~mission/pull (mavros_msgs/WaypointPull)

~mission/push (mavros_msgs/WaypointPush)

~mission/clear (mavros_msgs/WaypointClear)

~mission/set_current (mavros_msgs/WaypointSetCurrent)

are broken.

**Comment by vooon** [comment]
Looks like some problems with ROS servers. You may see all msgsrv docs here: http://docs.ros.org/kinetic/api/mavros_msgs/html/index-msg.html

**Comment by TSC21** [comment]
Closing this at it seems to be solved.
