### ISSUE TITLE
Release for ROS Lunar

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#721]
ROS Lunar relased, need to add mavros.

**Comment by mhkabir** [comment]
^_^

**Comment by vooon** [comment]
http://www.ros.org/news/2017/03/lunar-loggerhead-buildfarm-available.html

Seems that only mavlink blocking mavros release :)

**Comment by vooon** [comment]
Mavlink release not fully successful: https://github.com/ros/rosdistro/pull/15062

**Comment by vooon** [comment]
Done.

https://github.com/ros/rosdistro/pull/15063
https://github.com/ros/rosdistro/pull/15066
https://github.com/ros/rosdistro/pull/15067
