### ISSUE TITLE
Altitude problem with /mavros/cmd/takeoff

### ISSUE THREAD

**Issue by Ahrovan** [mavlink/mavros#724]
Takeoff work with mavproxy, and "takeoff 5" command -> result about 5meter altitude, but :

```
ros::ServiceClient takeoff_cl = n.serviceClient<mavros_msgs::CommandTOL>("/mavros/cmd/takeoff");
mavros_msgs::CommandTOL srv_takeoff;
srv_takeoff.request.altitude = 5;
srv_takeoff.request.latitude = 0;
srv_takeoff.request.longitude = 0;
srv_takeoff.request.min_pitch = 0;
srv_takeoff.request.yaw = 0;
if(takeoff_cl.call(srv_takeoff)){
ROS_ERROR("srv_takeoff send ok %d", srv_takeoff.response.success);
}else{
ROS_ERROR("Failed Takeoff");
}
```

result of this code with mavros is not 5meter altitude, but about 1meter.

for example plot show - takeoff 5 (in GUIDED+mavproxy) and takeoff 5 (in LOITER+mavros)
![image](https://cloud.githubusercontent.com/assets/5772832/26746077/ecb215ae-4802-11e7-9d94-2df66ab948e8.png)

ArduPilot(Copter-3.5.0-rc7 ), ros-kinetic-mavros(0.18.7), Gazebo8 uctf SITL

**Comment by vooon** [comment]
Try:
```
rosrun mavros mavsys mode -c GUIDED
rosrun mavros mavcmd takeoff 0 0 0 0 5
```

**Comment by TSC21** [comment]
@Ahrovan you still have problems?

**Comment by Ahrovan** [comment]
@vooon  rosrun mavros mavsys mode -c GUIDED
or
    ros::ServiceClient cl = n.serviceClient<mavros_msgs::SetMode>("/mavros/set_mode");
    mavros_msgs::SetMode srv_setMode;
    srv_setMode.request.base_mode = 0;
    srv_setMode.request.custom_mode = "LOITER";
    if(cl.call(srv_setMode)){
        ROS_ERROR("setmode send ok %d value:", srv_setMode.response.success);
    }else{
        ROS_ERROR("Failed SetMode");
        return -1;
    }
result in mavros terminal this:
CMD: Unexpected command 11, result 0

**Comment by Ahrovan** [comment]
This problem solved. thx

**Comment by ashirsat** [comment]
@Ahrovan What did you do to solve this problem?
