### ISSUE TITLE
How to use compass offsets?

### ISSUE THREAD

**Issue by jjkllll** [mavlink/mavros#737]
Hi, I am using mavros to read the APM2.5 internal compass data. But the data showing is not correct. On Mission planner I calibrated the compass and got x,y and z offsets. Using mavros the compass data which I got is bearing. I want to know how to use these offsets to correct the compass bearing.

**Comment by vooon** [comment]
APM should apply offsets itself. Calibration data should be stored in FC parameters.
Useually GCS do that automatically.

**Comment by jjkllll** [comment]
Thanks!!
