### ISSUE TITLE
Distance sensors improvements

### ISSUE THREAD

**Issue by khancyr** [mavlink/mavros#740]
### FEATURE details

- Add support for laser subscriber and publisher
- Limit the error stream at https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/distance_sensor.cpp#L208 
In case we send distance to FCU, at least on ardupilot, the message will be resend by the FCU so mavros spam the console.
- support https://github.com/mavlink/mavlink/pull/740 (if merged)

Can be assign to me !

**Comment by TSC21** [comment]
> Add support for laser subscriber and publisher

You mean: http://docs.ros.org/api/sensor_msgs/html/msg/LaserScan.html ?

> Limit the error stream at https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/distance_sensor.cpp#L208
In case we send distance to FCU, at least on ardupilot, the message will be resend by the FCU so mavros spam the console.

Ok makes sense. @JD-ETH this may interest you, as Ardupilot already does what you are looking for.

> support mavlink/mavlink#740 (if merged)

Yeah that should be straightforward.

Waiting your PR then :)

**Comment by khancyr** [comment]
Yes I was thinking about laserscan, but it doesn't seem that ROS use a lot of 1D laser rangefinder. I will dig a little to see how they handle it. 
Otherwise it could be use for Ardupilot proximity feature that act like a simplified 360 laserscan

**Comment by TSC21** [comment]
@khancyr check this: https://github.com/mavlink/mavros/pull/292#issuecomment-101750640. For 1D Laser, we use `INFRARED` type in `sensor_msgs/Range`.

> Otherwise it could be use for Ardupilot proximity feature that act like a simplified 360 laserscan

How do you have that implemented? Multiple `DISTANCE_SENSOR` msgs, one for each beam?

**Comment by TSC21** [comment]
Related: https://github.com/ros/common_msgs/pull/73

**Comment by khancyr** [comment]
interesting ! Thanks for the information !

About proximity, yes , each sector send a distance_sensor msg with a different id : http://ardupilot.org/dev/docs/code-overview-object-avoidance.html

**Comment by TSC21** [comment]
> About proximity, yes , each sector send a distance_sensor msg with a different id : http://ardupilot.org/dev/docs/code-overview-object-avoidance.html

Thanks for sharing

**Comment by TSC21** [comment]
@khancyr are you considering doing a PR to this in the mean time?

**Comment by khancyr** [comment]
yes probably next week, I am waiting some material to do test

**Comment by TSC21** [comment]
> yes probably next week, I am waiting some material to do test

Awesome

**Comment by TSC21** [comment]
Solved with #747, #748, #749.
