### ISSUE TITLE
Yaw offset in /mavros/setpoint_raw/local

### ISSUE THREAD

**Issue by ChrisGermany** [mavlink/mavros#751]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

The yaw rotation has a 90degree offset when publishing to /mavros/setpoint_raw/local. This issue is not present when publishing a desired pose to /mavros/setpoint_position/local. I am pretty sure it has something to do with the END <-> NED conversion. 

### MAVROS version and platform

Mavros: latest
ROS: indigo
Ubuntu: 14.04

### Autopilot type and version

[  ] ArduPilot
[X] PX4

Version: 1.6.3v4

**Comment by TSC21** [comment]
@ChrisGermany were you able to test the modifications I did on my branch?

**Comment by TSC21** [comment]
@ChrisGermany what's the status of this?

**Comment by Seanmatthews** [comment]
I've also seen incorrect yaw offsets in the system. When using MAVROS with PX4, I can't get PX4 to realize that the yaw is not pi/2 at the origin. Along with #762, there are some odd transformations occurring through MAVROS.

**Comment by TSC21** [comment]
The issue reported is related to angular velocities being published to the FCU and not the other way around.

**Comment by Seanmatthews** [comment]
@TSC21 Thanks for the clarification. To that effect, I see a 90 degree offset when publishing to setpoint_position/local. I believe this is related to what I described, and that there's some more inherent transformation issue at large.

**Comment by TSC21** [comment]
@ChrisGermany is this solved to you already?

**Comment by TSC21** [comment]
> I believe this is related to what I described, and that there's some more inherent transformation issue at large.

@Seanmatthews as I said this issue is completly different, as there was a lack of a propper frame transform on the `transform_frame_yaw` method (only).

**Comment by epiception** [comment]
Is this is still an issue on v1.8.2? We seem to be facing a 90 degree offset in yaw when publishing 0 to /mavros/setpoint_position/local. Any solutions to this?
