### ISSUE TITLE
How to connect both mavros and gcs to fcu at the same time?

### ISSUE THREAD

**Issue by TSC21** [mavlink/mavros#77]
I have doubts regarding the connection of the gcs using tcp or udp after launching the mavros node. 
I use: `rosrun mavros mavros_node _fcu_url:=/dev/ttyACM0:57600`
Got in the cmd log:

```
 [ INFO] [1407186463.360407694]: FCU URL: /dev/ttyACM0:57600`
 [ INFO] [1407186463.360972333]: serial0: device: /dev/ttyACM0 @ 57600 bps`
 [ INFO] [1407186464.238116655]: GCS URL: udp://@`
 [ INFO] [1407186464.238464639]: udp1: Bind address: 0.0.0.0:14555 `
```

But I can't get any connection with the fcu. What am I doing wrong and what should be done?

Thanks!

Note: By the way how can I add a block of code to the comment? :D

**Comment by shubham-shahh** [comment]
> Working now! Used the `launch` file and added `udp://@localhost` in the gcs param. Can close now!

how can I find the value for gcs param?

**Comment by evbernardes** [comment]
@shubham-shahh Hey there! Did you find how to get this param?
