### ISSUE TITLE
Using the PositionTarget message

### ISSUE THREAD

**Issue by Seanmatthews** [mavlink/mavros#794]
Is there a configuration with using setpoint_raw and the PositionTarget message where I'm able to command the vehicle to a position at a velocity? After reading a slew of velocity control issues, I can't figure it. Alternatively, can I set the maximum velocity used by position control over the XY (horizontal) plane?

**Comment by TSC21** [comment]
Check what's done on `test_mavros` with the `control_toolbox`.

**Comment by Seanmatthews** [comment]
@TSC21 I took a look at the packages and it doesn't look like they're just sending setpoints. Is velocity mode required to have any sort of direct control over the travel velocity between setpoints?

**Comment by TSC21** [comment]
> Is velocity mode required to have any sort of direct control over the travel velocity between setpoints?

Yes. You can directly control the velocity or use the PID controller.
