### ISSUE TITLE
Add support for debug messages

### ISSUE THREAD

**Issue by jlecoeur** [mavlink/mavros#796]
MAVLink has three messages that can be used to send debug values: NAMED_VALUE_FLOAT, DEBUG and DEBUG_VECT. 
They are useful to quickly stream some values, or as an alternative to creating custom MAVLink message.

Support for these messages should be added to mavros-extras.

@TSC21

**Comment by TSC21** [comment]
Thanks @jlecoeur! Seems a good addition to a plugin. Will be a todo.

**Comment by jlecoeur** [comment]
Thanks @TSC21 @vooon 👍
