### ISSUE TITLE
MAVROS Service required for MAV_CMD_SET_MESSAGE_INTERVAL

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [mavlink/mavros#805]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details
The existing `/mavros/set_stream_rate` for (http://mavlink.org/messages/common#REQUEST_DATA_STREAM) is deprecated.

It is required to replace the existing `/mavros/set_stream_rate`  by a new MAVROS Service for [MAV_CMD_SET_MESSAGE_INTERVAL](http://mavlink.org/messages/common#MAV_CMD_SET_MESSAGE_INTERVAL).

### MAVROS version and platform

Mavros: 0.19.0
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

PX4
Version: 4.4.0

Thanks,
Shakthi

**Comment by vooon** [comment]
Duplicate #370.
