### ISSUE TITLE
cannot launch px4.launch with mavros

### ISSUE THREAD

**Issue by aaumar** [mavlink/mavros#843]
here is the error that I get when I try to execute 
$ roslaunch mavros px4.launch

> abdularis@abdularis:~/catkin_ws$
 roslaunch mavros px4.launch
... logging to /home/abdularis/.ros/log/8e55979a-b7c1-11e7-9333-54ab3af70fe5/roslaunch-abdularis-10611.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
started roslaunch server http://abdularis:40955/
SUMMARY
========
CLEAR PARAMETERS
  /mavros/
PARAMETERS
  /mavros/cmd/use_comp_id_system_control: False
  /mavros/conn/heartbeat_rate: 1.0
  /mavros/conn/system_time_rate: 1.0
  /mavros/conn/timeout: 10.0
  /mavros/conn/timesync_rate: 10.0
  /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
  /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
  /mavros/distance_sensor/hrlv_ez4_pub/id: 0
  /mavros/distance_sensor/hrlv_ez4_pub/orientation: ROLL_180
  /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
  /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
  /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
  /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
  /mavros/distance_sensor/laser_1_sub/id: 3
  /mavros/distance_sensor/laser_1_sub/orientation: ROLL_180
  /mavros/distance_sensor/laser_1_sub/subscriber: True
  /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
  /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
  /mavros/distance_sensor/lidarlite_pub/id: 1
  /mavros/distance_sensor/lidarlite_pub/orientation: ROLL_180
  /mavros/distance_sensor/lidarlite_pub/send_tf: True
  /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
  /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
  /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
  /mavros/distance_sensor/sonar_1_sub/id: 2
  /mavros/distance_sensor/sonar_1_sub/orientation: ROLL_180
  /mavros/distance_sensor/sonar_1_sub/subscriber: True
  /mavros/fake_gps/eph: 2.0
  /mavros/fake_gps/epv: 2.0
  /mavros/fake_gps/fix_type: 3
 /mavros/fake_gps/geo_origin/alt: 408.0
 /mavros/fake_gps/geo_origin/lat: 47.3667
  /mavros/fake_gps/geo_origin/lon: 8.55
  /mavros/fake_gps/gps_rate: 5.0
  /mavros/fake_gps/mocap_transform: True
  /mavros/fake_gps/satellites_visible: 5
  /mavros/fake_gps/tf/child_frame_id: fix
  /mavros/fake_gps/tf/frame_id: map
  /mavros/fake_gps/tf/listen: False
  /mavros/fake_gps/tf/rate_limit: 10.0
  /mavros/fake_gps/tf/send: False
  /mavros/fake_gps/use_mocap: True
  /mavros/fake_gps/use_vision: False
  /mavros/fcu_url: /dev/ttyACM0:57600
  /mavros/gcs_url: 
  /mavros/global_position/frame_id: map
  /mavros/global_position/rot_covariance: 99999.0
  /mavros/global_position/tf/child_frame_id: base_link
  /mavros/global_position/tf/frame_id: map
  /mavros/global_position/tf/global_frame_id: earth
  /mavros/global_position/tf/send: False
  /mavros/global_position/use_relative_alt: True
  /mavros/image/frame_id: px4flow
  /mavros/imu/angular_velocity_stdev: 0.000349065850399
  /mavros/imu/frame_id: base_link
  /mavros/imu/linear_acceleration_stdev: 0.0003
  /mavros/imu/magnetic_stdev: 0.0
  /mavros/imu/orientation_stdev: 1.0
  /mavros/local_position/frame_id: map
  /mavros/local_position/tf/child_frame_id: base_link
  /mavros/local_position/tf/frame_id: map
  /mavros/local_position/tf/send: False
  /mavros/local_position/tf/send_fcu: False
  /mavros/mission/pull_after_gcs: True
  /mavros/mocap/use_pose: True
  /mavros/mocap/use_tf: False
  /mavros/odometry/estimator_type: 3
  /mavros/odometry/frame_tf/desired_frame: ned
  /mavros/plugin_blacklist: ['safety_area', '...
  /mavros/plugin_whitelist: []
  /mavros/px4flow/frame_id: px4flow
  /mavros/px4flow/ranger_fov: 0.118682389136
  /mavros/px4flow/ranger_max_range: 5.0
  /mavros/px4flow/ranger_min_range: 0.3
  /mavros/safety_area/p1/x: 1.0
  /mavros/safety_area/p1/y: 1.0
  /mavros/safety_area/p1/z: 1.0
  /mavros/safety_area/p2/x: -1.0
  /mavros/safety_area/p2/y: -1.0
  /mavros/safety_area/p2/z: -1.0
  /mavros/setpoint_accel/send_force: False
  /mavros/setpoint_attitude/reverse_thrust: False
  /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
  /mavros/setpoint_attitude/tf/frame_id: map
  /mavros/setpoint_attitude/tf/listen: False
  /mavros/setpoint_attitude/tf/rate_limit: 50.0
  /mavros/setpoint_attitude/use_quaternion: False
  /mavros/setpoint_position/tf/child_frame_id: target_position
  /mavros/setpoint_position/tf/frame_id: map
  /mavros/setpoint_position/tf/listen: False
  /mavros/setpoint_position/tf/rate_limit: 50.0
  /mavros/startup_px4_usb_quirk: True
  /mavros/sys/disable_diag: False
  /mavros/sys/min_voltage: 10.0
  /mavros/target_component_id: 1
  /mavros/target_system_id: 1
  /mavros/tdr_radio/low_rssi: 40
  /mavros/time/time_ref_source: fcu
  /mavros/time/timesync_avg_alpha: 0.6
  /mavros/time/timesync_mode: MAVLINK
  /mavros/vibration/frame_id: base_link
  /mavros/vision_pose/tf/child_frame_id: vision_estimate
  /mavros/vision_pose/tf/frame_id: map
  /mavros/vision_pose/tf/listen: False
  /mavros/vision_pose/tf/rate_limit: 10.0
  /mavros/vision_speed/listen_twist: False
  /rosdistro: kinetic
  /rosversion: 1.12.7
NODES
  /
    mavros (mavros/mavros_node)
auto-starting new master
process[master]: started with pid [10622]
ROS_MASTER_URI=http://localhost:11311
setting /run_id to 8e55979a-b7c1-11e7-9333-54ab3af70fe5
process[rosout-1]: started with pid [10635]
started core service [/rosout]
process[mavros-2]: started with pid [10653]
[FATAL] [1508742760.794537524]: UAS: GeographicLib exception: File not readable /usr/share/GeographicLib/geoids/egm96-5.pgm | Run install_geographiclib_dataset.sh script in order to install Geoid Model dataset!
================================================================================REQUIRED process [mavros-2] has died!
process has finished cleanly
log file: /home/abdularis/.ros/log/8e55979a-b7c1-11e7-9333-54ab3af70fe5/mavros-2*.log
Initiating shutdown!
================================================================================
[mavros-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by vooon** [comment]
https://github.com/mavlink/mavros/blob/master/mavros/README.md#required-dependencies
