### ISSUE TITLE
How to interpret cam_imu_stamp?

### ISSUE THREAD

**Issue by Changliu52** [mavlink/mavros#857]
Hi @mhkabir,
I was trying to do camera-imu hardware sync for vins_mono.
I made sure the camera is in external trigger mode and px4 (pixracer 1.6.5) enabled camera trigger following https://dev.px4.io/en/tutorials/camera_trigger.html. I also carefully modified the camera driver to match the image frame sequence with the cam_imu_stamp sequence, then overwrite the image frame stamp by the cam_imu_stamp + 0.5 exposure time. (https://github.com/Changliu52/ueye_cam)

However, from the test, the odometry is much worse than the unsyncronized setup with exactly the same hardware, in fact, most time failed. I suspect there must be something wrong fundamentally. Is there a time offset I need to include between cam_imu_stamp and imu timestamp?

Please give some advice.

Thanks

**Comment by Changliu52** [comment]
In your ueye nodelet example: https://github.com/ProjectArtemis/ueye_cam/blob/artemis-devel/src/ueye_cam_nodelet.cpp#L1230, the way you over write the timestamp really doesn't make sense. It looks like you are accumulating the cam_imu_stamp in each iteration. This doesn't seem to work for me either. I am really confused....

@mhkabir Please help.

**Comment by Changliu52** [comment]
My bad... at startup, there was always one image in the ueye buffer, which causes one frame shift for sequence matching. I can confirm the mavros sync was perfectly done!

**Comment by mhkabir** [comment]
:) Awesome!

**Comment by Changliu52** [comment]
https://youtu.be/afJtmZv1gT8 a quick link to the performance. Really great performance!
