### ISSUE TITLE
global_position/local odometry cannot be shown in RViz.

### ISSUE THREAD

**Issue by pavloblindnology** [mavlink/mavros#859]
Due to the NANs in angular twist, the global_position/local odometry message cannot be shown in RViz (saying "Message contained invalid floating point values (nans or infs)").
https://github.com/mavlink/mavros/blob/c6775a7b18b13d8c1e4671c41f6a63ffdaa48916/mavros/src/plugins/global_position.cpp#L285

**Comment by TSC21** [comment]
If you delete lines 285 and 286 and recompile, does it work?

**Comment by pavloblindnology** [comment]
I changed NANs to zeroes and it worked.

**Comment by TSC21** [comment]
Ok can you please issue a PR with the change so we can merge it? Thanks

**Comment by pavloblindnology** [comment]
Ok
