### ISSUE TITLE
Error build package when install mavros

### ISSUE THREAD

**Issue by lp02781** [mavlink/mavros#873]
i have some problems, when i try to install mavros on ubuntu 16.04 ROS kinetic, there error in build package like in ss. what must i do??

![screenshot from 2017-11-27 11-09-59](https://user-images.githubusercontent.com/23095475/33250518-8fd03234-d363-11e7-99db-f9df8cb2895b.png)

**Comment by TSC21** [comment]
Are you running a VM? That seems a problem with low RAM or swap space. This is not an issue directly related with MAVROS. Try increasing the swap space or follow https://www.cyberciti.biz/faq/linux-add-a-swap-file-howto/

**Comment by lp02781** [comment]
thank for your advice

**Comment by lp02781** [comment]
i'm not use VM, i'm using dual boot windows 8 and ubuntu 16.04, i'm installing ubuntu not as swap partition, but as extent partition, that give effect for my ubuntu??

**Comment by vooon** [comment]
Please show `free -h` and `lscpu` (copy text and place inside \`\`\` code block).

**Comment by vooon** [comment]
4 GiB of RAM is too low to run 4 GCC simultaneously (yes C++ take lots of RAM, ~1-1.5G for each process).
You should add swap partition or file, it is necessary when RAM < 6-8G (and still recommended to have small area even if you have more ram).

Quick way to add swap file:
```sh
sudo fallocate -l 6G /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
```

But swapping may cause that system will be very slow, limitation number of parallel jobs may help.
Try add flag `-j3` to `catkin build`.
