### ISSUE TITLE
Some MAVROS data not coming

### ISSUE THREAD

**Issue by TrishantRoy** [mavlink/mavros#887]
Hey,

### Issue details
After connecting, only the /mavros/imu/ is sending data. Others aren't coming.

### MAVROS version and platform

Mavros: How to check? Did sudo apt-get install ros-indigo-mavros ros-indigo-mavros-extras
ROS: Indigo
Ubuntu: 14.04

### Autopilot type and version
PX4
Version: 3.5.4
Pixhawk 2.1

### Node logs

```
copy output of mavros_node. Usually console where you run roslaunch
```
trishantroy@EurusHolmes:~$ roslaunch mavros px4.launch fcu_url:=/dev/ttyACM0:921600
... logging to /home/trishantroy/.ros/log/6c3db59c-df27-11e7-a420-2c6e8522ef61/roslaunch-EurusHolmes-24137.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://EurusHolmes:41020/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: ROLL_180
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: ROLL_180
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fcu_url: /dev/ttyACM0:921600
 * /mavros/gcs_url: 
 * /mavros/global_position/frame_id: fcu
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: fcu_utm
 * /mavros/global_position/tf/frame_id: local_origin
 * /mavros/global_position/tf/send: False
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: fcu
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: fcu
 * /mavros/local_position/tf/child_frame_id: fcu
 * /mavros/local_position/tf/frame_id: local_origin
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.0
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_throttle: False
 * /mavros/setpoint_attitude/tf/child_frame_id: attitude
 * /mavros/setpoint_attitude/tf/frame_id: local_origin
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 10.0
 * /mavros/setpoint_position/tf/child_frame_id: setpoint
 * /mavros/setpoint_position/tf/frame_id: local_origin
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/vibration/frame_id: vibration
 * /mavros/vision_pose/tf/child_frame_id: vision
 * /mavros/vision_pose/tf/frame_id: local_origin
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    mavros (mavros/mavros_node)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[mavros-1]: started with pid [24156]
[ INFO] [1513155439.306708196]: FCU URL: /dev/ttyACM0:921600
[ INFO] [1513155439.306874971]: serial0: device: /dev/ttyACM0 @ 921600 bps
[ INFO] [1513155439.307249000]: GCS bridge disabled
[ INFO] [1513155439.341342315]: Plugin 3dr_radio loaded and initialized
[ INFO] [1513155439.344205275]: Plugin actuator_control loaded and initialized
[ INFO] [1513155439.345221764]: Plugin altitude loaded and initialized
[ INFO] [1513155439.390669307]: Plugin cam_imu_sync loaded and initialized
[ INFO] [1513155439.395442377]: Plugin command loaded and initialized
[ INFO] [1513155439.395487905]: Plugin distance_sensor blacklisted
[ INFO] [1513155439.401624205]: Plugin ftp loaded and initialized
[ INFO] [1513155439.409763476]: Plugin global_position loaded and initialized
[ INFO] [1513155439.410414656]: Plugin hil_controls loaded and initialized
[ INFO] [1513155439.410445916]: Plugin image_pub blacklisted
[ INFO] [1513155439.417922694]: Plugin imu_pub loaded and initialized
[ INFO] [1513155439.429217571]: Plugin local_position loaded and initialized
[ INFO] [1513155439.429814687]: Plugin manual_control loaded and initialized
[ INFO] [1513155439.433794842]: Plugin mocap_pose_estimate loaded and initialized
[ INFO] [1513155439.436003208]: Plugin param loaded and initialized
[ INFO] [1513155439.441381270]: Plugin px4flow loaded and initialized
[ INFO] [1513155439.444858800]: Plugin rc_io loaded and initialized
[ INFO] [1513155439.444920282]: Plugin safety_area blacklisted
[ INFO] [1513155439.447924740]: Plugin setpoint_accel loaded and initialized
[ INFO] [1513155439.461222315]: Plugin setpoint_attitude loaded and initialized
[ INFO] [1513155439.466670033]: Plugin setpoint_position loaded and initialized
[ INFO] [1513155439.475281878]: Plugin setpoint_raw loaded and initialized
[ INFO] [1513155439.477653604]: Plugin setpoint_velocity loaded and initialized
[ INFO] [1513155439.484058274]: Plugin sys_status loaded and initialized
[ INFO] [1513155439.488237253]: Plugin sys_time loaded and initialized
[ INFO] [1513155439.489355053]: Plugin vfr_hud loaded and initialized
[ INFO] [1513155439.489390932]: Plugin vibration blacklisted
[ INFO] [1513155439.496883900]: Plugin vision_pose_estimate loaded and initialized
[ INFO] [1513155439.500010512]: Plugin vision_speed_estimate loaded and initialized
[ INFO] [1513155439.503499189]: Plugin waypoint loaded and initialized
[ INFO] [1513155439.503542062]: Autostarting mavlink via USB on PX4
[ INFO] [1513155439.503572399]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1513155439.503582652]: Built-in MAVLink package version: 2016.5.20
[ INFO] [1513155439.503600542]: Built-in MAVLink dialect: ardupilotmega
[ INFO] [1513155439.503615443]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ WARN] [1513155439.592461670]: TM: Clock skew detected (-1513155434.904920101 s). Hard syncing clocks.
[ INFO] [1513155439.754618946]: CON: Got HEARTBEAT, connected. FCU: ArduPilotMega
[ INFO] [1513155439.922302779]: FCU: Initialising APM
[ INFO] [1513155440.775105702]: VER: 1.1: Capabilities 0x0000000000001bcf
[ INFO] [1513155440.775516531]: VER: 1.1: Flight software:     030504ff (284349c30384802e1bcae90b?Y)?)
[ INFO] [1513155440.775719955]: VER: 1.1: Middleware software: 00000000 (0384802e1bcae90b?Y)?)
[ INFO] [1513155440.775866366]: VER: 1.1: OS software:         00000000 (1bcae90b?Y)?)
[ INFO] [1513155440.776025534]: VER: 1.1: Board hardware:      00000000
[ INFO] [1513155440.776148209]: VER: 1.1: VID/PID: 0000:0000
[ INFO] [1513155440.776356000]: VER: 1.1: UID: 0000000000000000
[ WARN] [1513155440.776653528]: CMD: Unexpected command 520, result 0
[ INFO] [1513155440.783615530]: FCU: Calibrating barometer
[ INFO] [1513155442.402578951]: FCU: Barometer calibration complete
[ INFO] [1513155444.620962115]: FCU: EKF2 IMU0 initial yaw alignment complete
[ INFO] [1513155444.625863330]: FCU: EKF2 IMU1 initial yaw alignment complete
[ INFO] [1513155445.971803907]: FCU: EKF2 IMU1 tilt alignment complete
[ INFO] [1513155446.046765809]: FCU: EKF2 IMU0 tilt alignment complete
[ INFO] [1513155449.759468635]: FCU: APM:Copter V3.5.4 (284349c3)
[ INFO] [1513155449.759729100]: FCU: PX4: 0384802e NuttX: 1bcae90b
[ INFO] [1513155449.759883906]: FCU: Frame: QUAD
[ INFO] [1513155449.759932026]: FCU: PX4v3 00260033 30365110 35323931
[ INFO] [1513155454.759500136]: WP: mission received
[ INFO] [1513155458.806854821]: PR: parameters list received

### Diagnostics

```
place here result of:
rostopic echo -n1 /diagnostics
```
trishantroy@EurusHolmes:~$ rostopic echo -n1/diagnostics
Usage: rostopic echo [options] /topic

rostopic: error: topic must be specified

### Check ID

```
rosrun mavros checkid
```
trishantroy@EurusHolmes:~$ rosrun mavros checkid
OK. I got messages from 1:1.

---
Received 283 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 22, 74, 111, 178, 182, 30

**Comment by TSC21** [comment]
how can you have APM and PX4 running on the same board?

```
[ INFO] [1513155449.759468635]: FCU: APM:Copter V3.5.4 (284349c3)
[ INFO] [1513155449.759729100]: FCU: PX4: 0384802e NuttX: 1bcae90b
```

**Comment by TSC21** [comment]
Did you load the PX4 Firmware to the Pixhawk?

**Comment by vooon** [comment]
@TSC21 APM runs on top of PX4 components, so this is APM:Copter 3.5.4.
@TrishantRoy please place logs inside code blocks. Did you setup stream rate parameters (use GCS)?

Deb version: `dpkg --status ros-indigo-mavros`

**Comment by TrishantRoy** [comment]
@vooon I haven't set the stream parameters. Which of the parameters to set and to what value?

**Comment by vooon** [comment]
First try: `rosrun mavros rate --all 10` http://wiki.ros.org/mavros#mavsys

**Comment by TSC21** [comment]
> @TSC21 APM runs on top of PX4 components, so this is APM:Copter 3.5.4.

Ok I leave it to you then.

**Comment by TrishantRoy** [comment]
`trishantroy@EurusHolmes:~$ rosrun mavros rate --all 10
[rosrun] Couldn't find executable named rate below /opt/ros/indigo/share/mavros`

**Comment by khancyr** [comment]
rosrun mavros mavsys rate --all 10

**Comment by TrishantRoy** [comment]
Okay... Still not happening... Only IMU data is coming

Is there a problem with baud rate?

**Comment by TrishantRoy** [comment]
@vooon We can get data from PX4Flow as well, right?
That is the main data I want to get velocity.

**Comment by TrishantRoy** [comment]
Can you confirm?
Coz I need to use the OFS to get data when connected to Pixhawk.
