### ISSUE TITLE
joule with px4 can't change to Offboard mode

### ISSUE THREAD

**Issue by raywang-nx** [mavlink/mavros#894]
Now i change pixhawk to px4, but i can't make it to change to offboard mode, neither using RC or mavros.
when i run mavsetp, it shows something like this:

rosrun mavros mavsetp local -v 0 0 0 0
Requesting OFFBOARD mode...
OFFBOARD mode are set.

and 

[ WARN] [1513421776.805711484]: CMD: Unexpected command 176, result 1

but pixhawk's red light blinks for maybe 4 times, with buzzer rings 3 times, and can't change it to offboard.

i think i need to send several position to it before, but everything seems the same.

and someone said that after the drone fly in the sky, change to alt-hold(may be other name i guess), then change to offboard and success, but i manage to change to position mode , but fail to change to offboard with the same situation like this.

### MAVROS version and platform

Mavros: ros-kinetic-mavros is already the newest version (0.21.5-0xenial-20171201-081620-0800).

ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[  ] ArduPilot
[ x ] PX4

Version:  installed from latest qgc, maybe 1.7.0 i guess

### Node logs

joule@joule-570x-DVT3:~$ roslaunch mavros px4.launch 
... logging to /home/joule/.ros/log/97af8a86-e24f-11e7-ad78-f78ca70923e1/roslaunch-joule-570x-DVT3-7754.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://joule-570x-DVT3:36437/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 10.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: ROLL_180
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: ROLL_180
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_url: /dev/ttyS1:921600
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/estimator_type: 3
 * /mavros/odometry/frame_tf/desired_frame: ned
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682389136
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.12

NODES
  /
    mavros (mavros/mavros_node)

auto-starting new master
process[master]: started with pid [7765]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 97af8a86-e24f-11e7-ad78-f78ca70923e1
process[rosout-1]: started with pid [7779]
started core service [/rosout]
process[mavros-2]: started with pid [7797]
[ INFO] [1513421714.643147521]: FCU URL: /dev/ttyS1:921600
[ WARN] [1513421714.644168217]: init: message from ASLUAV, MSG-ID 201 ignored! Table has different entry.
[ WARN] [1513421714.644518264]: init: message from autoquad, MSG-ID 150 ignored! Table has different entry.
[ WARN] [1513421714.644565190]: init: message from autoquad, MSG-ID 152 ignored! Table has different entry.
[ WARN] [1513421714.644838158]: init: message from matrixpilot, MSG-ID 150 ignored! Table has different entry.
[ WARN] [1513421714.644875178]: init: message from matrixpilot, MSG-ID 151 ignored! Table has different entry.
[ WARN] [1513421714.644909148]: init: message from matrixpilot, MSG-ID 152 ignored! Table has different entry.
[ WARN] [1513421714.644940410]: init: message from matrixpilot, MSG-ID 153 ignored! Table has different entry.
[ WARN] [1513421714.644968149]: init: message from matrixpilot, MSG-ID 155 ignored! Table has different entry.
[ WARN] [1513421714.644996873]: init: message from matrixpilot, MSG-ID 156 ignored! Table has different entry.
[ WARN] [1513421714.645029195]: init: message from matrixpilot, MSG-ID 157 ignored! Table has different entry.
[ WARN] [1513421714.645060320]: init: message from matrixpilot, MSG-ID 158 ignored! Table has different entry.
[ WARN] [1513421714.645093739]: init: message from matrixpilot, MSG-ID 170 ignored! Table has different entry.
[ WARN] [1513421714.645126231]: init: message from matrixpilot, MSG-ID 171 ignored! Table has different entry.
[ WARN] [1513421714.645156685]: init: message from matrixpilot, MSG-ID 172 ignored! Table has different entry.
[ WARN] [1513421714.645185980]: init: message from matrixpilot, MSG-ID 173 ignored! Table has different entry.
[ WARN] [1513421714.645225005]: init: message from matrixpilot, MSG-ID 174 ignored! Table has different entry.
[ WARN] [1513421714.645265061]: init: message from matrixpilot, MSG-ID 175 ignored! Table has different entry.
[ WARN] [1513421714.645304846]: init: message from matrixpilot, MSG-ID 176 ignored! Table has different entry.
[ WARN] [1513421714.645343880]: init: message from matrixpilot, MSG-ID 177 ignored! Table has different entry.
[ WARN] [1513421714.645383153]: init: message from matrixpilot, MSG-ID 178 ignored! Table has different entry.
[ WARN] [1513421714.645421557]: init: message from matrixpilot, MSG-ID 179 ignored! Table has different entry.
[ WARN] [1513421714.645462192]: init: message from matrixpilot, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1513421714.645500841]: init: message from matrixpilot, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1513421714.645539889]: init: message from matrixpilot, MSG-ID 182 ignored! Table has different entry.
[ WARN] [1513421714.645598643]: init: message from matrixpilot, MSG-ID 183 ignored! Table has different entry.
[ WARN] [1513421714.645639971]: init: message from matrixpilot, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1513421714.645680640]: init: message from matrixpilot, MSG-ID 185 ignored! Table has different entry.
[ WARN] [1513421714.645722533]: init: message from matrixpilot, MSG-ID 186 ignored! Table has different entry.
[ WARN] [1513421714.645971994]: init: message from paparazzi, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1513421714.646009468]: init: message from paparazzi, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1513421714.646044315]: init: message from paparazzi, MSG-ID 182 ignored! Table has different entry.
[ WARN] [1513421714.646080673]: init: message from paparazzi, MSG-ID 183 ignored! Table has different entry.
[ WARN] [1513421714.646119824]: init: message from paparazzi, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1513421714.646356285]: init: message from slugs, MSG-ID 170 ignored! Table has different entry.
[ WARN] [1513421714.646393755]: init: message from slugs, MSG-ID 172 ignored! Table has different entry.
[ WARN] [1513421714.646427295]: init: message from slugs, MSG-ID 173 ignored! Table has different entry.
[ WARN] [1513421714.646466734]: init: message from slugs, MSG-ID 176 ignored! Table has different entry.
[ WARN] [1513421714.646505500]: init: message from slugs, MSG-ID 177 ignored! Table has different entry.
[ WARN] [1513421714.646546905]: init: message from slugs, MSG-ID 179 ignored! Table has different entry.
[ WARN] [1513421714.646606419]: init: message from slugs, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1513421714.646648135]: init: message from slugs, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1513421714.646687256]: init: message from slugs, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1513421714.646724096]: init: message from slugs, MSG-ID 185 ignored! Table has different entry.
[ WARN] [1513421714.646761282]: init: message from slugs, MSG-ID 186 ignored! Table has different entry.
[ WARN] [1513421714.646799051]: init: message from slugs, MSG-ID 188 ignored! Table has different entry.
[ WARN] [1513421714.646839739]: init: message from slugs, MSG-ID 191 ignored! Table has different entry.
[ WARN] [1513421714.646878249]: init: message from slugs, MSG-ID 192 ignored! Table has different entry.
[ WARN] [1513421714.646914168]: init: message from slugs, MSG-ID 193 ignored! Table has different entry.
[ WARN] [1513421714.646952666]: init: message from slugs, MSG-ID 194 ignored! Table has different entry.
[ INFO] [1513421714.647525415]: serial0: device: /dev/ttyS1 @ 921600 bps
[ INFO] [1513421714.749760698]: GCS bridge disabled
[ INFO] [1513421714.846258997]: Plugin 3dr_radio loaded
[ INFO] [1513421714.853044009]: Plugin 3dr_radio initialized
[ INFO] [1513421714.853514594]: Plugin actuator_control loaded
[ INFO] [1513421714.869312803]: Plugin actuator_control initialized
[ INFO] [1513421714.939124362]: Plugin adsb loaded
[ INFO] [1513421714.954767112]: Plugin adsb initialized
[ INFO] [1513421714.955165092]: Plugin altitude loaded
[ INFO] [1513421714.959875592]: Plugin altitude initialized
[ INFO] [1513421714.960267323]: Plugin cam_imu_sync loaded
[ INFO] [1513421714.963795369]: Plugin cam_imu_sync initialized
[ INFO] [1513421714.964314955]: Plugin command loaded
[ INFO] [1513421714.988554850]: Plugin command initialized
[ INFO] [1513421714.989040162]: Plugin debug_value loaded
[ INFO] [1513421715.012704734]: Plugin debug_value initialized
[ INFO] [1513421715.012828291]: Plugin distance_sensor blacklisted
[ INFO] [1513421715.013197957]: Plugin fake_gps loaded
[ INFO] [1513421715.075287365]: Plugin fake_gps initialized
[ INFO] [1513421715.075843331]: Plugin ftp loaded
[ INFO] [1513421715.110856112]: Plugin ftp initialized
[ INFO] [1513421715.111287306]: Plugin global_position loaded
[ INFO] [1513421715.183165512]: Plugin global_position initialized
[ INFO] [1513421715.183829322]: Plugin hil loaded
[ INFO] [1513421715.249026870]: Plugin hil initialized
[ INFO] [1513421715.249731698]: Plugin home_position loaded
[ INFO] [1513421715.278049774]: Plugin home_position initialized
[ INFO] [1513421715.278987481]: Plugin imu loaded
[ INFO] [1513421715.317085232]: Plugin imu initialized
[ INFO] [1513421715.317496930]: Plugin local_position loaded
[ INFO] [1513421715.343959928]: Plugin local_position initialized
[ INFO] [1513421715.344417705]: Plugin manual_control loaded
[ INFO] [1513421715.351011920]: Plugin manual_control initialized
[ INFO] [1513421715.351711326]: Plugin mocap_pose_estimate loaded
[ INFO] [1513421715.369355214]: Plugin mocap_pose_estimate initialized
[ INFO] [1513421715.369750237]: Plugin odom loaded
[ INFO] [1513421715.395333065]: Plugin odom initialized
[ INFO] [1513421715.396018728]: Plugin param loaded
[ INFO] [1513421715.415065249]: Plugin param initialized
[ INFO] [1513421715.415654572]: Plugin px4flow loaded
[ INFO] [1513421715.441735175]: Plugin px4flow initialized
[ INFO] [1513421715.441834209]: Plugin rangefinder blacklisted
[ INFO] [1513421715.442296809]: Plugin rc_io loaded
[ INFO] [1513421715.460979701]: Plugin rc_io initialized
[ INFO] [1513421715.461092374]: Plugin safety_area blacklisted
[ INFO] [1513421715.461521245]: Plugin setpoint_accel loaded
[ INFO] [1513421715.477961440]: Plugin setpoint_accel initialized
[ INFO] [1513421715.478766357]: Plugin setpoint_attitude loaded
[ INFO] [1513421715.531463609]: Plugin setpoint_attitude initialized
[ INFO] [1513421715.531998297]: Plugin setpoint_position loaded
[ INFO] [1513421715.559800079]: Plugin setpoint_position initialized
[ INFO] [1513421715.560306408]: Plugin setpoint_raw loaded
[ INFO] [1513421715.604669037]: Plugin setpoint_raw initialized
[ INFO] [1513421715.605268068]: Plugin setpoint_velocity loaded
[ INFO] [1513421715.625312491]: Plugin setpoint_velocity initialized
[ INFO] [1513421715.625991107]: Plugin sys_status loaded
[ INFO] [1513421715.653044817]: Plugin sys_status initialized
[ INFO] [1513421715.653423399]: Plugin sys_time loaded
[ INFO] [1513421715.668205487]: TM: Timesync mode: MAVLINK
[ INFO] [1513421715.670823546]: Plugin sys_time initialized
[ INFO] [1513421715.671209517]: Plugin vfr_hud loaded
[ INFO] [1513421715.676822411]: Plugin vfr_hud initialized
[ INFO] [1513421715.676923354]: Plugin vibration blacklisted
[ INFO] [1513421715.677273742]: Plugin vision_pose_estimate loaded
[ INFO] [1513421715.711217773]: Plugin vision_pose_estimate initialized
[ INFO] [1513421715.711748036]: Plugin vision_speed_estimate loaded
[ INFO] [1513421715.725896476]: Plugin vision_speed_estimate initialized
[ INFO] [1513421715.726338428]: Plugin waypoint loaded
[ INFO] [1513421715.748986110]: Plugin waypoint initialized
[ INFO] [1513421715.749132939]: Autostarting mavlink via USB on PX4
[ INFO] [1513421715.749227329]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1513421715.749300477]: Built-in MAVLink package version: 2017.11.11
[ INFO] [1513421715.749367475]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1513421715.749455249]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ INFO] [1513421715.754745582]: IMU: Attitude quaternion IMU detected!
[ INFO] [1513421715.761287832]: RC_CHANNELS message detected!
[ INFO] [1513421715.768812941]: IMU: High resolution IMU detected!
[ WARN] [1513421715.890978814]: GP: No GPS fix
[ INFO] [1513421716.672160908]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1513421716.675391810]: IMU: Attitude quaternion IMU detected!
[ INFO] [1513421716.689627816]: IMU: High resolution IMU detected!
[ INFO] [1513421716.714215919]: RC_CHANNELS message detected!
[ INFO] [1513421717.684120107]: VER: 1.1: Capabilities         0x000000000000e4ef
[ INFO] [1513421717.684232515]: VER: 1.1: Flight software:     010700ff (000000006109C1EA)
[ INFO] [1513421717.684297607]: VER: 1.1: Middleware software: 010700ff (000000006109C1EA)
[ INFO] [1513421717.684349567]: VER: 1.1: OS software:         071600ff (0000000000000000)
[ INFO] [1513421717.684399337]: VER: 1.1: Board hardware:      00000011
[ INFO] [1513421717.684479192]: VER: 1.1: VID/PID:             26ac:0011
[ INFO] [1513421717.684525698]: VER: 1.1: UID:                 3536511737353630
[ WARN] [1513421717.685317695]: CMD: Unexpected command 520, result 0
[ INFO] [1513421726.673524094]: HP: requesting home position
[ WARN] [1513421731.017511350]: PR: request param #245 timeout, retries left 2, and 15 params still missing
[ INFO] [1513421731.679955869]: WP: mission received
[ WARN] [1513421732.024286988]: PR: request param #246 timeout, retries left 2, and 14 params still missing
[ WARN] [1513421733.030464516]: PR: request param #247 timeout, retries left 2, and 13 params still missing
[ WARN] [1513421734.034328952]: PR: request param #422 timeout, retries left 2, and 12 params still missing
[ WARN] [1513421735.038416373]: PR: request param #423 timeout, retries left 2, and 11 params still missing
[ WARN] [1513421736.042169099]: PR: request param #424 timeout, retries left 2, and 10 params still missing
[ INFO] [1513421736.673570105]: HP: requesting home position
[ WARN] [1513421737.047979110]: PR: request param #434 timeout, retries left 2, and 9 params still missing
[ WARN] [1513421738.053163586]: PR: request param #435 timeout, retries left 2, and 8 params still missing
[ WARN] [1513421739.058911783]: PR: request param #436 timeout, retries left 2, and 7 params still missing
[ WARN] [1513421740.069401170]: PR: request param #437 timeout, retries left 2, and 6 params still missing
[ WARN] [1513421741.076240946]: PR: request param #438 timeout, retries left 2, and 5 params still missing
[ WARN] [1513421742.079508764]: PR: request param #439 timeout, retries left 2, and 4 params still missing
[ WARN] [1513421743.085368077]: PR: request param #719 timeout, retries left 2, and 3 params still missing
[ WARN] [1513421744.092100517]: PR: request param #720 timeout, retries left 2, and 2 params still missing
[ WARN] [1513421745.096748833]: PR: request param #721 timeout, retries left 2, and 1 params still missing
[ WARN] [1513421746.087828035]: GP: No GPS fix
[ INFO] [1513421746.673530002]: HP: requesting home position

### Diagnostics

joule@joule-570x-DVT3:~$ rostopic echo -n1 /diagnostics
header: 
  seq: 58
  stamp: 
    secs: 1513421784
    nsecs: 750998711
  frame_id: ''
status: 
  - 
    level: 0
    name: "mavros: FCU connection"
    message: "connected"
    hardware_id: "/dev/ttyS1:921600"
    values: 
      - 
        key: "Received packets:"
        value: "25624"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "137"
      - 
        key: "Tx sequence number:"
        value: "192"
      - 
        key: "Rx total bytes:"
        value: "1058882"
      - 
        key: "Tx total bytes:"
        value: "30409"
      - 
        key: "Rx speed:"
        value: "14744.000000"
      - 
        key: "Tx speed:"
        value: "430.000000"
  - 
    level: 2
    name: "mavros: GPS"
    message: "No satellites"
    hardware_id: "/dev/ttyS1:921600"
    values: 
      - 
        key: "Satellites visible"
        value: "0"
      - 
        key: "Fix type"
        value: "0"
      - 
        key: "EPH (m)"
        value: "99.99"
      - 
        key: "EPV (m)"
        value: "99.99"
  - 
    level: 0
    name: "mavros: Heartbeat"
    message: "Normal"
    hardware_id: "/dev/ttyS1:921600"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "69"
      - 
        key: "Frequency (Hz)"
        value: "1.000019"
      - 
        key: "Vehicle type"
        value: "Quadrotor"
      - 
        key: "Autopilot type"
        value: "PX4 Autopilot"
      - 
        key: "Mode"
        value: "STABILIZED"
      - 
        key: "System status"
        value: "Standby"
  - 
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "/dev/ttyS1:921600"
    values: 
      - 
        key: "Sensor present"
        value: "0x00000000"
      - 
        key: "Sensor enabled"
        value: "0x00000000"
      - 
        key: "Sensor helth"
        value: "0x00000000"
      - 
        key: "CPU Load (%)"
        value: "61.6"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 0
    name: "mavros: Battery"
    message: "Normal"
    hardware_id: "/dev/ttyS1:921600"
    values: 
      - 
        key: "Voltage"
        value: "65.54"
      - 
        key: "Current"
        value: "-0.0"
      - 
        key: "Remaining"
        value: "-1.0"
---

### Check ID

joule@joule-570x-DVT3:~$ rosrun mavros checkid
OK. I got messages from 1:1.

---
Received 5474 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 1, 2, 140, 141, 147, 24, 30, 31, 32, 36, 65, 70, 74, 76, 77, 87, 230, 231, 105, 111, 241, 245

**Comment by TSC21** [comment]
`mavsetp` won't work the way you expect (it actually requires an update). Reade the offboard docs on the PX4 devguide and you will see you are missing something critical: you are not sending a stream of setpoints to the board before changing to Offboard mode. That'a why it does not change mode.

**Comment by raywang-nx** [comment]
@TSC21 thanks a lot, now i understand what means setpoints, i am able to make it to the Offboard mode by publish /mavros/setpoint plugins, really appreciate!
