### ISSUE TITLE
odom plugin tf not working

### ISSUE THREAD

**Issue by ChristophTobler** [mavlink/mavros#901]
When running mavros and publishing to `mavros/odometry/odom` with a VIO, I get
```
[ WARN] [10897.423774037]: odom: Invalid argument passed to lookupTransform argument target_frame in tf2 frame_ids cannot be empty
```
all the time. So I just hard coded https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/odom.cpp#L80-L82 to https://github.com/mavlink/mavros/blob/master/mavros/src/lib/uas_data.cpp#L55-L56

Am I missing something?

**Comment by TSC21** [comment]
@jgoppert ^

**Comment by ChristophTobler** [comment]
The issue was that I didn't set `frame_id` and `child_frame_id` in the odometry msg that the transform is looking for...
