### ISSUE TITLE
Increase rate of data tansfer of mavros package

### ISSUE THREAD

**Issue by TrishantRoy** [mavlink/mavros#902]
Hey,
I am using mavros package to communicate to Pixhawk 2.1 connected using radio telemetry.

I am getting data at around 2 Hz.

How to increase this rate?
What is the apm_pluginlists.yaml used for?
Will less data be transferred if I add some topics in the blacklist region?

Thanks.

**Comment by vooon** [comment]
It only selects what plugins to load at startup. That not affect messages.
Try `rosrun mavros mavsys rate --all 10`.

**Comment by TrishantRoy** [comment]
Yup.... Rate has increased.... Have tried with only imu data... Will try with other as well.

Thanks @vooon
