### ISSUE TITLE
[Question] Protocol v1.0 or v2.0

### ISSUE THREAD

**Issue by tuloski** [mavlink/mavros#904]
I wasn't able to understand if MAVros sends messages using protocol v1.0 or v2.0 or I can chose it?
If I can chose it how do I do it? Is it at compile time?

**Comment by vooon** [comment]
You can select by `~fcu_protocol` parameter. http://wiki.ros.org/mavros#Parameters

But actually that only change messages that mavros send to FCU, it understand both versions on input.
