### ISSUE TITLE
/rc/override data when using Gazebo 

### ISSUE THREAD

**Issue by TrishantRoy** [mavlink/mavros#907]
Hello,
I want to simulate some codes on a quad in Gazebo.

After connecting to the Gazebo, I am unable to publish on the /mavros/rc/override topic.

I was able to publish when trying on the actual quad.

Thanks.

**Comment by TSC21** [comment]
Are you using APM SITL or PX4 SITL? Cause PX4 SITL doesn't process RC override msgs. So you will have to use setpoint msgs instead or direct actuator controls.

**Comment by TrishantRoy** [comment]
I am using PX4 SITL.

Didn't know that RC override msgs aren't processed.

Then, I will use the APM SITL. The feature is available in APM, right?

Thanks.

**Comment by TSC21** [comment]
I don't know. That depends on the SITL implementation.
