### ISSUE TITLE
test_mavros/launch/px4/iris_empty_world_offboard_ctl.launch issue

### ISSUE THREAD

**Issue by FaboNo** [mavlink/mavros#913]
I am trying to use the test file you have created to run with px4 and a model from the package Rotors (from ethz-asl) 
Actually I created a watkin_ws including Rotors, Firmware (px4), mavros and mavlink
Then catkin build without errors

then from catkin_ws: 
roslaunch src/mavros/test_mavros/launch/px4/iris_empty_world_offboard_ctl.launch

it appears (see below) that the some executables (manual_input, commander, mc_mixer, attitude_estimator, mc_att_control and mavlink) are not created during the catkin build process.

However, after checking the Firmware CMakeList I do not see how to generate them, do you have any suggestion or do I have to post on px4/Firmware?

Thank you very much for you advice

Fabrice
----

### Issue details

xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
redefining global property: pi
when processing file: /home/fabrice/catkin_demo_ws/src/rotors_simulator/rotors_description/urdf/iris_base.xacro
xacro.py is deprecated; please use xacro instead
started roslaunch server http://fabrice-N650DU:45133/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/
 * /sitl_test_offboard_ctl/

PARAMETERS
 * /iris/MPP_XY_FF: 0.0
 * /iris/MPP_XY_P: 1.0
 * /iris/MPP_XY_VEL_D: 0.01
 * /iris/MPP_XY_VEL_I: 0.0
 * /iris/MPP_XY_VEL_MAX: 2.0
 * /iris/MPP_XY_VEL_P: 0.01
 * /iris/MPP_Z_P: 2.0
 * /iris/MPP_Z_VEL_P: 0.3
 * /iris/mavlink/mavlink_fcu_url: udp://localhost:1...
 * /iris/mixer: i
 * /iris/robot_description: <?xml version="1....
 * /iris/tf_prefix: 
 * /iris/vehicle_model: iris
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: ROLL_180
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: ROLL_180
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_url: udp://localhost:1...
 * /mavros/gcs_url: 
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/estimator_type: 3
 * /mavros/odometry/frame_tf/desired_frame: ned
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682389136
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.7
 * /sitl_test_offboard_ctl/linvel_d_gain: 0.12
 * /sitl_test_offboard_ctl/linvel_i_gain: 0.05
 * /sitl_test_offboard_ctl/linvel_i_max: 0.1
 * /sitl_test_offboard_ctl/linvel_i_min: -0.1
 * /sitl_test_offboard_ctl/linvel_p_gain: 0.4
 * /sitl_test_offboard_ctl/mode: position
 * /sitl_test_offboard_ctl/num_of_tests: 1
 * /sitl_test_offboard_ctl/rate: 10.0
 * /sitl_test_offboard_ctl/shape: square
 * /sitl_test_offboard_ctl/use_pid: True
 * /sitl_test_offboard_ctl/yawrate_d_gain: 0.12
 * /sitl_test_offboard_ctl/yawrate_i_gain: 0.00058
 * /sitl_test_offboard_ctl/yawrate_i_max: 0.005
 * /sitl_test_offboard_ctl/yawrate_i_min: -0.005
 * /sitl_test_offboard_ctl/yawrate_p_gain: 0.011
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    mavros (mavros/mavros_node)
    sitl_test_offboard_ctl (test_mavros/sitl_test_node)
  /iris/
    attitude_estimator (px4/attitude_estimator)
    commander (px4/commander)
    joy_node (joy/joy_node)
    manual_input (px4/manual_input)
    mavlink (px4/mavlink)
    mc_att_control (px4/mc_att_control)
    mc_mixer (px4/mc_mixer)
    mc_pos_control (px4/mc_pos_control)
    position_estimator (px4/position_estimator)
    spawn_iris (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [17523]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 4189591e-f197-11e7-8903-b0359f2c094d
process[rosout-1]: started with pid [17536]
started core service [/rosout]
process[gazebo-2]: started with pid [17562]
process[gazebo_gui-3]: started with pid [17567]
process[iris/spawn_iris-4]: started with pid [17572]
process[iris/joy_node-5]: started with pid [17573]
[ERROR] [1515101761.247495687]: Couldn't open joystick /dev/input/js0. Will retry every second.
ERROR: cannot launch node of type [px4/manual_input]: can't locate node [manual_input] in package [px4]
**ERROR: cannot launch node of type [px4/commander]: can't locate node [commander] in package [px4]
ERROR: cannot launch node of type [px4/mc_mixer]: can't locate node [mc_mixer] in package [px4]
ERROR: cannot launch node of type [px4/attitude_estimator]: can't locate node [attitude_estimator] in package [px4]
ERROR: cannot launch node of type [px4/position_estimator]: can't locate node [position_estimator] in package [px4]
ERROR: cannot launch node of type [px4/mc_att_control]: can't locate node [mc_att_control] in package [px4]**
SpawnModel script started
ERROR: cannot launch node of type [px4/mc_pos_control]: can't locate node [mc_pos_control] in package [px4]
[ INFO] [1515101761.766534928]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1515101761.767330901]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
ERROR: cannot launch node of type [px4/mavlink]: can't locate node [mavlink] in package [px4]
process[mavros-14]: started with pid [17690]
process[sitl_test_offboard_ctl-15]: started with pid [17691]
[ INFO] [1515101761.853388919]: SITL Test node started...
[INFO] [1515101761.893862, 0.000000]: Loading model XML from ros parameter
[INFO] [1515101761.897214, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ERROR] [1515101761.916984723]: Tried to advertise a service that is already advertised in this node [/pid/set_parameters]
[ERROR] [1515101761.933097201]: Tried to advertise a service that is already advertised in this node [/pid/set_parameters]
[ INFO] [1515101761.952557109]: FCU URL: udp://localhost:14560@localhost:14565
[ WARN] [1515101761.953425731]: init: message from ASLUAV, MSG-ID 201 ignored! Table has different entry.
[ WARN] [1515101761.953580268]: init: message from autoquad, MSG-ID 150 ignored! Table has different entry.
[ WARN] [1515101761.953590629]: init: message from autoquad, MSG-ID 152 ignored! Table has different entry.
[ WARN] [1515101761.953724789]: init: message from matrixpilot, MSG-ID 150 ignored! Table has different entry.
[ WARN] [1515101761.953733463]: init: message from matrixpilot, MSG-ID 151 ignored! Table has different entry.
[ WARN] [1515101761.953741683]: init: message from matrixpilot, MSG-ID 152 ignored! Table has different entry.
[ WARN] [1515101761.953749656]: init: message from matrixpilot, MSG-ID 153 ignored! Table has different entry.
[ WARN] [1515101761.953757828]: init: message from matrixpilot, MSG-ID 155 ignored! Table has different entry.
[ WARN] [1515101761.953765933]: init: message from matrixpilot, MSG-ID 156 ignored! Table has different entry.
[ WARN] [1515101761.953773926]: init: message from matrixpilot, MSG-ID 157 ignored! Table has different entry.
[ WARN] [1515101761.953781986]: init: message from matrixpilot, MSG-ID 158 ignored! Table has different entry.
[ WARN] [1515101761.953790693]: init: message from matrixpilot, MSG-ID 170 ignored! Table has different entry.
[ WARN] [1515101761.953798750]: init: message from matrixpilot, MSG-ID 171 ignored! Table has different entry.
[ WARN] [1515101761.953807051]: init: message from matrixpilot, MSG-ID 172 ignored! Table has different entry.
[ WARN] [1515101761.953815336]: init: message from matrixpilot, MSG-ID 173 ignored! Table has different entry.
[ WARN] [1515101761.953828354]: init: message from matrixpilot, MSG-ID 174 ignored! Table has different entry.
[ WARN] [1515101761.953838771]: init: message from matrixpilot, MSG-ID 175 ignored! Table has different entry.
[ WARN] [1515101761.953849921]: init: message from matrixpilot, MSG-ID 176 ignored! Table has different entry.
[ WARN] [1515101761.953862231]: init: message from matrixpilot, MSG-ID 177 ignored! Table has different entry.
[ WARN] [1515101761.953896796]: init: message from matrixpilot, MSG-ID 178 ignored! Table has different entry.
[ WARN] [1515101761.953906249]: init: message from matrixpilot, MSG-ID 179 ignored! Table has different entry.
[ WARN] [1515101761.953917124]: init: message from matrixpilot, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1515101761.953925205]: init: message from matrixpilot, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1515101761.953933579]: init: message from matrixpilot, MSG-ID 182 ignored! Table has different entry.
[ WARN] [1515101761.953941459]: init: message from matrixpilot, MSG-ID 183 ignored! Table has different entry.
[ WARN] [1515101761.953949793]: init: message from matrixpilot, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1515101761.953958057]: init: message from matrixpilot, MSG-ID 185 ignored! Table has different entry.
[ WARN] [1515101761.953966716]: init: message from matrixpilot, MSG-ID 186 ignored! Table has different entry.
[ WARN] [1515101761.954105020]: init: message from paparazzi, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1515101761.954114260]: init: message from paparazzi, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1515101761.954124168]: init: message from paparazzi, MSG-ID 182 ignored! Table has different entry.
[ WARN] [1515101761.954134308]: init: message from paparazzi, MSG-ID 183 ignored! Table has different entry.
[ WARN] [1515101761.954142850]: init: message from paparazzi, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1515101761.954298821]: init: message from slugs, MSG-ID 170 ignored! Table has different entry.
[ WARN] [1515101761.954309867]: init: message from slugs, MSG-ID 172 ignored! Table has different entry.
[ WARN] [1515101761.954319608]: init: message from slugs, MSG-ID 173 ignored! Table has different entry.
[ WARN] [1515101761.954330146]: init: message from slugs, MSG-ID 176 ignored! Table has different entry.
[ WARN] [1515101761.954340681]: init: message from slugs, MSG-ID 177 ignored! Table has different entry.
[ WARN] [1515101761.954351066]: init: message from slugs, MSG-ID 179 ignored! Table has different entry.
[ WARN] [1515101761.954360079]: init: message from slugs, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1515101761.954368131]: init: message from slugs, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1515101761.954376448]: init: message from slugs, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1515101761.954385324]: init: message from slugs, MSG-ID 185 ignored! Table has different entry.
[ WARN] [1515101761.954393854]: init: message from slugs, MSG-ID 186 ignored! Table has different entry.
[ WARN] [1515101761.954401814]: init: message from slugs, MSG-ID 188 ignored! Table has different entry.
[ WARN] [1515101761.954412561]: init: message from slugs, MSG-ID 191 ignored! Table has different entry.
[ WARN] [1515101761.954421519]: init: message from slugs, MSG-ID 192 ignored! Table has different entry.
[ WARN] [1515101761.954430490]: init: message from slugs, MSG-ID 193 ignored! Table has different entry.
[ WARN] [1515101761.954439254]: init: message from slugs, MSG-ID 194 ignored! Table has different entry.
[ INFO] [1515101761.955432866]: udp0: Bind address: 127.0.0.1:14560
[ INFO] [1515101761.955773331]: udp0: Remote address: 127.0.0.1:14565
[ INFO] [1515101761.956086711]: GCS bridge disabled
[ERROR] [1515101761.971303164]: Tried to advertise a service that is already advertised in this node [/pid/set_parameters]
[ INFO] [1515101761.993219394]: SITL Test: Offboard control test running!
[ INFO] [1515101761.993246450]: Position control mode selected.
[ INFO] [1515101761.993254785]: Test option: square-shaped path...
[ INFO] [1515101761.993263916]: Testing...
[ INFO] [1515101762.005649227]: Plugin 3dr_radio loaded
[ INFO] [1515101762.007763465]: Plugin 3dr_radio initialized
[ INFO] [1515101762.007906940]: Plugin actuator_control loaded
[ INFO] [1515101762.011184063]: Plugin actuator_control initialized
[ INFO] [1515101762.037868583]: Plugin adsb loaded
[ INFO] [1515101762.042158571]: Plugin adsb initialized
[ INFO] [1515101762.042375405]: Plugin altitude loaded
[ INFO] [1515101762.043589982]: Plugin altitude initialized
[ INFO] [1515101762.043728168]: Plugin cam_imu_sync loaded
[ INFO] [1515101762.044517332]: Plugin cam_imu_sync initialized
[ INFO] [1515101762.044777564]: Plugin command loaded
[ INFO] [1515101762.055820198]: Plugin command initialized
[ INFO] [1515101762.055887582]: Plugin distance_sensor blacklisted
[ INFO] [1515101762.056038284]: Plugin fake_gps loaded
[ INFO] [1515101762.088957414]: Plugin fake_gps initialized
[ INFO] [1515101762.089150044]: Plugin ftp loaded
[ INFO] [1515101762.103880070]: Plugin ftp initialized
[ INFO] [1515101762.104035735]: Plugin global_position loaded
[ INFO] [1515101762.119724126]: Plugin global_position initialized
[ INFO] [1515101762.119871281]: Plugin hil loaded
[ INFO] [1515101762.135359100]: Plugin hil initialized
[ INFO] [1515101762.135535443]: Plugin home_position loaded
[ INFO] [1515101762.139036063]: Plugin home_position initialized
[ INFO] [1515101762.139172985]: Plugin imu loaded
[ INFO] [1515101762.139497324]: initialize IMU Plugin
[ INFO] [1515101762.146283451]: Plugin imu initialized
[ INFO] [1515101762.146428808]: Plugin local_position loaded
[ INFO] [1515101762.159052797]: Plugin local_position initialized
[ INFO] [1515101762.159230970]: Plugin manual_control loaded
[ INFO] [1515101762.163019293]: Plugin manual_control initialized
[ INFO] [1515101762.163286798]: Plugin mocap_pose_estimate loaded
[ INFO] [1515101762.168089503]: Plugin mocap_pose_estimate initialized
[ INFO] [1515101762.168228616]: Plugin odom loaded
[ INFO] [1515101762.172195241]: Plugin odom initialized
[ INFO] [1515101762.172403491]: Plugin param loaded
[ INFO] [1515101762.174992497]: Plugin param initialized
[ INFO] [1515101762.175103402]: Plugin px4flow loaded
[ INFO] [1515101762.179797331]: Plugin px4flow initialized
[ INFO] [1515101762.179820396]: Plugin rangefinder blacklisted
[ INFO] [1515101762.180008246]: Plugin rc_io loaded
[ INFO] [1515101762.183704542]: Plugin rc_io initialized
[ INFO] [1515101762.183727230]: Plugin safety_area blacklisted
[ INFO] [1515101762.183855735]: Plugin setpoint_accel loaded
[ INFO] [1515101762.187065235]: Plugin setpoint_accel initialized
[ INFO] [1515101762.187295394]: Plugin setpoint_attitude loaded
[INFO] [1515101762.200807, 0.000000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1515101762.207166738]: Plugin setpoint_attitude initialized
[ INFO] [1515101762.207334621]: Plugin setpoint_position loaded
[ INFO] [1515101762.213034770]: Plugin setpoint_position initialized
[ INFO] [1515101762.213178735]: Plugin setpoint_raw loaded
[ INFO] [1515101762.228015527]: Plugin setpoint_raw initialized
[ INFO] [1515101762.228178853]: Plugin setpoint_velocity loaded
[ INFO] [1515101762.234020048]: Plugin setpoint_velocity initialized
[ INFO] [1515101762.234255929]: Plugin sys_status loaded
[ INFO] [1515101762.240541030]: Plugin sys_status initialized
[ INFO] [1515101762.240701396]: Plugin sys_time loaded
[ INFO] [1515101762.247691947]: TM: Timesync mode: MAVLINK
[ INFO] [1515101762.248562286]: Plugin sys_time initialized
[ INFO] [1515101762.248706134]: Plugin vfr_hud loaded
[ INFO] [1515101762.250121844]: Plugin vfr_hud initialized
[ INFO] [1515101762.250146329]: Plugin vibration blacklisted
[ INFO] [1515101762.250276670]: Plugin vision_pose_estimate loaded
[ INFO] [1515101762.260663550]: Plugin vision_pose_estimate initialized
[ INFO] [1515101762.260973974]: Plugin vision_speed_estimate loaded
[ INFO] [1515101762.266048503]: Plugin vision_speed_estimate initialized
[ INFO] [1515101762.266274170]: Plugin waypoint loaded
[ INFO] [1515101762.270586203]: Plugin waypoint initialized
[ INFO] [1515101762.270813989]: Autostarting mavlink via USB on PX4
[ INFO] [1515101762.271125756]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1515101762.271239292]: Built-in MAVLink package version: 2018.1.1
[ INFO] [1515101762.271358504]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1515101762.271446380]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[INFO] [1515101762.309411, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[iris/spawn_iris-4] process has finished cleanly
log file: /home/fabrice/.ros/log/4189591e-f197-11e7-8903-b0359f2c094d/iris-spawn_iris-4*.log

### MAVROS version and platform
Mavros: 0.18.4
ROS: Kinetic
Ubuntu: 16.04
### Autopilot type and version

[  ] ArduPilot
[ x] PX4

Version: ?3.7.1?

### Node logs

```
copy output of mavros_node. Usually console where you run roslaunch
```

### Diagnostics

```
place here result of:
rostopic echo -n1 /diagnostics

WARNING: no messages received and simulated time is active.
Is /clock being published?


### Check ID

```
rosrun mavros checkid
```

**Comment by TSC21** [comment]
@FaboNo this package is not updated for ages now. I'm planning to update it to use with `PX4/sitl_gazebo` but I'm currently swamped with other stuff.

**Comment by FaboNo** [comment]
@TSC21 oh I see, I will try to do it on my side and if I succeed I will post it; in case other people want to do the same think :)

**Comment by FaboNo** [comment]
@TSC21 Yes I wrote a program in C++ and it works. Thank you for your concern.
I am trying to do the same thing with the offboard mode with our drone and I will probably let you know if I face some issues. Wish you a good week-end

**Comment by TSC21** [comment]
Oh ok, I thought you were planning to update `test_mavros` to use `sitl_gazebo` instead. Thanks anyway. A good weekend for you too.
