### ISSUE TITLE
Using MAVROS for mutliple quads

### ISSUE THREAD

**Issue by TrishantRoy** [mavlink/mavros#914]
Hey,
Can I use mavros getting and sending data for more than one quad connected via telemetry/wifi.

Will the quad 1 and quad 2 have different set of topics published?

I haven't tried actually since I currently don't have multiple flight controllers.

Thanks.

**Comment by vooon** [comment]
It is possible, but you should start independent mavros node for each drone. Easiest way - use namespaces.
