### ISSUE TITLE
PX4 unable to control attitude

### ISSUE THREAD

**Issue by OHussain** [mavlink/mavros#922]
### Issue details

Hello,
I am using the PX4 SITL in MAVROS for offboard attitude control. I started with the sample position control code from the user guide, and modified it to hold its position with no problem. Now I am trying to do the same with attitude control and it appears to be rejecting the offboard mode. This is peculiar as I have a flag in my code to verify that the offboard control is enabled, but the Pixhawk flashes the red rejection light when attempting to switch to offboard. I suspect it has something to do with the publishing, but am unsure. Any help would be greatly appreciated.

### Code

#include <ros/ros.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/Quaternion.h>
#include <sensor_msgs/Imu.h>
#include <geometry_msgs/Vector3.h>
#include <std_msgs/Float64.h>
#include <mavros_msgs/CommandBool.h>
#include <mavros_msgs/SetMode.h>
#include <mavros_msgs/State.h>
#include <mavros_msgs/RCIn.h>
#include <tf/transform_listener.h>
#include <tf/transform_datatypes.h>
#define Pi 3.14159

geometry_msgs::Vector3 Current_euler;
mavros_msgs::State current_state;
mavros_msgs::RCIn current_RC;

double Time = 0;

void state_cb(const mavros_msgs::State::ConstPtr& msg){
    current_state = *msg;
}

void RC_cb(const mavros_msgs::RCIn::ConstPtr& msg){
    current_RC = *msg;
}
void imuqua_cb(const sensor_msgs::Imu msg){
	tf::Quaternion IMU_q(msg.orientation.x,msg.orientation.y,msg.orientation.z,msg.orientation.w);
	tf::Matrix3x3 m(IMU_q);
	m.getRPY(Current_euler.x,Current_euler.y,Current_euler.z);
	Current_euler.z=-Current_euler.z;
	Current_euler.y=-Current_euler.y;
}
	bool wasArmed = false; //Check value for arming

int main(int argc, char **argv)
{
    ros::init(argc, argv, "offb_node");
    ros::NodeHandle nh;

    ros::Subscriber state_sub = nh.subscribe<mavros_msgs::State>
            ("mavros/state", 10, state_cb);
	ros::Subscriber RC_sub = nh.subscribe<mavros_msgs::RCIn>
            ("mavros/rc/in", 10, RC_cb);
	ros::Subscriber imuqua_sub = nh.subscribe<sensor_msgs::Imu>
            ("mavros/imu/data", 10, imuqua_cb);

 	ros::Publisher Eu_pub = nh.advertise<geometry_msgs::Vector3>//attitutude_pub
             ("Current_Euler", 10); 
	ros::Publisher Des_pub = nh.advertise<geometry_msgs::Vector3>//attitutude_pub
             ("Desired_Euler", 10); 
	 ros::ServiceClient arming_client = nh.serviceClient<mavros_msgs::CommandBool>
            ("mavros/cmd/arming");
   	 ros::ServiceClient set_mode_client = nh.serviceClient<mavros_msgs::SetMode>
            ("mavros/set_mode");
	
	ros::Publisher pub_att = nh.advertise<geometry_msgs::PoseStamped>("/mavros/setpoint_attitude/attitude",100);
	ros::Publisher pub_thr = nh.advertise<std_msgs::Float64>("mavros/setpoint_attitude/att_throttle",100);
	geometry_msgs::PoseStamped cmd_att;
	std_msgs::Float64 cmd_thr;

  int count = 1;
  double theta = 0.0;
  double v[3] = {1.0, 0.0, 0.0};
  double lambda =0.3;
  double v_norm = sqrt(v[0]*v[0] + v[1]*v[1] + v[2]*v[2]);
    //the setpoint publishing rate MUST be faster than 2Hz
  double SampleFreq = 50;
  double SampleTime = 0.02;  
  ros::Rate rate(SampleFreq);

  tf::Quaternion Dequaternion;

    // wait for FCU connection
    while(ros::ok() && !current_state.connected){
        ros::spinOnce();
        rate.sleep();
    }
        
    mavros_msgs::SetMode offb_set_mode;
    offb_set_mode.request.custom_mode = "OFFBOARD";

    mavros_msgs::CommandBool arm_cmd;
    arm_cmd.request.value = true;

    ros::Time last_request = ros::Time::now();

    while(ros::ok){

	double roll, pitch, yaw;

        if( current_state.mode != "OFFBOARD" && current_RC.channels[4] > 1800  &&
			(ros::Time::now() - last_request > ros::Duration(5.0))){
            if( set_mode_client.call(offb_set_mode)  && offb_set_mode.response.mode_sent){   

				ROS_INFO("Offboard enabled~~~~~~~~~~~~~~~~~~~~~~~");
				Time = 0;//Reset timer when offboard is enabled

            }
            last_request = ros::Time::now();

        } else if( !current_state.armed &&  wasArmed == false &&
                	(ros::Time::now() - last_request > ros::Duration(5.0))){
					if(current_RC.channels[6] > 1500){           	
						arm_cmd.request.value = true;	
						
						if( arming_client.call(arm_cmd) && 
	                    	arm_cmd.response.success){
	                    	ROS_INFO("Vehicle armed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
							wasArmed = true;
							}
						}
                	last_request = ros::Time::now();

				} else{//disarm if switch on channel 7 < 1500

						if(/*current_state.armed == true &&*/ wasArmed == true && current_RC.channels[6] < 1500){
							arm_cmd.request.value = false;
							
							if( arming_client.call(arm_cmd) && 
	                    		arm_cmd.response.success){
	                    		ROS_INFO("Vehicle disarmed///////////////////////");
								wasArmed = false;
							}
						}
						//last_request = ros::Time::now();
					}

	

		cmd_att.header.stamp = ros::Time::now();
		cmd_att.header.seq = count;
		cmd_att.header.frame_id = 1;
		cmd_att.pose.position.x = 0.0;//0.001*some_object.position_x;
		cmd_att.pose.position.y = 0.0;
		cmd_att.pose.position.z = 0.0;
	
		cmd_att.pose.orientation.x = sin(theta/2.0)*v[0]/v_norm;
		cmd_att.pose.orientation.y = sin(theta/2.0)*v[1]/v_norm;
		cmd_att.pose.orientation.z = sin(theta/2.0)*v[2]/v_norm;
		cmd_att.pose.orientation.w = cos(theta/2.0);

		cmd_thr.data = lambda;
		count++;
		theta = 0.3*sin(count/300.0);

		geometry_msgs::Vector3 Desired_Euler;
 		Desired_Euler.x = 0.3*sin(Pi*0.2*Time); 
		Desired_Euler.y = 0;
		Desired_Euler.z = 0;
		roll = Desired_Euler.x;
		pitch = -Desired_Euler.y;
		yaw = -Desired_Euler.z;

			pub_att.publish(cmd_att);
			pub_thr.publish(cmd_thr);
			Des_pub.publish(Desired_Euler);//attitude//attitude_pub.publish(attitude);
			Eu_pub.publish(Current_euler);

      
        ros::spinOnce();
        rate.sleep();
	Time  = Time + SampleTime;
	}

    return 0;
}

### MAVROS version and platform

Mavros: ?0.18.4?
ROS: ?Kinetic?
Ubuntu: ?16.04?

### Autopilot type and version

[  ] ArduPilot
[ X ] PX4

Version: ?3.7.1?

### Node logs

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: ROLL_180
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: ROLL_180
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_url: /dev/ttySAC0:921600
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/estimator_type: 3
 * /mavros/odometry/frame_tf/desired_frame: ned
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682389136
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    Trigger_sep (darc_rc_fly/Trigger)
    des_attitude_sep (darc_rc_fly/attitude_sep)
    mavros (mavros/mavros_node)

ROS_MASTER_URI=http://192.168.2.5:11311

core service [/rosout] found
process[mavros-1]: started with pid [2757]
process[des_attitude_sep-2]: started with pid [2759]
process[Trigger_sep-3]: started with pid [2760]
[ INFO] [1516319572.101456145]: FCU URL: /dev/ttySAC0:921600
[ WARN] [1516319572.107197118]: init: message from ASLUAV, MSG-ID 201 ignored! Table has different entry.
[ WARN] [1516319572.109275634]: init: message from autoquad, MSG-ID 150 ignored! Table has different entry.
[ WARN] [1516319572.109573923]: init: message from autoquad, MSG-ID 152 ignored! Table has different entry.
[ WARN] [1516319572.111574440]: init: message from matrixpilot, MSG-ID 150 ignored! Table has different entry.
[ WARN] [1516319572.111847062]: init: message from matrixpilot, MSG-ID 151 ignored! Table has different entry.
[ WARN] [1516319572.112128558]: init: message from matrixpilot, MSG-ID 152 ignored! Table has different entry.
[ WARN] [1516319572.112404347]: init: message from matrixpilot, MSG-ID 153 ignored! Table has different entry.
[ WARN] [1516319572.112916882]: init: message from matrixpilot, MSG-ID 155 ignored! Table has different entry.
[ WARN] [1516319572.113302294]: init: message from matrixpilot, MSG-ID 156 ignored! Table has different entry.
[ WARN] [1516319572.113617165]: init: message from matrixpilot, MSG-ID 157 ignored! Table has different entry.
[ WARN] [1516319572.113872204]: init: message from matrixpilot, MSG-ID 158 ignored! Table has different entry.
[ WARN] [1516319572.114631112]: init: message from matrixpilot, MSG-ID 170 ignored! Table has different entry.
[ WARN] [1516319572.114884400]: init: message from matrixpilot, MSG-ID 171 ignored! Table has different entry.
[ WARN] [1516319572.115171272]: init: message from matrixpilot, MSG-ID 172 ignored! Table has different entry.
[ WARN] [1516319572.115488185]: init: message from matrixpilot, MSG-ID 173 ignored! Table has different entry.
[ WARN] [1516319572.115876930]: init: message from matrixpilot, MSG-ID 174 ignored! Table has different entry.
[ WARN] [1516319572.116517047]: init: message from matrixpilot, MSG-ID 175 ignored! Table has different entry.
[ WARN] [1516319572.116866168]: init: message from matrixpilot, MSG-ID 176 ignored! Table has different entry.
[ WARN] [1516319572.117120998]: init: message from matrixpilot, MSG-ID 177 ignored! Table has different entry.
[ WARN] [1516319572.117423578]: init: message from matrixpilot, MSG-ID 178 ignored! Table has different entry.
[ WARN] [1516319572.118290317]: init: message from matrixpilot, MSG-ID 179 ignored! Table has different entry.
[ WARN] [1516319572.118564481]: init: message from matrixpilot, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1516319572.118861186]: init: message from matrixpilot, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1516319572.119121724]: init: message from matrixpilot, MSG-ID 182 ignored! Table has different entry.
[ WARN] [1516319572.119373971]: init: message from matrixpilot, MSG-ID 183 ignored! Table has different entry.
[ WARN] [1516319572.119646843]: init: message from matrixpilot, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1516319572.119994047]: init: message from matrixpilot, MSG-ID 185 ignored! Table has different entry.
[ WARN] [1516319572.120236377]: init: message from matrixpilot, MSG-ID 186 ignored! Table has different entry.
[ WARN] [1516319572.121815608]: init: message from paparazzi, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1516319572.122073980]: init: message from paparazzi, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1516319572.122320186]: init: message from paparazzi, MSG-ID 182 ignored! Table has different entry.
[ WARN] [1516319572.122871304]: init: message from paparazzi, MSG-ID 183 ignored! Table has different entry.
[ WARN] [1516319572.123703627]: init: message from paparazzi, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1516319572.125825602]: init: message from slugs, MSG-ID 170 ignored! Table has different entry.
[ WARN] [1516319572.126130098]: init: message from slugs, MSG-ID 172 ignored! Table has different entry.
[ WARN] [1516319572.126438553]: init: message from slugs, MSG-ID 173 ignored! Table has different entry.
[ WARN] [1516319572.126750007]: init: message from slugs, MSG-ID 176 ignored! Table has different entry.
[ WARN] [1516319572.127037170]: init: message from slugs, MSG-ID 177 ignored! Table has different entry.
[ WARN] [1516319572.127310542]: init: message from slugs, MSG-ID 179 ignored! Table has different entry.
[ WARN] [1516319572.127620580]: init: message from slugs, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1516319572.127852161]: init: message from slugs, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1516319572.128260364]: init: message from slugs, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1516319572.128547027]: init: message from slugs, MSG-ID 185 ignored! Table has different entry.
[ WARN] [1516319572.129262769]: init: message from slugs, MSG-ID 186 ignored! Table has different entry.
[ WARN] [1516319572.129516224]: init: message from slugs, MSG-ID 188 ignored! Table has different entry.
[ WARN] [1516319572.129812304]: init: message from slugs, MSG-ID 191 ignored! Table has different entry.
[ WARN] [1516319572.130117175]: init: message from slugs, MSG-ID 192 ignored! Table has different entry.
[ WARN] [1516319572.130412671]: init: message from slugs, MSG-ID 193 ignored! Table has different entry.
[ WARN] [1516319572.130686793]: init: message from slugs, MSG-ID 194 ignored! Table has different entry.
[ INFO] [1516319572.134968658]: serial0: device: /dev/ttySAC0 @ 921600 bps
[ INFO] [1516319572.137082591]: GCS bridge disabled
[ INFO] [1516319572.260156941]: Plugin 3dr_radio loaded
[ INFO] [1516319572.292079848]: Plugin 3dr_radio initialized
[ INFO] [1516319572.292472260]: Plugin actuator_control loaded
[ INFO] [1516319572.322639772]: Plugin actuator_control initialized
[ INFO] [1516319572.348608209]: Plugin adsb loaded
[ INFO] [1516319572.416793429]: Plugin adsb initialized
[ INFO] [1516319572.417793083]: Plugin altitude loaded
[ INFO] [1516319572.425232202]: Plugin altitude initialized
[ INFO] [1516319572.426128900]: Plugin cam_imu_sync loaded
[ INFO] [1516319572.430637345]: Plugin cam_imu_sync initialized
[ INFO] [1516319572.431796248]: Plugin command loaded
[ INFO] [1516319572.485460935]: Plugin command initialized
[ INFO] [1516319572.486421173]: Plugin debug_value loaded
[ INFO] [1516319572.540446522]: Plugin debug_value initialized
[ INFO] [1516319572.540889558]: Plugin distance_sensor blacklisted
[ INFO] [1516319572.542132835]: Plugin fake_gps loaded
[ INFO] [1516319572.733412780]: Plugin fake_gps initialized
[ INFO] [1516319572.734428143]: Plugin ftp loaded
[ INFO] [1516319572.802178951]: Plugin ftp initialized
[ INFO] [1516319572.803305021]: Plugin global_position loaded
[ INFO] [1516319573.056961548]: Plugin global_position initialized
[ INFO] [1516319573.058137825]: Plugin hil loaded
[ INFO] [1516319573.226973958]: Plugin hil initialized
[ INFO] [1516319573.228258192]: Plugin home_position loaded
[ INFO] [1516319573.261757789]: Plugin home_position initialized
[ INFO] [1516319573.262845317]: Plugin imu loaded
[ INFO] [1516319573.449042533]: Plugin imu initialized
[ INFO] [1516319573.450211060]: Plugin local_position loaded
[ INFO] [1516319573.541174589]: Plugin local_position initialized
[ INFO] [1516319573.542224077]: Plugin manual_control loaded
[ INFO] [1516319573.552211415]: Plugin manual_control initialized
[ INFO] [1516319573.553113945]: Plugin mocap_pose_estimate loaded
[ INFO] [1516319573.603976666]: Plugin mocap_pose_estimate initialized
[ INFO] [1516319573.604895613]: Plugin odom loaded
[ INFO] [1516319573.664492937]: Plugin odom initialized
[ INFO] [1516319573.665539424]: Plugin param loaded
[ INFO] [1516319573.697386541]: Plugin param initialized
[ INFO] [1516319573.698451945]: Plugin px4flow loaded
[ INFO] [1516319573.817045849]: Plugin px4flow initialized
[ INFO] [1516319573.817400553]: Plugin rangefinder blacklisted
[ INFO] [1516319573.818468874]: Plugin rc_io loaded
[ INFO] [1516319573.852618379]: Plugin rc_io initialized
[ INFO] [1516319573.853063957]: Plugin safety_area blacklisted
[ INFO] [1516319573.853998696]: Plugin setpoint_accel loaded
[ INFO] [1516319573.893876798]: Plugin setpoint_accel initialized
[ INFO] [1516319573.895074784]: Plugin setpoint_attitude loaded
[ INFO] [1516319574.048567060]: Plugin setpoint_attitude initialized
[ INFO] [1516319574.050293123]: Plugin setpoint_position loaded
[ INFO] [1516319574.225052601]: Plugin setpoint_position initialized
[ INFO] [1516319574.226423543]: Plugin setpoint_raw loaded
[ INFO] [1516319574.337898284]: Plugin setpoint_raw initialized
[ INFO] [1516319574.339224018]: Plugin setpoint_velocity loaded
[ INFO] [1516319574.404658688]: Plugin setpoint_velocity initialized
[ INFO] [1516319574.406132712]: Plugin sys_status loaded
[ INFO] [1516319574.469493782]: Plugin sys_status initialized
[ INFO] [1516319574.470689017]: Plugin sys_time loaded
[ INFO] [1516319574.507457200]: TM: Timesync mode: MAVLINK
[ INFO] [1516319574.514280076]: Plugin sys_time initialized
[ INFO] [1516319574.515817474]: Plugin vfr_hud loaded
[ INFO] [1516319574.539909350]: Plugin vfr_hud initialized
[ INFO] [1516319574.540262971]: Plugin vibration blacklisted
[ INFO] [1516319574.541461457]: Plugin vision_pose_estimate loaded
[ INFO] [1516319574.646499650]: Plugin vision_pose_estimate initialized
[ INFO] [1516319574.647427639]: Plugin vision_speed_estimate loaded
[ INFO] [1516319574.688373312]: Plugin vision_speed_estimate initialized
[ INFO] [1516319574.689390717]: Plugin waypoint loaded
[ INFO] [1516319574.741019137]: Plugin waypoint initialized
[ INFO] [1516319574.741458340]: Autostarting mavlink via USB on PX4
[ INFO] [1516319574.742030583]: Built-in SIMD instructions: None
[ INFO] [1516319574.742362287]: Built-in MAVLink package version: 2018.1.1
[ INFO] [1516319574.742775365]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1516319574.743196235]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ WARN] [1516319574.748096385]: TM: Clock skew detected (-1516319345.542399406 s). Hard syncing clocks.
[ INFO] [1516319574.749058123]: IMU: High resolution IMU detected!
[ INFO] [1516319574.750504064]: IMU: Attitude quaternion IMU detected!
[ INFO] [1516319574.772170845]: RC_CHANNELS message detected!
[ INFO] [1516319575.072472228]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1516319575.078016078]: RC_CHANNELS message detected!
[ INFO] [1516319575.088747740]: IMU: High resolution IMU detected!
[ INFO] [1516319575.089446190]: IMU: Attitude quaternion IMU detected!
[ INFO] [1516319576.087123094]: VER: 1.1: Capabilities         0x00000000000024ef
[ INFO] [1516319576.087520922]: VER: 1.1: Flight software:     01060500 (00000000B6F2E14B)
[ INFO] [1516319576.088029875]: VER: 1.1: Middleware software: 01060500 (0000000000000001)
[ INFO] [1516319576.088365287]: VER: 1.1: OS software:         000000c0 (0000000000000001)
[ INFO] [1516319576.088668034]: VER: 1.1: Board hardware:      00000011
[ INFO] [1516319576.088964488]: VER: 1.1: VID/PID:             26ac:0011
[ INFO] [1516319576.089254152]: VER: 1.1: UID:                 3034510937383933
[ WARN] [1516319576.138111980]: CMD: Unexpected command 520, result 0
[ INFO] [1516319585.073506400]: HP: requesting home position
[ INFO] [1516319590.078335484]: WP: mission received
[ INFO] [1516319595.073217427]: HP: requesting home position
[ INFO] [1516319605.073125361]: HP: requesting home position
[ INFO] [1516319605.269395556]: Vehicle armed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ INFO] [1516319615.073976641]: HP: requesting home position
[ INFO] [1516319615.864072009]: Offboard enabled~~~~~~~~~~~~~~~~~~~~~~~
[ WARN] [1516319615.872200578]: CMD: Unexpected command 176, result 1
[ INFO] [1516319622.411947639]: Vehicle disarmed///////////////////////
[ INFO] [1516319625.073051539]: HP: requesting home position

### Diagnostics

header: 
  seq: 32
  stamp: 
    secs: 1516319610
    nsecs: 244350323
  frame_id: ''
status: 
  - 
    level: 0
    name: mavros: FCU connection
    message: connected
    hardware_id: /dev/ttySAC0:921600
    values: 
      - 
        key: Received packets:
        value: 19563
      - 
        key: Dropped packets:
        value: 0
      - 
        key: Buffer overruns:
        value: 0
      - 
        key: Parse errors:
        value: 0
      - 
        key: Rx sequence number:
        value: 219
      - 
        key: Tx sequence number:
        value: 22
      - 
        key: Rx total bytes:
        value: 774302
      - 
        key: Tx total bytes:
        value: 18648
      - 
        key: Rx speed:
        value: 30706.000000
      - 
        key: Tx speed:
        value: 757.000000
  - 
    level: 2
    name: mavros: GPS
    message: No satellites
    hardware_id: /dev/ttySAC0:921600
    values: 
      - 
        key: Satellites visible
        value: 0
      - 
        key: Fix type
        value: 0
      - 
        key: EPH (m)
        value: Unknown
      - 
        key: EPV (m)
        value: Unknown
  - 
    level: 0
    name: mavros: Heartbeat
    message: Normal
    hardware_id: /dev/ttySAC0:921600
    values: 
      - 
        key: Heartbeats since startup
        value: 36
      - 
        key: Frequency (Hz)
        value: 1.000042
      - 
        key: Vehicle type
        value: Quadrotor
      - 
        key: Autopilot type
        value: PX4 Autopilot
      - 
        key: Mode
        value: MANUAL
      - 
        key: System status
        value: Active
  - 
    level: 0
    name: mavros: System
    message: Normal
    hardware_id: /dev/ttySAC0:921600
    values: 
      - 
        key: Sensor present
        value: 0x00000000
      - 
        key: Sensor enabled
        value: 0x00000000
      - 
        key: Sensor helth
        value: 0x00000000
      - 
        key: CPU Load (%)
        value: 58.5
      - 
        key: Drop rate (%)
        value: 0.0
      - 
        key: Errors comm
        value: 0
      - 
        key: Errors count #1
        value: 0
      - 
        key: Errors count #2
        value: 0
      - 
        key: Errors count #3
        value: 0
      - 
        key: Errors count #4
        value: 0
  - 
    level: 0
    name: mavros: Battery
    message: Normal
    hardware_id: /dev/ttySAC0:921600
    values: 
      - 
        key: Voltage
        value: 11.45
      - 
        key: Current
        value: 2.1
      - 
        key: Remaining
        value: 68.0
  - 
    level: 0
    name: mavros: Time Sync
    message: Normal
    hardware_id: /dev/ttySAC0:921600
    values: 
      - 
        key: Timesyncs since startup
        value: 356
      - 
        key: Frequency (Hz)
        value: 10.000422
      - 
        key: Last dt (ms)
        value: -0.069912
      - 
        key: Mean dt (ms)
        value: 0.010035
      - 
        key: Last system time (s)
        value: 264.676425000
      - 
        key: Time offset (s)
        value: 1516319345.540253162
---

### Check ID

OK. I got messages from 1:1.

---
Received 7514 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 1, 2, 140, 141, 147, 30, 31, 32, 36, 65, 70, 74, 76, 77, 83, 230, 231, 105, 111, 241, 245

**Comment by OHussain** [comment]
No. We used setpoint_attitude/raw imstead of setpoint_attitude/attitude to work around the problem, but the original issue is still there. I’ll close it, but I have to wonder what setpoint_attitude/attitude is meant for.

**Comment by TSC21** [comment]
> I’ll close it, but I have to wonder what setpoint_attitude/attitude is meant for.

Did you use it properly? Did you generate the attitude and the thrust setpoints and published them to the right topics? What MAVROS version were you even using? From my analysis you are using an old MAVROS version where the `setpoint_attitude` didn't even have the `message_filters` to sync the the attitude and thrust topics (you are using `Float64` for the Thrust topic when the current msg is `mavros_msgs/Thurst`.

**Comment by TSC21** [comment]
This is the current code for a reference: https://github.com/mavlink/mavros/blob/master/mavros/src/plugins/setpoint_attitude.cpp

**Comment by viswanarayanans** [comment]
I have a similar problem. I did "rostopic list". But "setpoint_attitude/attitude" is not in the list. I could see only "setpoint_attitude/cmd_vel" and "setpoint_attitude/thrust". I am using mavros with PX4. Is there anything that I need to specify to see the topic?
