### ISSUE TITLE
error roslaunch mavros

### ISSUE THREAD

**Issue by lp02781** [mavlink/mavros#926]
i had installed mavros on ubuntu 16.04 ROS distro kinetic, but when i connect my pixhawk to laptop and running `roslaunch mavros apm.launch`, this error appears 
```

```

lp02781@Lenovo:~$ roslaunch mavros apm.launch
... logging to /home/lp02781/.ros/log/24d26d28-00ca-11e8-baff-acb57df86549/roslaunch-Lenovo-9655.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Lenovo:44840/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 0.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 0.0
 * /mavros/distance_sensor/rangefinder_pub/field_of_view: 0.0
 * /mavros/distance_sensor/rangefinder_pub/frame_id: lidar
 * /mavros/distance_sensor/rangefinder_pub/id: 0
 * /mavros/distance_sensor/rangefinder_pub/send_tf: False
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/rangefinder_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/rangefinder_sub/id: 1
 * /mavros/distance_sensor/rangefinder_sub/orientation: PITCH_270
 * /mavros/distance_sensor/rangefinder_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_url: /dev/ttyACM0:57600
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/estimator_type: 3
 * /mavros/odometry/frame_tf/desired_frame: ned
 * /mavros/plugin_blacklist: ['actuator_contro...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682389136
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: False
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: NONE
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.12

NODES
  /
    mavros (mavros/mavros_node)

auto-starting new master
process[master]: started with pid [9666]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 24d26d28-00ca-11e8-baff-acb57df86549
process[rosout-1]: started with pid [9679]
started core service [/rosout]
process[mavros-2]: started with pid [9697]
[ INFO] [1516772884.177725904]: FCU URL: /dev/ttyACM0:57600
[ WARN] [1516772884.178295560]: init: message from ASLUAV, MSG-ID 201 ignored! Table has different entry.
[ WARN] [1516772884.178470638]: init: message from autoquad, MSG-ID 150 ignored! Table has different entry.
[ WARN] [1516772884.178487881]: init: message from autoquad, MSG-ID 152 ignored! Table has different entry.
[ WARN] [1516772884.178645067]: init: message from matrixpilot, MSG-ID 150 ignored! Table has different entry.
[ WARN] [1516772884.178660248]: init: message from matrixpilot, MSG-ID 151 ignored! Table has different entry.
[ WARN] [1516772884.178676468]: init: message from matrixpilot, MSG-ID 152 ignored! Table has different entry.
[ WARN] [1516772884.178693309]: init: message from matrixpilot, MSG-ID 153 ignored! Table has different entry.
[ WARN] [1516772884.178710136]: init: message from matrixpilot, MSG-ID 155 ignored! Table has different entry.
[ WARN] [1516772884.178727062]: init: message from matrixpilot, MSG-ID 156 ignored! Table has different entry.
[ WARN] [1516772884.178742852]: init: message from matrixpilot, MSG-ID 157 ignored! Table has different entry.
[ WARN] [1516772884.178759266]: init: message from matrixpilot, MSG-ID 158 ignored! Table has different entry.
[ WARN] [1516772884.178774361]: init: message from matrixpilot, MSG-ID 170 ignored! Table has different entry.
[ WARN] [1516772884.178789510]: init: message from matrixpilot, MSG-ID 171 ignored! Table has different entry.
[ WARN] [1516772884.178804140]: init: message from matrixpilot, MSG-ID 172 ignored! Table has different entry.
[ WARN] [1516772884.178819087]: init: message from matrixpilot, MSG-ID 173 ignored! Table has different entry.
[ WARN] [1516772884.178833682]: init: message from matrixpilot, MSG-ID 174 ignored! Table has different entry.
[ WARN] [1516772884.178848382]: init: message from matrixpilot, MSG-ID 175 ignored! Table has different entry.
[ WARN] [1516772884.178862998]: init: message from matrixpilot, MSG-ID 176 ignored! Table has different entry.
[ WARN] [1516772884.178878361]: init: message from matrixpilot, MSG-ID 177 ignored! Table has different entry.
[ WARN] [1516772884.178892937]: init: message from matrixpilot, MSG-ID 178 ignored! Table has different entry.
[ WARN] [1516772884.178907808]: init: message from matrixpilot, MSG-ID 179 ignored! Table has different entry.
[ WARN] [1516772884.178922449]: init: message from matrixpilot, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1516772884.178937235]: init: message from matrixpilot, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1516772884.178951999]: init: message from matrixpilot, MSG-ID 182 ignored! Table has different entry.
[ WARN] [1516772884.178966934]: init: message from matrixpilot, MSG-ID 183 ignored! Table has different entry.
[ WARN] [1516772884.178982800]: init: message from matrixpilot, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1516772884.178998062]: init: message from matrixpilot, MSG-ID 185 ignored! Table has different entry.
[ WARN] [1516772884.179013278]: init: message from matrixpilot, MSG-ID 186 ignored! Table has different entry.
[ WARN] [1516772884.179170268]: init: message from paparazzi, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1516772884.179185076]: init: message from paparazzi, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1516772884.179201214]: init: message from paparazzi, MSG-ID 182 ignored! Table has different entry.
[ WARN] [1516772884.179216126]: init: message from paparazzi, MSG-ID 183 ignored! Table has different entry.
[ WARN] [1516772884.179231402]: init: message from paparazzi, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1516772884.179384056]: init: message from slugs, MSG-ID 170 ignored! Table has different entry.
[ WARN] [1516772884.179398584]: init: message from slugs, MSG-ID 172 ignored! Table has different entry.
[ WARN] [1516772884.179414452]: init: message from slugs, MSG-ID 173 ignored! Table has different entry.
[ WARN] [1516772884.179429639]: init: message from slugs, MSG-ID 176 ignored! Table has different entry.
[ WARN] [1516772884.179444831]: init: message from slugs, MSG-ID 177 ignored! Table has different entry.
[ WARN] [1516772884.179459876]: init: message from slugs, MSG-ID 179 ignored! Table has different entry.
[ WARN] [1516772884.179475282]: init: message from slugs, MSG-ID 180 ignored! Table has different entry.
[ WARN] [1516772884.179490611]: init: message from slugs, MSG-ID 181 ignored! Table has different entry.
[ WARN] [1516772884.179505232]: init: message from slugs, MSG-ID 184 ignored! Table has different entry.
[ WARN] [1516772884.179520417]: init: message from slugs, MSG-ID 185 ignored! Table has different entry.
[ WARN] [1516772884.179535454]: init: message from slugs, MSG-ID 186 ignored! Table has different entry.
[ WARN] [1516772884.179551037]: init: message from slugs, MSG-ID 188 ignored! Table has different entry.
[ WARN] [1516772884.179567204]: init: message from slugs, MSG-ID 191 ignored! Table has different entry.
[ WARN] [1516772884.179582009]: init: message from slugs, MSG-ID 192 ignored! Table has different entry.
[ WARN] [1516772884.179596853]: init: message from slugs, MSG-ID 193 ignored! Table has different entry.
[ WARN] [1516772884.179611900]: init: message from slugs, MSG-ID 194 ignored! Table has different entry.
[ INFO] [1516772884.179991857]: serial0: device: /dev/ttyACM0 @ 57600 bps
[FATAL] [1516772884.180150691]: FCU: DeviceError:serial:open: No such file or directory
================================================================================REQUIRED process [mavros-2] has died!
process has finished cleanly
log file: /home/lp02781/.ros/log/24d26d28-00ca-11e8-baff-acb57df86549/mavros-2*.log
Initiating shutdown!
================================================================================
[mavros-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

```

**Comment by lp02781** [comment]
what should i do??

**Comment by vooon** [comment]
You should provide correct URL to FCU.
```
[FATAL] [1516772884.180150691]: FCU: DeviceError:serial:open: No such file or directory
```
