### ISSUE TITLE
catkin_make error in setMode service

### ISSUE THREAD

**Issue by TrishantRoy** [mavlink/mavros#934]
Hey,
I am using a code for offboard control. This code is for changing the mode of the quadcopter.
![image](https://user-images.githubusercontent.com/27051377/35593769-d9fc5544-0636-11e8-9152-9f43549fd570.png)

On doing catkin_make, I am getting the following error:
![image](https://user-images.githubusercontent.com/27051377/35593513-17f76efc-0636-11e8-86fe-9a5f3ec69394.png)

Thanks.

**Comment by anassinator** [comment]
You should be writing `srv_setMode.response.mode_sent` as seen here: https://github.com/mavlink/mavros/blob/master/mavros_msgs/srv/SetMode.srv#L22

**Comment by TrishantRoy** [comment]
Thank you @anassinator
