### ISSUE TITLE
TODO: update distance_sensor orientation convention

### ISSUE THREAD

**Issue by TSC21** [mavlink/mavros#935]
https://github.com/mavlink/mavlink/blob/master/message_definitions/v1.0/common.xml#L4070

**Comment by vooon** [comment]
For what? We already use `MAV_SENSOR_ORIENTATION`.

**Comment by TSC21** [comment]
I'm referring to this only: https://github.com/mavlink/mavros/blob/master/mavros/launch/px4_config.yaml#L136

**Comment by vooon** [comment]
Here dosc more readable: https://mavlink.io/en/messages/common.html#DISTANCE_SENSOR
