### ISSUE TITLE
Regain Manual Control

### ISSUE THREAD

**Issue by TrishantRoy** [mavlink/mavros#936]
Hey,
I have using mavros for Off-board control (Pixhawk, Quadcopter).

I am using the /mavros/rc/override topic to publish the channel values.

But, as a safety feature, I want to regain manual control using the transmitter on a particular condition, say, on using one of the unused channels.

I had read that publishing the value 65535 on the channel will lead to regain in manual mode.
(Is this correct?)

The code:
`msg_override.channels[0] = 65535;
 msg_override.channels[1] = 65535;
 msg_override.channels[2] = 65535;
 msg_override.channels[3] = 65535;
 rc_override_pub.publish(msg_override);
ros::shutdown();`

This isn't working.

What is the mistake? Is there any other alternative to implement the safety feature?

Thanks.

**Comment by TSC21** [comment]
Not MAVROS related. Bring this to the firmware repositories.

**Comment by TrishantRoy** [comment]
Just found a previous issue in which it said to publish 0 to regain control.
https://github.com/mavlink/mavros/issues/22

![image](https://user-images.githubusercontent.com/27051377/35722869-0d64ba28-081e-11e8-800b-b83bb37a7415.png)

I will try this and post my result here.

Thanks.

**Comment by TrishantRoy** [comment]
Hey,
You have to publish 0 to regain manual control.

`msg_override.channels[0] = 0;
        msg_override.channels[1] = 0;
        msg_override.channels[2] = 0;
        msg_override.channels[3] = 0;
        rc_override_pub.publish(msg_override);
        ros::shutdown();`
