### ISSUE TITLE
Update Mavlink msgs 

### ISSUE THREAD

**Issue by TSC21** [mavlink/mavros#94]
mavlink/c_library@23a8961. New msg definitions!

Some updates:

Mandatory:
- [x] `LOCAL_NED_POSITION_SETPOINT_EXTERNAL` to [SET_POSITION_TARGET_LOCAL_NED](https://pixhawk.ethz.ch/mavlink/#SET_POSITION_TARGET_LOCAL_NED)
- [x] `ATTITUDE_SETPOINT_EXTERNAL` to [SET_ATTITUDE_TARGET](https://pixhawk.ethz.ch/mavlink/#SET_ATTITUDE_TARGET)

Optional:
- [ ] [LOCAL_POSITION_NED](https://pixhawk.ethz.ch/mavlink/#LOCAL_POSITION_NED) to [LOCAL_POSITION_NED_COV](https://pixhawk.ethz.ch/mavlink/#LOCAL_POSITION_NED_COV)
- [ ] [GLOBAL_POSITION_INT](https://pixhawk.ethz.ch/mavlink/#GLOBAL_POSITION_INT) to [GLOBAL_POSITION_INT_COV](https://pixhawk.ethz.ch/mavlink/#GLOBAL_POSITION_INT_COV)
- [ ] [ATTITUDE_QUATERNION](https://pixhawk.ethz.ch/mavlink/#ATTITUDE_QUATERNION) to [ATTITUDE_QUATERNION_COV](https://pixhawk.ethz.ch/mavlink/#ATTITUDE_QUATERNION_COV)

Without the first ones is not possible to test setpoints. Does the ros-*-mavlink will be getting the new message definitions?

**Comment by vooon** [comment]
I think we may close this issue. Maybe better use new message for complete IMU+ATTITUDE data in one piece.
