### ISSUE TITLE
Simple example for setpoint's

### ISSUE THREAD

**Issue by Ahrovan** [mavlink/mavros#948]
Is a simple example for the following to get the right concept to get started:
1. setpoint_accel
2. setpoint_attitude
3. setpoint_position
4. setpoint_raw
5. setpoint_velocity

### Autopilot Support
[APM], [PX4*]

**Comment by TSC21** [comment]
@Ahrovan what is the purpose of opening this issue?

**Comment by Ahrovan** [comment]
This issues has been opened to promote the concept of any of the above. But surely here is not the right place to bring an example and discuss how to use them. Please close this issues and introduce the best place to discuss how to use them.
Thanks

**Comment by TSC21** [comment]
There are examples for the above on the devguides of the autopilots. At least for PX4. Don't know if there are any for APM. Though this would be autopilot specific cause it depends on the flight mode (OFFBOARD or GUIDED) and on the support for each type of setpoint. Though this should be moved to the respective autopilots discussion forums. Closing.
