### ISSUE TITLE
obstacle_distance: report LaserScan.ranges (meters) as OBSTACLE_DISTANCE.ranges (centimeters)

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#950]
With #949 i found bug in message filler. It should convert meters to centimeters and then fill message.

**Comment by TSC21** [comment]
Ok I see the bug now. @mrivi will update this soon.

**Comment by vooon** [comment]
No, that bug is mine :) Just i'm trying to imagine best solution. And i'm recommend that `std::copy()` code.

**Comment by TSC21** [comment]
If you divide every value by 10 and round it inside `std::copy()` it should work.

**Comment by vooon** [comment]
1 m == 100 cm. Div 1e2.

**Comment by TSC21** [comment]
Forgot a zero :)

**Comment by vooon** [comment]
Hehe, we completely screwed up on conversions :D
We should multiply by 100, not divide to get m->cm. Fixed.

**Comment by TSC21** [comment]
Ahahah nevermind
