### ISSUE TITLE
using  /mavros/fake_gps/mocap/tf

### ISSUE THREAD

**Issue by SubMishMar** [mavlink/mavros#954]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

Hi, Does anyone know how to override the gps satellite data with one's own fake_gps data? I am using aruco markers for indoor localization and I stream the pose of a quadrotor estimated using aruco markers over the topic /mavros/fake_gps/mocap/tf . How to ensure that the FCU prefers this data over the data received from the GPS onboard the quadrotor?

### MAVROS version and platform

Mavros: ?0.18.4?
ROS: ?Kinetic?
Ubuntu: ?16.04?

### Autopilot type and version

[X ] ArduPilot
[  ] PX4

**Comment by TSC21** [comment]
Not MAVROS related. You should ask on APM forums.
