### ISSUE TITLE
Installing older versions of mavros

### ISSUE THREAD

**Issue by mellonUAV** [mavlink/mavros#955]
I had a previous version of mavros that I installed via sudo apt-get install ros-kinetic-mavros ros-kinetic-mavros-extras. I am trying to install 0.18.3, and I am new to these stuff. Can you please explain how can I achieve this. Thank you!

Regards,

### MAVROS version and platform

Mavros: 0.23.0
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[ x] ArduPilot
[  ] PX4

Version: 3.6.0

**Comment by TSC21** [comment]
Check https://github.com/mavlink/mavros/issues/941
