### ISSUE TITLE
Using mavros with ROS kinetic

### ISSUE THREAD

**Issue by myeabhishek** [mavlink/mavros#978]
Hi Team,

I need a companion computer with ROS and MAVROS. I am inclined to choose mavros with ROS kinetic, however, the CI status on repository says that the build is unstable. 

Can someone please shed some light on what issues I might run into if I go with this approach?

**Comment by korigod** [comment]
The latest release passed CI on Kinetic: http://build.ros.org/job/Kdev__mavros__ubuntu_xenial_amd64/131/
We also use MAVROS on Kinetic without issues.
