### ISSUE TITLE
type_mask is always 0 for setpoint_raw

### ISSUE THREAD

**Issue by AlexisTM** [mavlink/mavros#992]
## Issue details

I send setpoints with `~setpoint_raw/local` with type_mask `1991` (vx, vy, vz, vyaw).

The MAVLink analyzer is reporting a `type_mask= 0`.

The `~setpoint_raw/target_local` topic reports a `type_mask of 0`.  

Linked to PX4/Firmware#9200

### MAVROS version and platform

Mavros: 0.23.1
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[x] PX4 1.6.5
[x] PX4 1.7.5

**Comment by AlexisTM** [comment]
![image](https://user-images.githubusercontent.com/6976744/38417442-9959b1cc-3998-11e8-87e5-33e2fda8ad12.png)

Left is `~setpoint_raw/local` and right is `setpoint_raw/target_local`

**Comment by vooon** [comment]
Problem in firmware side.

https://github.com/mavlink/mavros/blob/master/mavros/src/plugins/setpoint_raw.cpp#L88

**Comment by vooon** [comment]
Yes, 0 comes from PX4.

**Comment by AlexisTM** [comment]
@vooon Actually, from what I see, the `target_local` topic is not linked to the offboard mode. It is filled with the position command, the velocity command and acceleration command resulting from the setpoints sent from the Offboard mode /or RC, ...

Therefore, the type_mask seems to be correct as all the data is filled.

Yet, we can arm and takeoff before this setpoint to be instantiated and publishing and when we do, the system will rotate because of the yaw setpoint which is still 0. 

There is no problem in Mavros; closing it :)
