### ISSUE TITLE
Failed to build mavros (0.24.0)

### ISSUE THREAD

**Issue by sabbaghp** [mavlink/mavros#993]
Current Error:

........./mavros/mavros_extras/src/plugins/vision_pose_estimate.cpp:128:46: error: ‘struct mavlink::common::msg::VISION_POSITION_ESTIMATE’ has no member named ‘covariance’
   ftf::covariance_urt_to_mavlink(cov_map, vp.covariance);

New release was pushed yesterday 4/6/18.

Mavros: 0.24.0
Ros: Kinetic
Ubuntu: 16.04
Autopilot: PX4

Standard libs (geographiclib-tools, mavlink, libgeographic-dev, ros-kinetic-control-toolbox, ros-kinetic-mavros-msgs) and scripts (install_geographiclib_datasets.sh).

Is there a new _mavlink_ library not available yet?

**Comment by vooon** [comment]
Did you update mavlink?

**Comment by MattMgn** [comment]
Same problem here
I have first installed mavros from binaries without problem (so mavlink should be up to date, right ?). But when i compile from source, I also get this error.
Any idea ?

**Comment by mhkabir** [comment]
Mavlink from apt isn't updated yet, I guess. Please also compile mavlink-gbp-release from source.

**Comment by vooon** [comment]
Simple rule: if you build mavros from source then build mavlink also. Just follow [manual][1].

[1]: https://github.com/mavlink/mavros/tree/master/mavros#source-installation

**Comment by sabbaghp** [comment]
Good point and rule to follow.
It all checks out. 
Thanks @vooon @mhkabir.
